### PR TITLE
refactor: remove lonely ? in query-string

### PR DESCRIPTION
**Pull request by mblarsen**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?

Feature was wanted by myself. So created the PR.

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No, only a small change.

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)

I updated the relevant test.

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.

When using the feature `updatesQueryString` it would leave append `?` a single (lonely) sign if every parameter for whatever reason has been filtered away (by except or otherwise). 

So your URL would go from a clean `/` to `/?`.

This PR prevents adding an empty query set.

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by mblarsen** [comment]
That failing test is a bit of a mystery. What values after being stringified would be truthy and then show up as an empty string? (in the context of the unit test)

**Comment by nuernbergerA** [comment]
@mblarsen please make sure you run `npm run build` and commit the `dist` files

**Comment by mblarsen** [comment]
> @mblarsen please make sure you run `npm run build` and commit the `dist` files

Thanks for pointing that out @nuernbergerA - The tests are passing now.

**Comment by calebporzio** [comment]
Love it, thanks!

**Comment by lancepioch** [comment]
@all-contributors please add @mblarsen for maintenance

**Pull request merged**
