### PR TITLE
Handle error in XMLHttpRequest and pass to uploadErrored

### PR DESCRIPTION
**Pull request by jtolj**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

Sorry, I did not start a discussion first, but this is a small PR that should be quick to review.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

Yes.

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No.

4️⃣ Does it include tests? (Required)

It does not, but I didn't see where the upload component was tested in the browser. I would be happy to add tests for this if there is an existing place to add one :).

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

This adds an event listener on the XMLHttpRequest for file uploads in UploadManager.js. 

Previously an error thrown here was not propagated up to the component, so the error callback is not triggered for things like CORS errors, aggressive Ad blocking extensions, or 500 errors (which we have encountered uploading directly to Backblaze B2).

In our use case, this results in the state we expose to the user getting stuck in "Uploading", even though the file has failed to upload.

Thanks for considering!

Jesse

### CODE REVIEW

**Comment by joshhanley** [comment]
@jtolj thanks for the PR! Yeah if you could add a test for this, that'd be great! If there aren't any browser tests for uploads, feel free to add a new one for this PR.

**Comment by jtolj** [comment]
@joshhanley Thanks, I'll figure out a way to test it as soon as I can.

**Comment by joshhanley** [comment]
@jtolj thanks! Much appreciated 🙂

**Comment by joshhanley** [comment]
@jtolj just wondering how you went with the tests? If you can't get the tests running, would you be able to provide a sample component class and view, which demonstrates the issue that this PR fixes? Thanks!

**Comment by jtolj** [comment]
@joshhanley 
So sorry for the delay, I have a rough idea for an approach to testing this by injecting some javascript to override the XMLHttpRequest prototype but I haven't had time to sit down and try it out.

I'll try to get to it within the next week.

**Comment by jtolj** [comment]
@joshhanley 

So sorry, I spent a little time on this but still having trouble coming up with a realistic test without hitting the network.

I do have a reproducible example and screen captures of the current release and this branch. I will hopefully have more time to look at the tests in the next couple of weeks.


`app/Http/Livewire/CorsExample.php`
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithFileUploads;

class CorsExample extends Component
{
    use WithFileUploads;

    public $photo;

    public function save()
    {
        $this->validate(
            [
            'photo' => 'required|file|max:1024',
            ]
        );
    }

    public function render()
    {
        return view('livewire.cors-example');
    }
}

```


`resources/views/livewire/cors-example.blade.php`
```
<div>
    <form wire:submit.prevent="save">
        <input type="file" wire:model="photo">

        @error('photo')
            <div class="error">{{ $message }}</div>
        @enderror

        <button type="submit">Save Photo</button>
    </form>
</div>
```

`config/livewire.php` (partial)
```
'temporary_file_upload' => [
        'disk' => 's3',        // Example: 'local', 's3'              Default: 'default'
        'rules' => null,       // Example: ['file', 'mimes:png,jpg']  Default: ['required', 'file', 'max:12288'] (12MB)
        'directory' => null,   // Example: 'tmp'                      Default  'livewire-tmp'
        'middleware' => null,  // Example: 'throttle:5,1'             Default: 'throttle:60,1'
        'preview_mimes' => [   // Supported file types for temporary pre-signed file URLs.
            'png', 'gif', 'bmp', 'svg', 'wav', 'mp4',
            'mov', 'avi', 'wmv', 'mp3', 'm4a',
            'jpg', 'jpeg', 'mpga', 'webp', 'wma',
        ],
        'max_upload_time' => 5, // Max duration (in minutes) before an upload gets invalidated.
    ],

```

`config/filesystems.php` (partial)
```
's3' => [
            'driver' => 's3',
            'key' => 'key',
            'secret' => 'secret',
            'region' => 'us-east-1',
            'bucket' => 'server',
            'url' => 'https://server.test-cors.org/',
            'endpoint' => 'https://server.test-cors.org/',
            'use_path_style_endpoint' => true,
            'throw' => false,
        ],
```

Current Release:

https://user-images.githubusercontent.com/845525/235702101-2172f638-1dbe-4457-b356-3faa5f30a4b6.mp4


This MR:


https://user-images.githubusercontent.com/845525/235702158-113f0eb1-0d89-4d6d-a512-668eb3bd4910.mp4

**Pull request closed without merging**
