### PR TITLE
Image filename with FilePond upload

### PR DESCRIPTION
**Pull request by robertorinaldi-dev**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
https://github.com/livewire/livewire/discussions/4464 https://github.com/livewire/livewire/issues/2918

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No, it's a one row fix

4️⃣ Does it include tests? (Required, where possible)
No, I honestly don't know how to test it, besides having tested it in a project of course

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
With filepond (https://pqina.nl/filepond/) images are uploaded as blob, so they get 'blob' as filename (https://developer.mozilla.org/en-US/docs/Web/API/FormData/append) and there is no way to know the original filename after uploading (as far as I know).
With this little fix we can keep the original name and get it with `getClientOriginalName()`.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@robertorinaldi-dev just saw this PR, so dis-regard my comment on your discussion 🙂 thanks for the PR! I've triggered tests to run.

**Comment by ralphjsmit** [comment]
Any idea when this could get considered/merged? Would be great for all the Filament users😅

**Comment by joshhanley** [comment]
@ralphjsmit I'll get this looked at for the next release 🙂

**Comment by ryangjchandler** [comment]
@joshhanley @calebporzio Any update on this?

**Comment by calebporzio** [comment]
Looks good to me. Ideally this would have a test, but I get it here. Thanks for the contribution @robertorinaldi-dev!

**Comment by ryangjchandler** [comment]
@calebporzio Legendary.

**Comment by calebporzio** [comment]
Tagged this in 2.10.3 so that it's available for you 👍

**Pull request merged**
