### PR TITLE
[Fix] FileUploadHandler didn't handle long filenames

### LINKED ISSUE #2834: FileUploadHandler didn't handle long original filenames.
### Description
- Related discussion #2238 #2813 
> When uploads with a long filename, it throws an exception:
> `fopen(<path with long filename>): failed to open stream: File name too long`

- In the process of encoding the original filename to base64.
- Increases filename length compared to the original filename.
https://github.com/livewire/livewire/blob/b0f4026509604f5239813a605ba7172f4bb5fa0e/src/TemporaryUploadedFile.php#L126-L133
- FileUploadHandler isn't catching that increases filename could be over the maximum length of filename.
https://github.com/livewire/livewire/blob/b0f4026509604f5239813a605ba7172f4bb5fa0e/src/Controllers/FileUploadHandler.php#L32-L42
### Exact steps to reproduce
- Select a file with a long filename in the file input form.

### Stripped-down, copy-pastable code snippets

UploadTest.php
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithFileUploads;

class UploadTest extends Component
{
    use WithFileUploads;

    protected $rules = [
        'file' => 'required',
    ];

    public $file;

    public function render()
    {
        return view('livewire.upload-test');
    }
}
```

upload-test.blade.php
```html
<div>
    <input wire:model="file" type="file">
</div>
```

**Context**
- Livewire version: 2.4.3
- Laravel version: 8.39.0
- Alpine version: 2.8.2
- Browser: Chrome

### PR DESCRIPTION
**Pull request by ZerglingGo**
Fixes #2834 

* Add checking the filename lengths
* Add test
* Add skip renaming in test syncUploadedFiles() when a blank file

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks for this! Just so I'm clear, where is the 256 restriction coming from? The browser? Server?

I'm wondering because it's it something that can be configured to allow for more, making this a bad idea to hard code?

**Comment by joshhanley** [comment]
At a quick look the 255 is the character limit for most common disk formats (APFS, exFAT, NTFS, etc) https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

I think the issue isn't necessarily in the filename length of the original file, but also how deep the tmp livewire folder is stored.

For example on #2238 the error has the full path and file name (see error below).

> "fopen(/var/www/html/multiup/storage/app/livewire-tmp/LYCKtev7fgBxuTDjG2EJcNsSbs6bKD-metaMjAyMC0xMi0wOS3guKPguLLguKLguIfguLLguJnguKrguKPguLjguJvguJzguKXguIHguLLguKPguJTguLPguYDguJnguLTguJnguIHguLLguKPguIjguLHguJTguIvguLfguYnguK3guIjguLHguJTguIjguYnguLLguIfguYPguJnguKPguK3guJrguYDguJTguLfguK3guJkg4Lie4Lik4Lio4LiI4Li04LiB4Liy4Lii4LiZ4LieLuC4qC4yNTYzLnBkZg==-.pdf): failed to open stream: File name too long"

I think actually base_64 encoding the original file name in the hash is what is actually causing the issues, as the results gets longer depending on the length of the file name. I wonder if we could use something else to encode the filename which is of fixed length, no matter the length of the string passed in?

**Comment by ZerglingGo** [comment]
I referenced the same page linked by @joshhanley.

I can't think of anything about fixed length decryptable string.
Another way that comes to me is to store the file with fixed length hash name, and create a metadata file for each file, and store the original filenames.
```
// upload file name
longfilenames.png

// In livewire tmp folder
520f639156198cf82b96767c695081dde6ccb6c7ebcf7bb73e2d750897da61e7 // longfilenames.png
520f639156198cf82b96767c695081dde6ccb6c7ebcf7bb73e2d750897da61e7.meta // contains original filename
```

**Comment by calebporzio** [comment]
Yeah, I'm pretty rusty on the internals of that system, but it makes sense to explore not adding the original name to the filename.

**Comment by calebporzio** [comment]
Sorry, can someone refresh me on what's the best way to move forward here?

**Comment by ZerglingGo** [comment]
Sorry, I was busy working for business.
There has two solutions getting original filename:
1. Create metadata file
2. Store in property (I couldn't proof it because I didn't know logic of how can that part worked.)

I'm curious about other people's opinions to 2nd solution.

**Comment by phattarachai** [comment]
Hi, I am still facing this issue? Is there a way to workaround this? 

Thanks.

**Comment by Mattia-Marchiorato** [comment]
Hello, any update for this issue? What about the pull request?

**Comment by calebporzio** [comment]
Closing due to lack of response - please re-submit this PR if/when you have an update. Thanks for contributing!

> For context, as a maintainer, leaving PR's open for an indefinite amount of time adds overhead to my work. Therefore, if I can't perform an immediate action on a PR, I may close it rather than wait for a response (that sometimes never comes). I Hope you can empathize with that! Thanks again!

**Comment by DanielGSoftware** [comment]
We're running into the same issue. I'm not sure if I'm the right person to try to fix this, but I'll have a quick look.

**Comment by DanielGSoftware** [comment]
Nevermind, I found this open [PR](https://github.com/livewire/livewire/pull/8690) to solve this issue hopefully!

**Pull request closed without merging**
