### PR TITLE
Fix file is deleted but property still references deleted file if filename mismatches.

### PR DESCRIPTION
**Pull request by hasyirin**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
No, I did not create any discussion about it.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes: fix-remove-upload

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
I need to explore how to code tests first...

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

If we were to trigger the upload:remove event to a property with a different filename, the file is deleted however it is still being referenced. This will throw exceptions if we were to use the value.

I'm still not sure whether it's better to match both property name and filename as my PR or ignore filename entirely if it's a single file.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@AhrimFakhriy thanks for the PR! Can you please add tests? Thanks!

**Comment by AhrimFakhriy** [comment]
@joshhanley Hi, I added a test. Still not sure whether to ignore the filename or ensure filename matches when removing a single file property.

**Comment by joshhanley** [comment]
@AhrimFakhriy tests were failing due to an unrelated error. I have merged master in and will run the tests again.

**Comment by AhrimFakhriy** [comment]
That’s odd. Another failed test that I dont think is related?

**Comment by joshhanley** [comment]
@AhrimFakhriy ah yeah we have some flaky tests which fail in CI sometimes. If you have a look you can see a few test suites have actually passed, so that's generally what we look for, so all should be good!

**Comment by calebporzio** [comment]
Looks great and makes sense. Thanks!

**Pull request merged**
