### PR TITLE
Fix loading not working while actually uploading a file

### PR DESCRIPTION
**Pull request by joshhanley**
This PR fixes an issue where, if you have an element with `wire:loading` that is targeting a file upload property, that element is not being displayed while the actual file upload is happening.

This is due to the loading state being wiped out by `_startUpload` request finishing, before the actual file upload starts.

I have added a `livewire-upload-transfer` event that gets triggered when the actual file upload request is fired (open to better names!).

But due to `morph` being wrapped in a double `queueMicrotask` I had to also do that same to this trigger call, to ensure that the event is fired after morph (from the `_startUpload` request) finishes, otherwise loading state just gets wiped again.

https://github.com/livewire/livewire/blob/001dabcc5924647e8dc40b6f0de4de5783b06ee5/js/features/supportMorphDom.js#L8-L16

As I'm typing this, I', wondering if it might be better listen to the `morph.updated` event instead of wrapping in the double `queueMicrotask`. We'd have to make sure that the listener is cleaned up after the `livewire-upload-transfer` event is fired once.

See screencapture below of example of the issue.

---

## Before

You can see `Loading` disappears once the first request has finished
Recording 2024-02-06 at 17 02 13

---

## After

You can see `Loading` remains all of the upload requests have finished
Recording 2024-02-06 at 17 03 17

### CODE REVIEW

**Comment by calebporzio** [comment]
Ah yep, definitely a valid problem. There's gotta be a simple solution though right? Like what is a small change we could make without introducing a new method dispatch and a double microtask call, that seems like digging a hole deeper you know?

**Comment by calebporzio** [comment]
# The problem

Given the following common case of uploading a file and showing a loading indicator:

```html
<input type="file" wire:model="photo">
<div wire:loading wire:target="photo">File is uploading...</div>
```

Currently, "File is loading..." will only show for a brief moment, then disappear even while the file is still uploading. (instead of being present for the entire duration of the uplaod)

## Why is this happening?

When a user uploads a file to the input field, Livewire internally sends TWO requests to the server.

Request #1: A simple component update to a method called "_startUpload". This method returns a signed URL to actually upload the file to.
Request #2: The actual file upload using the signed URL from the previous request.

`wire:loading` is only showing for the duration of request #1, completely ignoring request #2.

## What's causing this?

When Livewire sends request #1, the loading state is set, however, when the response is received, it's handled like any other Livewire response, re-rendering the component, and morphing the new HTML in the frontend.

When this morph happens, it wipes out the CSS added by `wire:loading`.

# Solutions

## Solution A

Fire an explicit event when request #2 fires (originally proposed in this PR). listen for that even inside `wire:loading` and reboot the loading states for that file input.

Pro: surgical: specifically solves the problem without impacting other behavior.
Con: adds an entirely new file upload event with a new concept name "transfer"
Con: uses a double queueMicrotask to be ordered with morph properly which feels complicated

## Solution B

Treat "_startUpload" as a `#[Renderless]` method so that there is no morph step to wipe out the loading state.

Pro: Simple, intuitive, improves the performance of the system as well as fixing the problem
Con: Potentially changes behavior in some way people depend on. I don't think this is a problem though because this is an internal method call

**Comment by joshhanley** [comment]
The main issue I see with solution B is that the _startUpload call isn’t an internal call. Instead it is a call made to a method on the component (included by the WithFileUploads trait).

What this means is that any queued property changes will also be sent with the request, so making it render less could cause other issues. I will do a test to double check that this is the current behaviour. 

But I’m all for a simpler solution. Maybe instead there could be a “shouldStillBeLoading” state somewhere instead that only gets turned off when the end upload event is fired. That concept could be useful in other places for loading too.

**Comment by calebporzio** [comment]
Ah yep, you're right, it could synchronize state and such, maybe triggering validation errors from property attributes and not showing the error?

Maybe we deploy this with a comment above it, and if people complain about that we explore something else. Feels like an edge-case-y problem I don't want to complicate the codebase because of you know? Agree?

**Comment by joshhanley** [comment]
@calebporzio so I did some experimenting and found that any deferred property updates that also have `#[Validate]` still work as expected as there are actually 3 requests that happen (`_startUpload`, `fileUpload`, `_finishUpload`) and the finish upload does a full render of the component which ensure that any validation messages that may have been triggered by other property updates are rendered and displayed correctly.

I have added and pushed up a test to ensure this.

So I would say we can merge this 😁

**Comment by calebporzio** [comment]
Wooohooo! Thanks for digging in on that!

**Comment by newlife0007** [comment]
<label
        x-cloak
        x-data="dropzone({
        _this: @this,
        })"
        @dragenter.prevent.document="onDragenter($event)"
        @dragleave.prevent="onDragleave($event)"
        @dragover.prevent="onDragover($event)"
        @drop.prevent="onDrop"
        for="dropzone-file"
        class="flex flex-col items-center justify-center w-full h-64 border-4 border-dashed border-white/30 border-blur-md rounded-lg bg-white/50 hover:bg-white/60 backdrop-blur-md cursor-pointer">
        <div class="flex flex-col items-center justify-center pt-5 pb-6">
            <svg class="w-10 h-10 mb-4 text-orange-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path d="M4 7a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v10a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V7z"/>
                <path d="M12 15v-6m0 0l-2 2m2-2l2 2"/>
            </svg>
            <p class="text-lg text-gray-600 font-semibold">tips</p>
        </div>
        <input wire:loading.delay.attr="disabled" wire:model="photo" id="dropzone-file" type="file" class="hidden" />
    </label>
    <div role="status" class="text-center">
        <svg wire:loading  aria-hidden="true" class="mt-10 inline w-12 h-12 text-gray-200 animate-spin dark:text-gray-600 fill-purple-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
            <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
        </svg>
        <span class="sr-only">Loading...</span>
    </div><script>
        Alpine.data('dropzone', ({_this}) => {
            return ({
                isDragging: false,
                isDropped: false,
                isLoading: false,

                onDrop(e) {
                    this.isDropped = true
                    this.isDragging = false

                    const file = e.dataTransfer.files[0]

                    const args = ['photo', file, () => {
                        // Upload completed
                        this.isLoading = false
                    }, (error) => {
                        // An error occurred while uploading
                        console.log('livewire-dropzone upload error', error);
                    }, () => {
                        // Uploading is in progress
                        this.isLoading = true
                    }];

                    // Upload file(s)
                    _this.upload(...args)
                }
            });
        })
    </script>

Recently, I discovered that if I use _this.upload(), the earliest issue will still be reproduced, where wire:loading is not triggered when uploading images.

**Pull request merged**
