### PR TITLE
Feature: Alpine.navigate.onNavigate() (aka: View Transitions Support)

### PR DESCRIPTION
**Pull request by iksaku**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Yes, discussed at #6329 

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
Nope

4️⃣ Does it include tests? (Required)
Yes!

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
The new [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) give developers a great foundation to create new experiences for our users, and while [support by major browsers](https://caniuse.com/view-transitions) is still a work in progress, we can now provide the tools needed for Alpine/Livewire developers to work with these new browser APIs easily.

This PR introduces the `onNavigate()` hook for the Alpine Navigate plugin, using the same API as [SvelteKit's `onNavigate()`](https://kit.svelte.dev/docs/modules#$app-navigation-onnavigate) lifecycle hook, which was [introduced specifically to enable View Transitions](https://svelte.dev/blog/view-transitions) when navigating between different pages. The Alpine version works the same way, and the integration would look something like this:

```js
document.addEventListener('alpine:init', () => {
    if (!document.startViewTransition) {
        // View Transitions API not supported by the current browser.
        return
    }

    Alpine.navigate.onNavigate((navigation) => {
        return new Promise((startTransition) => {
            document.startViewTransition(async () => {
                startTransition() // Signal the start of the View Transition
                await navigation.complete // Wait until Alpine finishes navigating, then signal the end of the View Transition
            })
        })
    })
})
```

This `onNavigate()` hook executes _as late as possible_, after the `alpine:navigating` event and before the `alpine:navigated` event, without interfering with them.

Here's a basic demo of the integration in action:

https://github.com/livewire/livewire/assets/4632429/8d34e1e5-0e66-4b13-812a-c740ba781f73

While integration could also be done in other ways, like [Astro's View Transitions](https://docs.astro.build/en/guides/view-transitions/) implementation (that uses minimal configuration), the SvelteKit way provides more flexibility for the developer to bend the integration to their needs.

> Another place where a similar API would be really useful is at the _pre-morph_ stage for both Alpine and Livewire lifecycles as the View Transitions API is intended to be used for page updates in general, not only page navigation. However, this is out of scope for this PR.

I hope you find this implementation to be a good fit for the ecosystem.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Thank you for the PR @iksaku - we certainly have plans to support view transitions in the future, but I want to get v3 more stable before introducing this. Thank you again for the well-formed and thought-out PR. Maybe it's possible to make a plugin if your own for this somehow?

**Comment by kirkbushell** [comment]
Will this ever be revisited?

**Comment by P4KM4N** [comment]
Hey @calebporzio You just reach PR zero, time to add this feature :D

**Comment by elias-michaias** [comment]
I'm really excited to see this come to Livewire and really complete that Live feel.

**Comment by RealMrHex** [comment]
waiting for it...

**Comment by bugsarekillingme** [comment]
+1

**Comment by kent13n** [comment]
+1

**Comment by sparklem-agency** [comment]
tired of waiting :(

**Comment by DanielSpravtsev** [comment]
@joshhanley @calebporzio Time has come? :)

**Comment by Bark-fa** [comment]
@iksaku can you make a plugin for your code seeing as @calebporzio can't merge it? It would have been nice for this to be merged even if just as a beta feature.

**Comment by sparklem-agency** [comment]
when will we get this

**Comment by NimaKhadivar** [comment]
we need in v4

**Comment by ventrec** [comment]
Great work with the PR @iksaku.

Would really like to see this in livewire! @calebporzio @joshhanley

**Comment by iksaku** [comment]
Looks like Livewire v4 is introducing a new API for View Transitions!

[YouTube Link](https://youtu.be/0AvfYxJ5Ss0?si=itemEeU1AQ-nyve_)

Not sure if this new API will have a JS API exposed, or if it works with `wire:navigate`, but it's a first step in the right direction.

> [Shared in the original discussion](https://github.com/livewire/livewire/discussions/6329#discussioncomment-15447985) as well.

**Pull request closed without merging**
