### PR TITLE
Remove onNodeAdded event call when matched keyed node moved to new parent

### PR DESCRIPTION
**Pull request by ncharalampidis**
This bug fix has been solved in the original morphdom project. You can see the original pull request [here](https://github.com/patrick-steele-idem/morphdom/pull/194).

It fixes multiple event registration in an keyed element mentioned in this issue #2578 

The pull request includes the test to reproduce the issue.

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks a bunch for catching this and referencing the original fix!

Only thought here: why did you remove the `@livewireModification` - that's the only part of this that makes me nervous.

**Comment by ncharalampidis** [comment]
The @livewireModification had the following comment:
`Otherwise, "curChild" (matched element by key) will be unattached when it is passed to "handleNodeAdded`

With this fix the matched element is never passed to handleNodeAdded event, which is exactly the fix. I think the @livewireModification was there to somehow skip the bug that morphdom had.

Also all the tests pass, so I guess its ok but please take a closer look yourself because I am new to the project and no so familiar.

**Comment by markhuot** [comment]
Can confirm I am experiencing a similar bug and this fork resolves the issue. In my particular case I have nested components with an outer `PostList` and an inner `Post` component, for example. When I save changes to the DB inside the `Post` component it triggers a render of the `Post` (to end editing) and then an event triggers a render of the `PostList` too (to update ordering/grouping). The first render completes without issue but after the `PostList` catches the event and tries to re-render itself I end up with a "TypeError: initialData is null" JS error.

You can see an example here, https://laravelplayground.com/#/snippets/4b1273ab-3d73-4d6f-b9ab-5e90eabd300b. To trigger the bug edit "lindsey" and change the family to "stooges" then edit "lindsey" again and change the family back to "bluth."

**Comment by calebporzio** [comment]
Awesome, thanks so much!

**Pull request merged**
