### PR TITLE
[V3] Support Defer Loading

### PR DESCRIPTION
**Pull request by nicolagianelli**
1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Refers to #6153 

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes, defer-loading

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
Livewire with the lazy param can load components when they are in the viewport but for us and other people can be useful to start loading a component even when outside of the viewport, for example in a scrollable page, so when the user scrolls down they can find the components already loaded.
I named this param "defer" following the HTML defer attribute used for scripts.

### CODE REVIEW

**Comment by DanielSpravtsev** [comment]
I agree that Livewire need defer loading besides lazy loading, but now it's unclear what each option making because of similar naming. Maybe add something referencing to viewport or intersect (like in Alpine)? 

What do you think @calebporzio @joshhanley?

**Comment by joshhanley** [comment]
@nicolagianelli I think it would be best to wait to see Caleb's thoughts on it before making changes, but my opinion is that this should be the default for `lazy` and for intersect using `lazy.intersect` or something like that. Then it is just one feature class with a toggle instead of two classes (defer and lazy) that are basically the same.

**Comment by nicolagianelli** [comment]
> @nicolagianelli I think it would be best to wait to see Caleb's thoughts on it before making changes, but my opinion is that this should be the default for `lazy` and for intersect using `lazy.intersect` or something like that. Then it is just one feature class with a toggle instead of two classes (defer and lazy) that are basically the same.



> 

Yes.. using only a lazy param is more simple and better for the structure so for me it's good.
I would use lazy.viewport or lazy.intersect and lazy.load or lazy.init for the names, and the lazy without any modifier would be the viewport one like now because other js frameworks like nuxt or with images the lazy param is usually used to load the element when it is in the viewport.
Anyway I don't mind too much and I can make these changes to use these names and only 1 class when Caleb decides what naming convention he prefers 😁

**Comment by calebporzio** [comment]
Ok, thank you for this PR. I agree that it should be a feature.

Here's my ideal syntax to opt-into non-viewport-based loading:

```html
<livewire:counter lazy="on-load" />
```

Here are my notes for what to do to this PR before I merge it:

* Instead of a seperate "SupportDeferredLoading" folder, just add this feature and it's test to the "SupportLazyLoading" feature folder.
* Also we probably only need a single test case for this syntax
* Update the docs portion

If these things are done, I'd be happy to merge this. Thanks @nicolagianelli!

**Comment by nicolagianelli** [comment]
@calebporzio 
I did the requested changes:
- changed defer to lazy="on-load"
- only a SupportLazyLoading folder
- 2 new tests (1 to try the lazy="on-load" and 1 to try the lazy without "on-load" outside the viewport)
- updated the docs

**Comment by edalzell** [comment]
Looks like there are conflicts @nicolagianelli, can you please resolve so that it's easier for Caleb to merge?

**Comment by calebporzio** [comment]
Thanks @nicolagianelli !!

**Pull request merged**
