### PR TITLE
Implements 2 new helper methods in the LivewireManager to set the urls for upload-file and preview-file routes.

### PR DESCRIPTION
**Pull request by felahdab**
1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

Yes: I started discussion #6771. However, I received no answer but since I am confident that there are use cases for these 2 additional helpers, I am submitting this simple PR.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No. Only one change.

4️⃣ Does it include tests? (Required)

No: but the other helpers (setUpdateRoute and setScriptRoute) do not have their own tests neither.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

The 2 new helpers allow the developer to do:

```php
Livewire::setUploadFileRoute(function ($handle) {
    return Route::post('/livewire/a/random/route/to/upload-file', $handle)
        ->middleware('web');
});

Livewire::setPreviewFileRoute(function ($handle) {
    // Here, the provided url should contain a {filename} parameter for model binding to work.
    return Route::get('/livewire/z/random/route/to/preview-file/{filename}', $handle)
        ->middleware('web');
});
```

This is a complement to the setUpdateRoute and setScriptRoute methods which already allow the developper to adjust the routing of livewire requests. I reproduced the style used in seUpdateRoute and setScriptRoute which makes the new helpers consistent and allow the developer to fully customize the route definition, adding whatever middleware he wants in particular.

These new methods register the new route into the Router and name them as livewire.upload-file and livewire.preview-file. The URL generation used in the SupportFileUpload and SupportFilePreview features actually rely on the fact that the generated URL depends on the last declared route (when multiple routes have the same name). However, Laravel is missing a feature to remove a Route from the Router (which would be a safe addition to these 2 helpers).

Despite that, I hope you will find this PR suitable for merging.

### CODE REVIEW

**Comment by dweerd** [comment]
Hi, I would expect that you now also need to change `Features\SupportFileUploads\SupportFileUploads.php`, where these routes are (also) registered.

Also, `Features\SupportFileUploads\FileUploadController.php` has a method `getMiddleware` which maybe is also no longer necessary, as you can add middleware using this new way of defining the route?

**Comment by felahdab** [comment]
> Hi, I would expect that you now also need to change `Features\SupportFileUploads\SupportFileUploads.php`, where these routes are (also) registered.
> 
> Also, `Features\SupportFileUploads\FileUploadController.php` has a method `getMiddleware` which maybe is also no longer necessary, as you can add middleware using this new way of defining the route?

Hi.

You are probably right.
However, I will leave to people wiser than me the decision to remove something that is already in production, since it constitutes an API break.
My PR simply adds some helper methods that are useful and were missing so far.

Regards.

**Comment by joshhanley** [comment]
@felahdab thanks for the PR! As noted by @dweerd, for the helper methods in this PR to work correctly, the routes will need to be updated and possibly other things. As such we're going to close this for now. Feel free to open a new PR if you manage to change all the required parts. Thanks for being willing to contribute!

**Comment by jimhlad** [comment]
Hi all. Just curious if there's any update on this?

Just bumped into this limitation while developing a multi-tenant app that uses different database connections per tenant (https://tenancyforlaravel.com/ package).

We are able to customize the middleware that runs for the `livewire/update` endpoint using the `Livewire::setUpdateRoute` method. For consistency it would also be awesome to be able to extend the file routes.

**Comment by stevebrainng** [comment]
> @felahdab thanks for the PR! As noted by @dweerd, for the helper methods in this PR to work correctly, the routes will need to be updated and possibly other things. As such we're going to close this for now. Feel free to open a new PR if you manage to change all the required parts. Thanks for being willing to contribute!

He was actually trying to solve a real problem in regards to file upload especially when dealing with Multi-Tenancy by having the convenience of setting up a middleware for the file upload routes. 

Is there a workaround for the main time? While I work on the PR?

**Comment by emkcloud** [comment]
> > @felahdab thanks for the PR! As noted by @dweerd, for the helper methods in this PR to work correctly, the routes will need to be updated and possibly other things. As such we're going to close this for now. Feel free to open a new PR if you manage to change all the required parts. Thanks for being willing to contribute!
> 
> He was actually trying to solve a real problem in regards to file upload especially when dealing with Multi-Tenancy by having the convenience of setting up a middleware for the file upload routes.
> 
> Is there a workaround for the main time? While I work on the PR?

https://github.com/livewire/livewire/pull/8752#issuecomment-2542826198

**Comment by mpskovvang** [comment]
I ran into this issue as well while looking for a way to customize or work around it.

For now, I’m using the following approach to move the routes out of the default web middleware group (based on what shows up in `route:list` command). I’m not entirely sure how this affects overall behavior, since I'm not using this feature in my app.

```php
\Livewire\Features\SupportFileUploads\FilePreviewController::$middleware = ['admin'];

\Livewire\Features\SupportFileUploads\FileUploadController::$defaultMiddleware = ['admin'];
```

Placed in `AppServiceProvider::boot()`.

**Pull request closed without merging**
