### PR TITLE
IE11 compatibility - remove short arrow function in script tag

### PR DESCRIPTION
**Pull request by theChaosCoder**
Fixes https://github.com/livewire/livewire/discussions/3160

### CODE REVIEW

**Review by nuernbergerA — APPROVED** [review]

**Review by joshhanley — APPROVED** [review]

**Comment by calebporzio** [comment]
Thanks!

**Comment by isarphilipp** [comment]
@theChaosCoder thanks for the contribution - we just ran into the same issue in production and i was about to create a PR for it ;)
@calebporzio would you mind sharing when you plan to tag the next release for livewire? Especially this PR solves a pain point in production for us (and maybe others like @theChaosCoder) and it would be super amazing to use a tagged release instead of a local fork for it ;) No pressure, just a bit of planning would be great! Thanks!

**Comment by calebporzio** [comment]
Just got back from a trip. Will release today!

**Comment by calebporzio** [comment]
Tagged: https://github.com/livewire/livewire/releases/tag/v2.5.2

**Pull request merged**
