### PR TITLE
Fix renderless not working in event handler

### PR DESCRIPTION
**Pull request by nicolagianelli**
1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
It's a bug fix for the renderless feature not working when event handler is called
2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes
3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No
4️⃣ Does it include tests? (Required)
Yes
5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

This includes my bug fix for Renderless attribute not working for event handler.

### CODE REVIEW

**Comment by nicolagianelli** [comment]
@joshhanley This pull includes also a Failing Test for $dispatch being called twice without the fix, so the labels should be bug fix for the renderless part and failing test also for the $dispatch one.

**Comment by joshhanley** [comment]
@nicolagianelli Ah ok, please seperate into two seperate PRs so we can merge the bug fix and then investigate the failing test. Thanks!

**Comment by nicolagianelli** [comment]
@joshhanley Done, now the unit test for the $dispatch being called twice is separate in #6564

**Comment by joshhanley** [comment]
@nicolagianelli thanks! Much appreciated 🙂

**Comment by calebporzio** [comment]
Thanks @nicolagianelli !!

**Pull request merged**
