### PR TITLE
Revert back wire:loading.remove on request error.

### PR DESCRIPTION
**Pull request by lucasromanojf**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?

Yes, see #3728

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)

Yes

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

Elements with wire:loading.remove were correctly hidden on request start, but it the request throws an exception, the element wasn't being shown again. It was happening because, somehow, when the element had wire:loading.remove, it was being processed twice by the LoadingStates.js logic. This PR fixes this bug by just removing duplicates from the elements array.

5️⃣ Thanks for contributing! 🙌

🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks for the fix! I test would be ideal here so that if we re implement wire:loading with another core (which we very well may for the next Livewire version) we don't introduce a regression.

Mind adding a test for this? Thanks!

**Comment by lucasromanojf** [comment]
Hey @calebporzio, sure, gonna try to make a test for this today

**Comment by lucasromanojf** [comment]
hey @calebporzio, just updated the PR with the tests.

**Comment by calebporzio** [comment]
Thanks @lucasromanojf!

**Pull request merged**
