### PR TITLE
Use session errors as default error bag

### PR DESCRIPTION
**Pull request by yungifez**
possibly fixes

#6586
#6546

Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Yes 

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No 

4️⃣ Does it include tests? (Required)
No tests 

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
see #6546

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@yungifez thanks for the PR! Can you please give a small summary of what this fixes and also some test/tests? Thanks!

**Comment by yungifez** [comment]
Normal laravel errors do not work in livewiee anymore

This fixes that

 I gave a simple scenario that can be found in issue #6546

I'm not sure what tests I can give here because it's essentially using laravels errors instead of a new message bag if the livewire error bag is not found

**Comment by joshhanley** [comment]
@yungifez please provide the scenario here so Caleb doesn't have to go off digging in issues 🙂

If you have a scenario in code in your app, then use similar code to create the test .

**Comment by yungifez** [comment]
Okay here is the issue

- Create a form request and add some validation rules

-Create a livewire component and place the livewire component into a blade file ( maybe a layout file )

-Add the following to check for errors in both the livewire file and the blade file

```html
    <div class="w-full" x-data="{open: true}" x-show="open" x-transition wire:ignore>
   @if ($errors->$errorBag->any())
       <div class=" bg-red-100 rounded-md dark:bg-red-600 dark:text-white text-red-900 border-red-300 border w-full">
           <div class="py-2 px-4 text-black dark:text-white flex justify-end">
               <button type="button"  @click="open = false">
                   <i class="fa fa-x" aria-hidden="true"></i>
               </button>
           </div>
           <ul class="pb-6 px-6">
               <p class="font-bold text-lg"> Whoops! Something went wrong.</p>
               @foreach ($errors->all() as $error)
                   <div class="pl-6">
                       <li class=" list-disc">{{ $error }}</li> 
                   </div>
               @endforeach
           </ul>
       </div>
   @endif
``` 
This is used in displaying all errors 

- Create a form, submit the form ( without using livewire ) and make sure validation fails

It'll only display the first set of errors in the blade but wouldn't display the errors again in the livewire file


This PR fixes that, to make sure it works the errors would be displayed twice from both the blade and the livewire file

**Comment by joshhanley** [comment]
@yungifez thanks for the PR! We're going to close this for now as we don't think using the session is the right answer for this. A better solution would be to try and pass Laravel's error bag down into the Livewire component. Thanks for being willing to contribute!

**Comment by yungifez** [comment]
Good idea, haha I didn't know how to do it the livewire way

**Comment by yungifez** [comment]
@joshhanley  do you think this issue would get fixed or Ill have to manually set my error bag in every component

**Comment by wojciechczerniak** [comment]
@joshhanley Do you have link to the followup on this? Where can I track progress on fixing this bug?

**Comment by joshhanley** [comment]
@wojciechczerniak sorry about the delay, this has been fixed and merged in PR #7265. 🙂

**Comment by yungifez** [comment]
Yeah no problem thanks

**Comment by Rattone** [comment]
@joshhanley The problem with livewire forms in pages with classic forms that use the same error bag is still there...

**Comment by joshhanley** [comment]
@Rattone what version of Livewire are you using? Any chance you could create a small example repo which reproduces the issue with as little code as possible so we can investigate it?

**Comment by Rattone** [comment]
@joshhanley i'm using Laravel 10 with Livewire 3.
Simply create a livewire component with an "email" property (eg.: SubscribeNewsletter) and place it in login/register Laravel page. Validations errors of email field of Laravel default login page are shown also in the livewire component...
```
public function boot()
{
    $this->resetErrorBag();
}
```
This in my livewire component fix the problem but I think error bag name should be customizable.

**Comment by joshhanley** [comment]
@Rattone that's not really related to what this PR was about. But you will see on that issue I linked that I suggested that someone should submit a PR if they need that functionality 🙂

**Pull request closed without merging**
