### PR TITLE
Update the event registration according to laravel-echo

### PR DESCRIPTION
**Pull request by rainaldoc**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?
Needed for applications using Laravel Echo. I created an [issue](https://github.com/livewire/livewire/issues/1074) outlining the problem

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)
No tests

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.
It is a change to the event registration in the EchoManager.js for presence channels. See the image below on how to register events on a presence channel taken from the [laravel](https://laravel.com/docs/master/broadcasting#broadcasting-to-presence-channels) doc

image

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by jonfackrell** [comment]
I ran into this same issue today, but I don't think this is the appropriate fix. I think the other methods (here, joining, and leaving) need to be considered as well.

**Comment by larasocket** [comment]
Also running into this issue. Agreed with @jonfackrell, we should try and find a solution that can account for join, here, leaving, as well as custom events.

Could we add a simple switch to check if `event_name` is "here", "joining", "leaving" to call the methods as it currently does. If not, listen to the event like you suggest in your pull request?

I would love to see this fixed :) Let me know if I can help.

Does @calebporzio have any suggestions on the best fix?

**Comment by calebporzio** [comment]
As it seems this isn't the appropriate fix, I'm going to close this.

Feel free to re-submit a PR or issue with a more thorough description of the problem that's easier for me and others to understand, ideally with sample, copy-pastable code.

Thanks!

**Comment by redbastie** [comment]
Did you figure it out? I'm getting the same error from this code:

    protected $listeners = [
        'echo-presence:lobby,MatchMade' => 'matchMade',
    ];

**Pull request closed without merging**
