### PR TITLE
Add inline-flex to wire:loading

### PR DESCRIPTION
**Pull request by Francismori7**
When you are trying to inline-flex a loading element, just like for instance you want to center the loading message inside a table's `td`, you need it to be inline-flex.

### CODE REVIEW

**Comment by joshhanley** [comment]
@Francismori7 thanks for the PR! It seems like there is a failure in one of your tests

image

**Comment by Francismori7** [comment]
> @Francismori7 thanks for the PR! It seems like there is a failure in one of your tests
> 
> image

Can you run it again? The javascript wasn't built. I did now.

**Comment by joshhanley** [comment]
@Francismori7 ah yep, I'll start them now!

**Comment by calebporzio** [comment]
If the tests are passing the conflicts have been resolved, I'll merge this - sorry for the extra work on such a simple addition. Thanks @Francismori7! and thanks @joshhanley for helping out here

**Comment by Francismori7** [comment]
> If the tests are passing the conflicts have been resolved, I'll merge this - sorry for the extra work on such a simple addition. Thanks @Francismori7! and thanks @joshhanley for helping out here

The merge conflicts are due to the compiled files, how can I resolve them?

**Comment by joshhanley** [comment]
@Francismori7 best thing to do would just be to merge the latest commits on the master branch into your feature branch, and then rebuild assets again and do another commit of the assets.

**Comment by Francismori7** [comment]
All done!

**Comment by calebporzio** [comment]
Thanks @Francismori7! Can you add a bit about this support to the livewire/docs? Thanks!

**Comment by Francismori7** [comment]
> Thanks @Francismori7! Can you add a bit about this support to the livewire/docs? Thanks!

Sure thing.

**Pull request merged**
