### PR TITLE
[v3] `#[On]` allow multiple listener attributes

### PR DESCRIPTION
**Pull request by nuernbergerA**
@joshhanley as requested here https://github.com/livewire/livewire/pull/5876#issuecomment-1646986368

----
Fixes https://github.com/livewire/livewire/discussions/5912

### CODE REVIEW

**Comment by joshhanley** [comment]
@nuernbergerA Thanks! We will wait to see what Caleb thinks about which style to allow on the rule PR then apply the same here?

**Comment by nuernbergerA** [comment]
@joshhanley fine for me

**Comment by calebporzio** [comment]
Lovely, should probably be added to #[Rule] as well - I assumed you could do it and you can't but I see there's a flag for it now. Thanks @nuernbergerA

**Comment by nuernbergerA** [comment]
@calebporzio  there is #5876

**Comment by calebporzio** [comment]
*facepalm* lol

**Comment by AntonioPrimera** [comment]
I still run into this issue. I get the error "Attribute "Livewire\Attributes\On" must not be repeated".

Here's my simple Livewire component:

```php
use App\Models\Workflow;
use Illuminate\Support\Collection;
use Livewire\Attributes\On;
use Livewire\Component;

class StepList extends Component
{
    public Workflow $workflow;
    public Collection $steps;

    public function mount(Workflow $workflow)
    {
        $this->workflow = $workflow;
        $this->refreshSteps();
    }

    #[On('stepAdded'), On('stepDeleted'), On('stepUpdated')]
    public function refreshSteps()
    {
        $this->steps = $this->workflow->steps;
    }
}
```

And here's my SupportEvents/On.php file, which seems to be up to date:

```php
namespace Livewire\Features\SupportEvents;

use Attribute;
use Livewire\Features\SupportAttributes\Attribute as LivewireAttribute;

use function Livewire\store;

#[Attribute(Attribute::IS_REPEATABLE | Attribute::TARGET_METHOD)]
class On extends LivewireAttribute
{
    public function __construct(public $event) {}

    public function boot()
    {
        store($this->component)->push(
            'listenersFromPropertyAttributes',
            $this->getName(),
            $this->event,
        );
    }
}
```

The Error is raised in:
vendor / livewire / livewire / src / Features / SupportAttributes / AttributeCollection.php on line 25, on creating a new instance of the attribute.
 
Any ideas on why this still occurs? I see that there is a successful unit test for this feature.

**Comment by nuernbergerA** [comment]
ah is see the problem - PR incoming

**Comment by nuernbergerA** [comment]
@AntonioPrimera see https://github.com/livewire/livewire/pull/6127

**Pull request merged**
