### PR TITLE
[3.x] Clarify docs for validation utilities

### PR DESCRIPTION
**Pull request by PerryvanderMeer**
This PR contains a documentation-clarification for the issue described in https://github.com/livewire/livewire/discussions/8230.

### CODE REVIEW

**Review by lrljoe — CHANGES_REQUESTED** [review]
Suggest "component " is replaced with "class", or "component or form" as the same applies to both.

Also suggest that "should **not**" is replaced with "must **not**"

**Comment by calebporzio** [comment]
Thanks for this!

**Comment by robsontenorio** [comment]
@PerryvanderMeer It also worth it to add that you cannot have a `messages()` method and related one. Faced this issue recently.

**Comment by PerryvanderMeer** [comment]
@robsontenorio Got ya, #8348

**Pull request merged**
