### PR TITLE
Fix undefined index error

### PR DESCRIPTION
**Pull request by mjerwin**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?

Fix for issue #2401 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)
Added test which fails without this fix and passed after the fix.

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

Added null coalescing operator when finding the event method to handle this and added tests.

**Exact steps to reproduce**
Override getListeners() to add dynamic events
Call an action which would cause one of the dynamic events to be removed
Emit the event which has now been removed
See "Undefined index" error

This will cause the following error:
ErrorException: Undefined index: itemUpdated:2
/Users/mje/Sites/packages/livewire/src/ComponentConcerns/ReceivesEvents.php:72

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
I was assisting on an issue that had a similar error the other day.

I think there is two parts to this, this PR would be the first part, ensuring that the listener key exists before trying to access it.

The other would be making sure the the dynamic listener gets removed from the listener list on the front end (I haven't investigated yet to see how it handles this and whether or not it does get removed).

**Comment by calebporzio** [comment]
Thanks for submitting this. Like @joshhanley mentioned, I believe changes to listeners at runtime aren't currently observed by Livewire on the front-end. I think Livewire sets the listeners up on initialization in JS, and doesn't change them with new listeners from the backend.

Your tests aren't showing this because they are Unit tests and not Dusk tests that excercise the actual JS.

Going to close this for now, feel free to re-open if you address the above. Thanks!

**Comment by cby016** [comment]
We are currently getting these undefined array key errors on our production environment.

`Undefined array key "echo..." at .../vendor/livewire/livewire/src/ComponentConcerns/ReceivesEvents.php:73`

I thought this issue was closed and the changes merged in, but when I looked at the ReceivesEvents.php file, it seems [the changes](https://github.com/livewire/livewire/pull/2427/files) never made it into the code base.  @calebporzio @mjerwin Any idea why not?

**Comment by joshhanley** [comment]
@cby016 currently dynamic listeners aren't supported. This PR was closed as per Caleb's comment above, about it being an incomplete fix and no one has re-submitted with a complete fix. I'm sure a PR with the fix would be welcome!

**Pull request closed without merging**
