### PR TITLE
Test resilience - deployment invalidation & session expiration tests

### PR DESCRIPTION
**Pull request by silnarm**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Mentioned in #4590, unclear if actually wanted as other people apparently don't experience these errors.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Y.

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
N.

4️⃣ Does it include tests? (Required)
It fixes tests.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
small changes to four tests, replacing `pause()` calls with `waitForDialog()`. Makes tests more resilient and makes them pass every-time for me (where they were previously erroring out most of the time).

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@silnarm thanks for the PR! I've triggered the tests to run

**Comment by silnarm** [comment]
@joshhanley Failure is in unrelated test. I actually need to modify that test locally to get smooth passes, wasn't too sure about a PR for that one, it removes a lot of asserts, but keeps the important ones and it would make that one much less likely to fail.
https://github.com/silnarm/livewire/tree/fix-false-failures-in-delay-durations-test
Worth a PR?

**Comment by joshhanley** [comment]
@silnarm have triggered the tests to re-run. Yeah that flaky test is a pain, definitely open to fixes for it, I'll have a look at your other PR.

**Comment by calebporzio** [comment]
Thanks!!

**Pull request merged**
