### PR TITLE
[v3] Exclude files from packagist

### PR DESCRIPTION
**Pull request by nuernbergerA**
Simulate what will end up on packagist
```shell
git archive --worktree-attributes -o latest.zip HEAD
```

Currently its:
image

with this PR:
image

### CODE REVIEW

**Comment by babacarcissedia** [comment]
this is pretty cool

**Comment by joshhanley** [comment]
@nuernbergerA looks good to me. Will leave this for Caleb to have a look at.

**Comment by joshhanley** [comment]
I believe this should fix #5808 too

**Comment by nuernbergerA** [comment]
due too the new pattern that test life next to the code in `src` we need to double check if all required files are included

**Comment by joshhanley** [comment]
@nuernbergerA yep will do that now before I merge

**Comment by joshhanley** [comment]
Thanks!

**Pull request merged**
