### PR TITLE
Replace action param parsing ES code with equivalent babel polyfill

### LINKED ISSUE #1112: Internet Explorer 11 support
The Internet Explorer support is pretty good. But I' having a problem when I'm working with listeners.
I'm getting a Syntax error in the directive.js file.

I'm not a Javascript expert but I think the Arrow Syntax is not supported by the IE. Could there be another way to write that method that would also work for the ie?

image

**Context**
- Livewire version: [e.g. 1.2.0]
- Laravel version: [e.g. 6.2.0]
- Browser: [IE11]

### PR DESCRIPTION
**Pull request by mattharcourt**
This is a re-submission of #1124 to fixes #1112 

The ES code was replaced with what Babel produces for a polyfill. I also verified it works in latest versions of Chrome and Firefox, but I don't have IE so need some help to verify there.

### CODE REVIEW

**Comment by dubcanada** [comment]
I tested it in IE 11 and it fixed the issue.

**Comment by mgussekloo** [comment]
This would be perfect! Any chance of a timely merge?

**Comment by jwohlfert23** [comment]
Tested this in IE11 and it does the trick! Any change to get this merged soon?

**Comment by calebporzio** [comment]
Thanks for the PR!

**Comment by jwohlfert23** [comment]
Any timeline for releasing v1.3.3?

**Pull request merged**
