### PR TITLE
Docs: note about nginx 404 `livewire.js`

### PR DESCRIPTION
**Pull request by robsontenorio**
This is the beginner's very first issue when using Nginx.

Feel free to tweak the text. This note was taken from  https://benjamincrozat.com/livewire-js-404-not-found

image

### CODE REVIEW

**Comment by calebporzio** [comment]
Good call - thanks for this PR! I reworked the wording a little, but the content is still there for people. Thanks!

**Comment by johnbacon** [comment]
Alternatively, we're curious if this PR is something being considered: https://github.com/livewire/livewire/pull/6891

As discussed in https://github.com/livewire/livewire/discussions/6575#discussioncomment-6853744, it's generally not considered best practice to serve static files in this way. I believe that PR's solution should supersede an Nginx workaround.

**Comment by clementmas** [comment]
That nginx config recently stopped working for me until I changed the filename to `location = /livewire/livewire.min.js`. So I guess the docs are wrong now.

It's clearly not a good practice to serve a JS file through PHP. There's probably a better solution but I haven't dug into the subject yet.

**Comment by PhiloNL** [comment]
> That nginx config recently stopped working for me until I changed the filename to `location = /livewire/livewire.min.js`. So I guess the docs are wrong now.
> 
> It's clearly not a good practice to serve a JS file through PHP. There's probably a better solution but I haven't dug into the subject yet.

Currently, Livewire changes the route depending on `APP_DEBUG` if the value is true the file is `/livewire/livewire.js` otherwise it's `/livewire/livewire.min.js`

**Pull request merged**
