### PR TITLE
Make it compatible with PHP 7.1

### PR DESCRIPTION
**Pull request by lalov**
Removed some trailing commas to make it work with PHP 7.1

### CODE REVIEW

**Comment by cbaconnier** [comment]
Shouldn't we add PHP 7.1 to Github actions test workflow ?

https://github.com/livewire/livewire/blob/master/.github/workflows/test.yml#L17

**Comment by lalov** [comment]
Should I add PHP 7.1 to Github actions test workflow before it can be pulled in?

**Comment by calebporzio** [comment]
Thanks!

**Comment by lancepioch** [comment]
@all-contributors please add @lalov for maintenance

**Pull request merged**
