### PR TITLE
Fix noscript tag in head when using navigate

### PR DESCRIPTION
**Pull request by schonhoff**
Hey!

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Yes, you can find the discussion here: https://github.com/livewire/livewire/discussions/6279

2️⃣ Did you create a branch for your fix/feature? (Main branch PR's will be closed)
Yes, the branch name is `failing-test-for-noscript-tag`

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No, the changes are only related to my feature.

4️⃣ Does it include tests? (Required)
Yes, it includes a failing test.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
After changing to Livewire v3 our company tried to use wire:navigate on some pages and quickly run into an issue. If you are using the `noscript` HTML-Tag in `head`, you cannot use `wire:navigate` nor can you use `$this->redirect(URL, navigate:true)` because it will trigger the `noscript`-tag.

Thanks for contributing! 🙌
I could not find a solution for the problem. Maybe someone can help out? :-)

### CODE REVIEW

**Comment by lrljoe** [comment]
I can agree that this behaviour occurs.

If I add:
```
<noscript> <meta http-equiv="refresh"  content="0;url=/dashboard"> </noscript>
```
Then it'll force to "/dashboard" regardless on wire:navigate.

**Comment by schonhoff** [comment]
Hey @lrljoe ,

we are currently redirecting to a page without javascript used, because some clients wants a single page to be completely functional without javascript. Showing an element won't resolve the client request.

However, it is not the redirect, which isn't working. Even if your are using css to show/hide elements with the noscript tag it won't work. The fix from Caleb should to it. If you want me to add another test just for the css I would provide it asap.

I don't know why the workflow for PHP:8.3 isn't working as expected.

**Review by joshhanley — APPROVED** [review]
@schonhoff thanks for the PR! The failing test suite was just because we occasionally have flaky tests. I've merged main and everything looks good. I tested this without Caleb's fix and your test fails as expected, and then when I applied the fix, the test passes. So this PR is good to merge @calebporzio

**Comment by schonhoff** [comment]
Hey @calebporzio,

I tried this out after upgrading and after using wire:navigate it works. But on the second page there is no noscript tag anymore. Here are two screenshots:

First Page:
image

On the second page (after using wire:navigate on a page component):
image

Maybe you need a second look at this?

**Comment by joshhanley** [comment]
@schonhoff I would say it's fine, mainly because if someone can see the noscript tag, then they have javascript disabled and therefore `wire:navigate` won't work anyway (as it depends on javascript). What do you think?

**Comment by schonhoff** [comment]
@joshhanley okay, that is a fair point! If they disable Javascript between the sides I cannot help them :D

**Pull request merged**
