### PR TITLE
[Fix] back button cache issues

### PR DESCRIPTION
**Pull request by calebporzio**
This is a WIP based on problems outlined here: https://github.com/livewire/livewire/issues/2603

### CODE REVIEW

**Comment by bastinald** [comment]
you rock dude

**Comment by joshhanley** [comment]
@calebporzio I have done testing of this today as a follow up from the other day.

First off, I have updated the test so it is a more realistic test of what is happening. I have pushed the changes to my own branch here if you want to pull the changes in https://github.com/joshhanley/livewire/commit/2d59b564aa2fa73b21de1bb6b3548731bf939e44

The reason we weren't seeing the changes reflected after moving the redirect call was because (as you said) no HTML is being returned in the response.

We have to allow render by removing `$this->shouldSkipRender = true;` from the `ComponentConcerns/PerformsRedirects.php` methods (which I haven't done, I just updated the test)
https://github.com/livewire/livewire/blob/2e07fe08a792a6bbad8804ae6aeca1aa7b10b9f0/src/ComponentConcerns/PerformsRedirects.php#L9-L25

I did that, and I can see foo change to bar in the test before the redirect kicks in (have left the 500ms delay for now and added a delay to the test to compensate).

But when the browser redirects back, it is still pulling the old HTML from the browser cache, even after morphdom has had time to update the page (and you can see the changes). It seems like modifying the HTML on the page won't update the browser cache. I did a quick search and I couldn't see a way to use javascript to tell the browser to update its cache.

Which I think brings me back to my original idea on https://github.com/livewire/livewire/issues/2334#issuecomment-759114918 which is that browser cache should probably be disabled for Livewire components. Well it should be disabled for components that are not idempotent at least, just like Laravel disables browser cache for POST/PATCH/PUT/DELETE routes.

The hard part is, how do you tell which components modify data and which don't. Do you just disable browser cache for all Livewire components? What about scenarios where the route is a Laravel controller and the Livewire component is just added into the view?

**Comment by calebporzio** [comment]
Yeah, these are great questions. Thanks for looking into this josh.

It's possible there's more digging to be done on why the browser isn't caching the latest html. it seems really of that or wouldn't.

As for disabling the cache, that would be ideal in a lot of ways, but would be a bold move. We'd want to make sure we've understood all the implications and only disabled it when necessary.

Thanks again for driving into this Josh

**Comment by bastinald** [comment]
https://stackoverflow.com/questions/1195440/ajax-back-button-and-dom-updates

**Comment by calebporzio** [comment]
Good reference @bastinald, can you please sum up what information is relevant from that post?

**Comment by rginnow** [comment]
@calebporzio In regards to the link @bastinald posted, it seems it has to do specifically with browser caches only invalidating if there is an "onunload" event -- otherwise the browser caches the previous DOM state and the state of the page is reloaded nearly instantly by the browser. According to the [accepted answer](https://stackoverflow.com/a/1195934), only some browsers do this caching, and each browser handles it differently. A hacky method, provided by the [second answer](https://stackoverflow.com/a/14428894), would be to set the Cache-Control header as `cache-control: no-store, no-cache, must-revalidate`

I have no way to test this at the moment, but is there any way that Livewire could possibly inject an "onunload" event that will allow the browser to invalidate the page and not cache the page so it forces a fresh call from the server?

**Comment by joshhanley** [comment]
Have marked this as a draft for now, but wanted to push up what I had so far.

How this will work is Livewire will have two new config options:
- `disable_back_button_cache` which will be true by default
- `should_skip_render_on_redirect` which will be false by default

And two new helper methods in components:
- `$this->enableBackButtonCache()`
- `$this->disableBackButtonCahce()`

The reason for needing the two different config options above is listed below.

## disable_back_button_cache

With the first config option, for Chrome to work currently (until it has a full implementation of BFCache) then browser cache needs to be disabled for any Livewire component, otherwise anyone using the back button in Chrome will get stale data. 

Disabling browser cache will be set to true by default for all Livewire components. 

This can be set to `false` in the config by setting `disable_back_button_cache` to `false`. 

It can also be set to `false` on the component level by calling `$this->enableBackButtonCache()`.

If disabled browser cache is set to `false` at a config level, then it can be set to `true` at the component level by calling `$this->disableBackButtonCache()`

## should_skip_render_on_redirect

The second config option `should_skip_render_on_redirect` is for `bfcache` in Firefox and Safari to work correctly. 

Currently when a redirect is fired, Livewire doesn't render the view before doing the redirect. But if that happens with a browser that has `bfcache` and the user goes back, they will get a stale view.

By making this a config option, rendering on redirect can be skipped if necessary, but by default the render will happen, ensuring the latest changes get written to the page before the redirect happens, which in turn means `bfcache` has the latest view.

Livewire already has a `$this->skipRender()` helper method, which can be called to override the config when `should_skip_render_on_redirect` is set to `false`, to set skip render to `true`.

I think there needs another helper method for the reverse of the above situation, where skip render is set to true by default in the config, but you want to allow render to happen for a specific component.

What should this be called? `$this->dontSkipRender()`?

Or should we change both and have `$this->enableSkipRender()` and `$this->disableSkipRender()`?

## Things left to do

- [ ] Change `ComponentConcerns\PerformsRedirects.php` to use config option `should_skip_render_on_redirect` and component override
- [ ] Consider adding the opposite of `$this->skipRender()`
- [ ] Clean up and update tests
- [ ] Merge latest changes from master and fix any conflicts (RenameMes moved to Features)

## Note

Something to note, I had to ensure the `DisableBrowserCache` middleware is disabled by default (even if the config is set to enabled), so that other routes that don't have a Livewire component in them aren't impacted by it. 

I then enable it in the constructor of `Component.php` if the config option is set to true, so it gets set if ever a Livewire component is constructed. Not sure if that is the best place for this or not.

Hope this helps!

**Comment by joshhanley** [comment]
Ok, this PR is basically good to go. Will need reviewing though.

One thing to note is, the `setTimeout` still has a time of `50ms`. Ideally this should be `0ms`, but I couldn't get the tests to pass. So not sure how to halt the redirect in the test until the test has run some assertions.

Main two that need it are in `tests/Browser/Redirects/Test.php` on lines 39 and 60.

Hope this helps!

**Comment by joshhanley** [comment]
Not sure what is going on with the tests. They were running fine earlier and the change I made hasn't impacted it as you can see some of them still passing.

**Comment by nuernbergerA** [comment]
@joshhanley have the same issue https://github.com/livewire/livewire/pull/3554

**Comment by calebporzio** [comment]
Latest decisions:
* 1 config item: `back_button_cache => false` (defaults to false)
* render before redirect ALL the time, UNLESS a person calls `$this->skipRender()`
* No per-component back button cache option (only config)

**Comment by bastinald** [comment]
any idea when this will be released? need it super bad

thanks for all your work

**Comment by joshhanley** [comment]
@bastinald this has now been merged, so will be in the next release 🙂

**Comment by bastinald** [comment]
> @bastinald this has now been merged, so will be in the next release 🙂

has this been released yet? was playing around with the latest version and notice components still aren't preserving their mutated state when you go back to the page.

just curious, thanks again for all of this.

**Comment by calebporzio** [comment]
This has been released, yes. 

Can you verify that when you hit the back button, you are getting a full page refresh? And that your browser isn't using it's back button cache to load the page

**Comment by bastinald** [comment]
nevermind, i just tried the most recent version and it seems to be working great.

i made a public repo where i tested it out: https://github.com/bastinald/bas-live

thanks a million times!

**Comment by calebporzio** [comment]
Awesome! Glad to hear it!

**Comment by joshhanley** [comment]
@bastinald ah thanks for testing! Great to hear it's working 🙂

**Comment by killgt** [comment]
We're having a serious issue with this middleware. Octane keeps the DisableBrowserCache middleware active, so we're having a no-cache header on the whole page, even if the request isnt a livewire one, and it's overwriting the our middleware cache headers. Any ideas? We've set the 
`
    'back_button_cache' => true,
`
to fix the problem for now

**Pull request merged**
