### PR TITLE
[V3] failing test: removing entangled watcher

### PR DESCRIPTION
**Pull request by danharrin**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

Filament issues

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No

4️⃣ Does it include tests? (Required)

Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

Entangled watchers are not being destroyed when they are removed from the DOM, and get run even after all the Alpine properties in the component object are returning null.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Update: Dan and I paired briefly to investigate this issue.

Our findings:

* The current test isn't comprehensive enough. It's kind of the expected behavior (that a watcher would run one last time before being removed from the DOM if the property changed just before)
* His local project is throwing an error because it's trying to access a property in the watcher that a destroy hook has unset (I think?)
* I couldn't recreate this. In my quick attempts, the watcher always ran before the destroy hook so no error was trown

@danharrin said he would look more into re-creating the issue for this test on his own - so this PR is waiting on that update

**Comment by joshhanley** [comment]
Hey @danharrin have you had a chance to look at updating this test?

**Comment by danharrin** [comment]
I haven't been successful yet. Could be a Filament thing, but it did work in Livewire 2 so it probably isnt. Need to keep trying I think

**Comment by joshhanley** [comment]
@danharrin ok, no worries 🙂

**Comment by calebporzio** [comment]
Closing this as it doesn't address the problem that it's trying to. maybe #6528 will hopefully fix this phantom problem.

**Pull request closed without merging**
