### PR TITLE
Eliminate need to resetErrorBag() or resetValidation() when using a custom validator

### PR DESCRIPTION
**Pull request by mattharcourt**
Here is the V2 version of 1.x PR #1398 - complete with test.

### CODE REVIEW

**Comment by nuernbergerA** [comment]
Hey @mattharcourt 

please make sure to merge the latest `master` to make tests pass.

**Comment by mattharcourt** [comment]
Hi @nuernbergerA - I merged with the latest master just prior to submitting the PR, and I just retried merging master but found "Already up to date." I've rerun the tests and was able run them successfully five times without failure. So, I'm stumped why the CI failed - is there a timing issue in the test?

**Comment by nuernbergerA** [comment]
Yea its https://github.com/livewire/livewire/blob/master/tests/Browser/Alpine/Test.php#L91 that has some timing issues.

I already tried to sleep and so on without success, I somehow thought @calebporzio dropped this line.

**Comment by calebporzio** [comment]
Thanks @mattharcourt, however, I've already brought the changes to `master` after I merged them in 1.x Thanks!

**Pull request closed without merging**
