### PR TITLE
Uploaded error message

### PR DESCRIPTION
**Pull request by ta-tikoma**
Do a search for the uploaded error message first in the component.

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
yes, no

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
no

4️⃣ Does it include tests? (Required)
no, error on file bigger than `post_max_size`

### CODE REVIEW

**Comment by joshhanley** [comment]
@ta-tikoma thanks for the PR! Can you please add a test for this? Thanks!

**Comment by ta-tikoma** [comment]
@joshhanley test added

**Comment by joshhanley** [comment]
@ta-tikoma thanks! I have triggered tests to run

**Comment by joshhanley** [comment]
@ta-tikoma seems like your test is failing. Can you investigate it? Also php 7.2 and 7.3 are failing due to the `array` type hint on the property, can you remove that too? Thanks!

**Comment by ta-tikoma** [comment]
@joshhanley thanks for review. I fixed

**Comment by joshhanley** [comment]
@ta-tikoma thanks! I have triggered the tests to re-run 🙂

**Comment by ta-tikoma** [comment]
@joshhanley sorry, I try to fix again:
image

**Comment by joshhanley** [comment]
While we're developing V3, we're trying to keep V2 stable and limit API changes/additions. In that spirit, PR's like this that may otherwise make sense to merge, we're unfortunately closing. Thank for your effort and input!

**Pull request closed without merging**
