### PR TITLE
[V3] Add --pest command to Artisan commands

### PR DESCRIPTION
**Pull request by skegel13**
This PR adds a `--pest` flag to the Artisan commands when creating a Livewire component to also create a Pest PHP test.

```shell
artisan make:livewire create-post --pest
```

It also handles copying and deleting the Pest files when the respective commands are run.

A new `livewire.pest.stub` was created for the Pest tests and it also gets published when publishing the stubs.

### CODE REVIEW

**Comment by joshhanley** [comment]
@skegel13 thanks for the PR!

I don't think the other commands need the `--pest` flag, do you?
To me, if another command like copy already has a `--test` flag, then it should copy the test regardless of if it is a PHPUnit or Pest test.

So my thoughts would be that this is only needed on the make command. If you agree, can you update the PR?

Thanks!

**Comment by skegel13** [comment]
@joshhanley I can make the update if you think that makes sense. I just figured if someone created a component with a pest test, they might use the other commands with the pest command too. Personally, I've never used to other commands so I'm fine with the change though.

**Comment by joshhanley** [comment]
@skegel13 yeah if you can, that'd be great! Keep it simple for now, and if there are issues, we can always add the pest flag to the other commands later 🙂

**Comment by skegel13** [comment]
Changes have been made, let me know if there's anything else.

**Comment by calebporzio** [comment]
Thank you @skegel13 !!

**Pull request merged**
