### PR TITLE
Minify asset code

### PR DESCRIPTION
**Pull request by tillkruss**
- switch to single quotes (js code)
- made styles/script more readable
- don’t print “Livewire Assets” comment when `app.debug` is disabled
- minify script when `app.debug` is disabled

### CODE REVIEW

**Comment by tillkruss** [comment]
We could extract the heredocs into separate methods to make it shorter and easier to read.

**Comment by calebporzio** [comment]
Thanks for the PR @tillkruss.

I refactored the Heredocs into their own methods.

Also, I added a "defer" attribute to the external Livewire script. I had to change the `DOMContentLoaded` listener, to listen for a new event I'm dispatching now: `livewire:available`. This should have been done before anyways.

Thanks again

**Comment by tillkruss** [comment]
@calebporzio: Beautiful 😄

I'd _maybe_ define the listener before including the script, just in case some browsers are weird with `defer`.

**Comment by calebporzio** [comment]
I "caniused" `defer`, and it is supported by most everything, even IEs.

But you're right, it makes sense and wouldn't hurt. will do, thanks.

**Comment by lancepioch** [comment]
@all-contributors please add @tillkruss for maintenance

**Pull request merged**
