### PR TITLE
[V3] Fix keyboard enter on `<a>` tags with wire:navigate

### PR DESCRIPTION
**Pull request by gehrisandro**
Adds the missing keyboard event handler to follow links with `wire:navigate` by hitting the "enter" key.

Fixes: https://github.com/livewire/livewire/discussions/6252 / https://github.com/livewire/livewire/discussions/6585

### CODE REVIEW

**Comment by joshhanley** [comment]
@gehrisandro thanks for the PR! Can you confirm, what happens if cmd+enter is hit? Default browser behaviour is to open the link as a new tab.

**Comment by gehrisandro** [comment]
@joshhanley Currently it does not open in a new tab. I will update the PR as asap.

**Comment by joshhanley** [comment]
@gehrisandro great, thanks! 🙂

**Comment by joshhanley** [comment]
@gehrisandro have a look at PRs #6519 and #6535, that fixed cmd + click, might give you an idea of how to handle cmd + enter.

**Comment by gehrisandro** [comment]
@joshhanley The PR is updated as discussed yesterday. ENTER plus (CMD / CTRL, SHIFT or ALT) are now not handled by navigate.
Instead it fallbacks to the default browser behaviour (open in new Tab, etc.)

And thanks for the links provided, they helped a lot. 👍 

P.S: The failing test seems not to be related to my changes.

**Comment by calebporzio** [comment]
Lovely, thanks!

**Pull request merged**
