### PR TITLE
Missing trait hooks

### PR DESCRIPTION
**Pull request by AlexandreBonaventure**
Follow up on this one: https://github.com/livewire/livewire/pull/8215

### CODE REVIEW

**Comment by calebporzio** [comment]
Thank you for finishing this up @AlexandreBonaventure !

**Comment by francoism90** [comment]
@AlexandreBonaventure Just an question about this commit, hope that's ok. :)

Is it also possible to add the exception inside the trait as well (e.g. `WithPost`), as can be seen in the examples later? I was thinking about catching model exceptions like 403/404, and than redirect to `/<-response-code>`.

**Comment by AlexandreBonaventure** [comment]
@francoism90, sure that should work!

**Comment by francoism90** [comment]
@AlexandreBonaventure that's awesome! 👍

**Pull request merged**
