### PR TITLE
Fix `$entangle` so it is no longer live by default

### PR DESCRIPTION
**Pull request by danharrin**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

filamentphp/filament#8614

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No

4️⃣ Does it include tests? (Required)

Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

We've had reports that all entangled components are live by default. This contradicts the documentation, which states they are not live by default.

I think this started when the `get()` check for this property was added inside the `$wire` proxy, which (I think) bypasses the `wireProperty` definition? The `wireProperty` contains the `false` default, so I moved that into `generateEntangleFunction()`.

When I recompiled, there were a ton of JS changes. Not sure what's wrong there, but I think it needs recompiling again.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@danharrin yeah the assets are currently being build from Alpine repo main branch again. I've just rebuilt them for you.

**Comment by danharrin** [comment]
@joshhanley do you think it's because they're expecting it to be live by default?

**Comment by joshhanley** [comment]
@danharrin just had a quick look, in the test it explicitly has `@entangle('items').live`. It turns out the first test is failing due to console errors:

image

**Comment by danharrin** [comment]
@joshhanley I've added back the wireProperty, can you recompile please?

**Comment by joshhanley** [comment]
@danharrin Yup, done

**Comment by danharrin** [comment]
Let's see if that fixes

**Comment by joshhanley** [comment]
@danharrin yep, looks good. Thanks for that!

**Comment by calebporzio** [comment]
This is perfect, thank you @danharrin !!

**Pull request merged**
