### PR TITLE
Add failing test for nested entangled items duplicating requests

### PR DESCRIPTION
**Pull request by archilex**
When there are `entangled` items in an array, removing one or more of them causes duplicate requests to be made. If there are entangled and non-entangled items in the array, then removing _any_ of the items will also cause duplicate requests to be made.

Expected behavior: only a single request should be made.

See https://github.com/filamentphp/filament/issues/8077 for an example of this happening in Filament.

Could this also be related to #6309?

### CODE REVIEW

**Comment by archilex** [comment]
Updated to remove unneeded nested component I forgot to remove when developing the test.

**Comment by satoved** [comment]
Encountered this issue when updating to V3 too.

**Comment by joshhanley** [comment]
@archilex thanks for the PR! Looks like after merging in the latest main branch changes (after I fixed the failing tests there), that this failing test is now passing 😁 I'll leave it up to Caleb as to whether he wants to merge this test in or not.

**Comment by joshhanley** [comment]
@archilex thanks! Caleb was happy to include the test 🙂

**Pull request merged**
