### PR TITLE
Change `#[On]` attribute to support being defined at the component level

### PR DESCRIPTION
**Pull request by gdebrauwer**
When I upgraded a Livewire project from v2 to v3, I wanted to remove all the `$listeners` and use the new php attribute syntax.

In my project, most of my listeners just trigger a refresh of a component when an event is fired from a (non-child) component (e.g. [wire-elements/pro](https://wire-elements.dev/pro) modal or slide-over). Those kind of listeners can currently not be converted to php attributes, because you can not add them to a method (or you would have to create a dummy empty method which seems a bit weird).

```php
// Before

class SomeComponent extends Component
{
    protected $listeners = [
        'foo' => '$refresh',
        'bar' => '$refresh',
    ];
}
```

This PR fixes that by allowing the `#[On('eventName')]` php attribute on a Livewire class. That feels a lot more like Livewire v3 and also reduces the amount of lines in your Livewire class 😄 

```php
// After

#[On(['foo', 'bar'])]
class SomeComponent extends Component
{
}
```

### CODE REVIEW

**Comment by devajmeireles** [comment]
Why not only `#[Refresh]`?

**Comment by gdebrauwer** [comment]
'refresh on' seems a bit clearer in my opinion

**Comment by levu42** [comment]
this looks awesome! When I migrated a bigger project from v2 to v3, I created those empty dummy methods, which indeed look weird.

**Comment by joshhanley** [comment]
@gdebrauwer makes sense to me that we should have a way to call `$refresh` from an attribute listener.

Could we just change how `#[On()]` is handled so if it's placed on the class definition it just refreshes the component?

Like

```php
#[On('foo')]
class MyComponent extends Component
{
}
```

**Comment by levu42** [comment]
@joshhanley that indeed looks like the cleanest solution, I like that one more than `#[RefreshOn]`

**Comment by gdebrauwer** [comment]
@joshhanley Good idea! I will change it
(btw, it was awesome meeting you at LaraconAU 😄)

**Comment by joshhanley** [comment]
@gdebrauwer great thanks! Was great to meet you too 😁

**Comment by calebporzio** [comment]
Looks good to me, thanks!

**Pull request merged**
