### PR TITLE
Fix for encoding string containing characters outside Latin1

### PR DESCRIPTION
**Pull request by ahmetbedir**
Replaced "btoa(string)" by "btoa(encodeURIComponent(string))" to fix issue where the string to be encoded contains characters outside of Latin1 range.

### CODE REVIEW

**Comment by intellow** [comment]
I'm having this problem as well. Hoping the PR is merged soon.

**Comment by calebporzio** [comment]
Thanks for this @ahmetbedir!

**Comment by calebporzio** [comment]
Tagged v0.3.2

**Comment by lancepioch** [comment]
@all-contributors please add @ahmetbedir for code

**Pull request merged**
