### PR TITLE
Add redirectIntended

### PR DESCRIPTION
**Pull request by binaryfire**
Adds a `redirectIntended` method to allow redirecting to the previous page.

See https://github.com/livewire/livewire/discussions/7273

### CODE REVIEW

**Comment by joshhanley** [comment]
@binaryfire sweet thanks! I’ve triggered the 8.1 tests to run again 🙂

**Comment by calebporzio** [comment]
Thanks for the contribution, however I'm not sure about it seeing as Laravel uses: `redirect()->intended('dashboard');` instead of `->redirectIntended()`.

You can add this method to `src/Features/SupportRedirects/Redirector.php` instead to achieve a similar API. Going to hold off on merging until it matches Laravel a bit better. Thanks!

**Comment by binaryfire** [comment]
Hi @calebporzio. I'm not that will solve this issue: https://github.com/livewire/livewire/discussions/7273 ? The goal with this PR was to be able to redirect to the intended url and also specify `navigate: true` / `navigate: false` .

It's not possible to do `$this->redirect(navigate: true)->intended('https://defaulturl.com')`, which is why I added a separate method.

**Comment by calebporzio** [comment]
I see, thanks!

**Pull request merged**
