### PR TITLE
Fixes 'Typed property must not be accessed before initialization'

### PR DESCRIPTION
**Pull request by iksaku**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?
- This is indeed something reported previously:
  - #600
  - #707 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
- Nope, straight-forward fix.

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)
- It is not possible (yet) to add tests, since typed properties are supported since PHP >=7.4, and this package only has official support for PHP ^7.1.3

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.
- Commit message is pretty detailed, but will copy-paste anyways...
<details>
<summary>Click to expand commit message</summary>

```
Typed properties are a feature of PHP 7.4, which allows
properties to reference specific types, helping both during
development and runtime.

This new implementation has the need to provide an "initialized" state for
all typed properties, which breaks Livewire's implementation when accesing
properties in early component construction.

The 'ReflectionProperty' class has a new 'isInitialized' method, which
helps us to determine if the value of the property is accessible,
but is only available for PHP >= 7.4.

In order to prevent Livewire's property implementation from breaking
when developers want to use typed properties, we check for the existance
of the 'isInitialized' method in the 'ReflectionProperty' class.
If the method doesn't exist, it must mean that the running PHP version
does not support typed properties, so we just access the property value directly,
expecting a default null value if not initialized, or an actual value if already initialized.

If the method exists, then we return a value depending on the property state.
If the property has not been initialized, we just return a null value (like earlier PHP
versions), otherwise, we access the property value and return it.
```

</details>

5️⃣ Thanks for contributing! 🙌
- Thank you for this awesome package!

### CODE REVIEW

**Comment by nuernbergerA** [comment]
He @iksaku nice PR!

>  Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)
> 
> * It is not possible (yet) to add tests, since typed properties are supported since PHP >=7.4, and this package only has official support for PHP ^7.1.3

We test against [PHP 7.1, 7.2, 7.3 and 7.4](https://github.com/livewire/livewire/blob/master/.github/workflows/test.yml#L22)

To run tests only for the specific version you can compare version, which you don't need in this case.

```php
/** @test */
public function public_properties_are_initialized_properly()
{
    if (version_compare(PHP_VERSION, '7.4', '<')) {
        $this->markTestSkipped('not supported...');
    }

   //....
}
```

If you need any help writing these tests, I would be happy to help you out.

**Comment by iksaku** [comment]
Hello @nuernbergerA!

I will look into adding the needed classes using version comparison for tests. Hope I can push them later today.

**Comment by iksaku** [comment]
@nuernbergerA Pushed some tests, which look for initialization states for both non-typed and typed properties, now the thing is that PHP Compiler will complain about the typing in earlier PHP Versions.

The only way to prevent this is to eval class strings into code when needed, but I don't think its good to force this use for the tests.

Any other way around?

**Comment by iksaku** [comment]
Bump on this...

\cc @calebporzio @nuernbergerA

**Comment by nuernbergerA** [comment]
Hey @iksaku sorry for my long absence, I still have a lot todo.
The only option comes to my mind is something with eval or anonymous classes.

My intention wasn't to block this PR for so long.

I think @calebporzio is also fine as it is now.

Thanks for your patience.

**Comment by iksaku** [comment]
Thanks for your response!

Actually, I tried using anonymous classes offline, but the parser still complains while trying to compile the test file on lower PHP versions... Maybe the only option left is eval... 

But _should_ we use that kind of hacky implementation?

**Comment by nuernbergerA** [comment]
For me, eval in a test for this special edge case would be fine.

**Review by nuernbergerA — APPROVED** [review]

**Comment by nuernbergerA** [comment]
@calebporzio bump

**Comment by calebporzio** [comment]
Thanks for this @iksaku  and @nuernbergerA  for tending to this PR 👏🏻

**Pull request merged**
