### PR TITLE
[Feature] multiple paginators support

### PR DESCRIPTION
**Pull request by joshhanley**
This PR adds support for multiple paginators in one component.

Need I say more? 😁

Hope this helps!

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks @joshhanley !

**Comment by ariaieboy** [comment]
@joshhanley 
great PR but i winder that is that working with simple pagination too or not bvecause i can not see any changes in the simple paginations views

**Comment by joshhanley** [comment]
Thanks @ariaieboy, you are right! Will fix that today 🙂

**Comment by ariaieboy** [comment]
> Thanks @ariaieboy, you are right! Will fix that today 🙂

i am working on cursor pagination and i am gonna fix this in that PR

**Comment by joshhanley** [comment]
@ariaieboy ah no worries, I have pushed the simple pagination views fixes anyway so they aren't left incomplete, in case the cursor pagination PR isn't merged 🙂

**Pull request merged**
