### PR TITLE
fix: Call to undefined method ReflectionUnionType::getName() on multiple-types property

### PR DESCRIPTION
**Pull request by sakanjo**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

#6361

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

no

4️⃣ Does it include tests? (Required)

absolutely

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Thank you!

**Comment by sakanjo** [comment]
@calebporzio That part of code still needs to be updated since if you do `string|int` it and assign a string value it will coerce it to int `0`,

We should add something like `BuiltinSynthesizers` for built-in types.

**Comment by nuernbergerA** [comment]
I don't understand this. Why should a value be an int or string or any other mixed type?

**Comment by sakanjo** [comment]
https://github.com/livewire/livewire/assets/121197517/1eb14a7d-8d0f-4a2e-8b3c-e4678557853f

```php
<?php

namespace App\Livewire;

use Livewire\Component;

class CreateInt extends Component
{
    public string|int $value = 10;

    public function save(): void
    {
        back()->with('message', 'The value was saved!');
    }

    public function render()
    {
        return view('livewire.test');
    }
}
```

```html
<form wire:submit.prevent="save">
    @if (session()->has('message'))
        <div class="bg-green-200 text-green-800 px-3 py-2 rounded mb-6">
            {{ session()->get('message') }}
        </div>
    @endif

    <div>
        <label for="value">Value</label>
        <input wire:model="value" id="value" class="border" />
        @error('value')
            <span class="text-red-500">{{ $message }}</span>
        @enderror
    </div>

    <div class="mt-10">
        <button
            class="text-sm font-bold rounded bg-blue-500 disabled:bg-red-500 px-4 py-2 text-white"
            type="submit"
        >
            Save
        </button>
    </div>
</form>
```

@nuernbergerA we should expect different scenarios not only string|int but null|int which if you pass null it will be coerced to 0 and so on...

**Pull request merged**
