### PR TITLE
feat: make Livewire default routes configurable and publishable

### PR DESCRIPTION
**Pull request by kslimani**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?
Yes, i added some comments to #1674.

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
Nope, the commits only apply to Livewire routes.

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)
Publish command has no unit test (yet ?)

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

 - It introduce the `routes/livewire.php` file, which contains Livewire default routes
 - It add the `--routes` option to `livewire:publish` artisan command (to publish routes file)
 - It add the `routes` configuration option, if set to `false`, to disable default routes (to use published one)
 - It add `routes_namespace`, `routes_domain` and `routes_prefix` configuration options (all default to null to keep current behaviour)
 - It should __not introduce any breaking changes__ (it only adds optional features)

__Example use case 1 :__

Default behaviour is to execute requests using `/livewire/` path. Let's say i want to add a prefix and execute request using `/acme/livewire` path, all i need is :

Publish configuration file :

```console
php artisan livewire:publish --config
```
Then change `asset_url` and add the `routes_prefix` option in application `config/livewire.php` file :

```php
// [...]
'asset_url' => '/acme'
// [...]
'routes_prefix' => 'acme',
```

Finally since we modified the assets url, don't forget to rebuild Laravel application assets (`npm run dev`).

__Example use case 2 :__

Let's says we want to modify the Livewire default routes : then publish also the routes file :

```console
php artisan livewire:publish --routes
```
Then add the `routes` option (and set value to `false`) in application `config/livewire.php` file :

```php
// [...]
'routes' => false, // Disable Livewire default routes
```

Finally require the published livewire routes file, for example,  in your application `routes/web.php` file :

```php
// [...]
require_once 'livewire.php';
```

At this stade you can modify application `routes/livewire.php` to suit your needs.

---

__Miscellaneous :__

 - The `routes*` options are a proposition, i can rename them if required
 - By default if you run the `livewire:publish` command without option, it __does not publish__ routes files. I made this choice to keep current behaviour. I can modify the command to also to publish routes file if required.

### CODE REVIEW

**Comment by kslimani** [comment]
It may also help resolving routing issues like #2445.

**Comment by calebporzio** [comment]
Thank you for this PR, going to hold off on this until there is more demand for such a thing. Seems like a reasonable feature though, so let's keep an eye on demand for it. Thanks for being willing to contribute!

**Comment by denisdulici** [comment]
This is required for the [Default Values](https://laravel.com/docs/8.x/urls#default-values) feature such as locale in URL. In our case with [Akaunting](https://github.com/akaunting/akaunting), we add the tenant id as a prefix to all URLs.

@calebporzio any chance to consider it?

**Comment by moxx** [comment]
This feature is absolutely needed, why was the pull request not accepted? It is a pure improvement!

**Comment by SEUH** [comment]
@calebporzio We need this for Jetstream teams application. Because we use prefixed routes to determine the team, we also need to prefix livewire to ensure that the component does the action in the correct team.

This MR does not change that much code and enables livewire to be much more flexible so we can use it with prefixes and middlewares. We would love to see this in livewire! :)

**Comment by calebporzio** [comment]
I hear you. This PR in its current form means we are locked into not changing the code around the Livewire routes because they would be published in people's apps. If all your after is a prefix, maybe there should be a PR to make that a dedicated config option or something

**Comment by Arkhas** [comment]
Any news about that ? We are using a multi tenancy system with the tenant name in a prefix like : `myapp.com/tenant` and that would be very useful for us :)

**Comment by schakko** [comment]
+1 for a PR. In the meantime I've extended the `LivewireServiceProvider` and excluded it from auto-discovery. With that, the routes can be registered manually in the `routes/web.php`.
I did a quick [write-up about that](https://dreitier.com/knowledge-base/multitenancy-architectures/using-livewire-in-a-multitenant-laravel-application) @Arkhas

**Comment by MDGDesign** [comment]
+1 for this one!
I think this would solve my current problems https://github.com/livewire/livewire/discussions/5731.

**Comment by MarllonGomes** [comment]
+1

**Comment by gazzoy** [comment]
+1

**Comment by PhillipMwaniki** [comment]
+1

**Comment by joshhanley** [comment]
In V3, this is already possible. See here https://livewire.laravel.com/docs/installation#configuring-livewires-update-endpoint

**Comment by denisdulici** [comment]
Thanks @joshhanley for the update. It is far better now. However, I still had to [override a class](https://github.com/akaunting/akaunting/blob/master/overrides/livewire/livewire/Mechanisms/HandleRequests/HandleRequests.php#L28) to make it work.

Do you know the reason for making the URL absolute and starting with a slash?

**Comment by joshhanley** [comment]
@denisdulici hmm not sure. PRs welcome if you think it's not needed 🙂

**Comment by denisdulici** [comment]
Got it. Will do when I find some time 😉

**Comment by on-future** [comment]
+1

**Pull request closed without merging**
