### PR TITLE
[V3] Fix TemporaryUploadedFile::dimensions return type

### PR DESCRIPTION
**Pull request by luanfreitasdev**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
https://github.com/livewire/livewire/discussions/6426
2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes
3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No
4️⃣ Does it include tests? (Required)
Yes
5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

This PR corrects only the type of return that prevents other validations such as pdf, image, etc.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
Looking at Laravel's implementation, they don't have any return types. So personally, I would be more inclined to remove the return types instead of adding more. See what Caleb thinks. https://github.com/laravel/framework/blob/38434a778d48b9f64dae67f7ca4cf116878fedfb/src/Illuminate/Http/FileHelpers.php#L57-L65

**Comment by luanfreitasdev** [comment]
I thought about that too

**Comment by calebporzio** [comment]
Thanks!

**Comment by JunaidQadirB** [comment]
Thanks for accepting my Bug Report!

**Pull request merged**
