### PR TITLE
Fix #875 wire:loading.class=" "  & wire:loading.remove.class=" "

### LINKED ISSUE #875: wire:loading.class="" goes crazy
LoadingStates.js:119 Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

### PR DESCRIPTION
**Pull request by amaelftah**
this **PR** closes #875 . & fixes two issues when using wire:loading.class="" & wire:loading.remove.class=""  the browser will keep throwing token DomTokenListException as **classList.add(...classes) & classList.remove(...classes)** accepts empty variables

a quick note i wanted to add the following test in **loading_state.spce.js**

```js

test('do nothing when the loading class is empty', async () => {
   mount('<button wire:click="onClick"></button><span wire:loading.class=""></span>')
    document.querySelector('button').click()

    await wait(() => {
        expect(document.querySelector('span').classList.contains('')).toBeTruthy()
    })
})

```

but this exception kept happening . i tried to debug jsdom and other dependencies to know why this is happening for many hours but my attempts failed . so hopefully if someone knows why i would appreciate that .

Screenshot from 2020-04-28 03-53-27
Screenshot from 2020-04-28 03-53-15

### CODE REVIEW

**Comment by jjjrmy** [comment]
nie one!

**Comment by calebporzio** [comment]
Thanks for this PR, I adjusted the test and implementation - take a look if you care.

**Comment by Te7a-Houdini** [comment]
Thanks a lot

**Comment by lancepioch** [comment]
@all-contributors please add @Te7a-Houdini for code

**Pull request merged**
