### PR TITLE
base64 make return "/" and break the path

### PR DESCRIPTION
**Pull request by VakulenkoIhor**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks for this. Would love a test for this. Do you feel up for that?

**Comment by VakulenkoIhor** [comment]
> Thanks for this. Would love a test for this. Do you feel up for that?

I've added test for that case.

**Comment by calebporzio** [comment]
Thanks for the test. From a quick glance, it looks like in the implementation you are replacing forward slashes with underscores, but then in your test, you are testing a filename with spaces, not forward slashes. Can you update the test to reflect the usage you were originally trying to fix. Or if I'm miss-understanding, can you inform me? Thanks!

**Comment by calebporzio** [comment]
Closing due to inactivity - feel free to re-submit. Thanks!

**Pull request closed without merging**
