### PR TITLE
Fixes JS so it doesn't break when minified in production

### PR DESCRIPTION
**Pull request by kduma**
With this PR, minified code works 😉

### CODE REVIEW

**Comment by kduma** [comment]
There ie even a notice above that block of code 😉
https://github.com/kduma/livewire/blob/e4d220d50a1722a15f49044aaf3c64d8c91bbfb5/src/LivewireManager.php#L233-L234

**Comment by it-can** [comment]
Have the same problem...

**Comment by calebporzio** [comment]
Thanks!

**Comment by calebporzio** [comment]
Great catch. Thanks!

**Pull request merged**
