### PR TITLE
feat: add loading.display modifier to allow other display types

### PR DESCRIPTION
**Pull request by mblarsen**
This PR adds a modifier to `wire:loading` that lets you override the default display property being set when loading (`inline-block`). 

```
wire:loading.display="flex"
```

You can probably get the same functionality with clever use of `wire:loading.attr` and `style`, however that doesn't feel very Livewire.

Anyway this is useful when you have just a little more than a `Loading...` text. In my particular case my loading is an overlay on an avatar that is using the padding-ratio hack for sizing. I use flex to center the 'Uploading' text.

Test included.

### CODE REVIEW

**Comment by mblarsen** [comment]
Hmm, would I need to add this?

```
[wire\:loading.display] {
  display: none;
}

**Comment by mblarsen** [comment]
Hey @calebporzio, any change you'd consider this PR or a variation of it?

**Comment by calebporzio** [comment]
Hmmm... I'm not sure about this API.

Are you using Tailwind? Wondering if it would be crazy to just check for the existence of a "flex" class (or "block" or "inline") and set the display type accordingly. Am I crazy?

**Comment by mblarsen** [comment]
I know what you mean about the API. But the more I look at it it grows on me. It is like a modifier for loading. (which is a display directive). Like enter for `keydown.enter`.

The default is fine for most cases, so I don't think you'll start seeing code littered with `wire:loading.display="flex"`.

I happen to use Tailwind, but it seems like a worse idea to code for a specific CSS framework, no matter how awesome it is.

**Comment by underdpt** [comment]
I just hit this issue, but not using tailwind but bootstrap4. I think it would be an error to tail livewire to an specific css framework.

Also, I like the solution the PR provides, as it allows the developer to use different properties in different contexts.

**Comment by devinfd** [comment]
I'm not sure that this PR is what is needed. The bottom line is that livewire should not add `display:inline-block` to `wire:loading` elements. When the element is loading the display property should just be removed so that either the element will behave it's natural way or use any display css given to it via classes.

ref: https://github.com/livewire/livewire/issues/885

**Comment by mblarsen** [comment]
Yes I guess it can be solved by removing the display style and then make use us .class and .class.remove

Perhaps keep it if class modifier isn't used. In other words when using the .class modifier no display is set.

loading use style
loading.class no style change
loading.class.remove no style change 

This is a breaking change though. 

The wire:loading css rule that hides can be kept as well.

**Comment by Francismori7** [comment]
> I'm not sure that this PR is what is needed. The bottom line is that livewire should not add `display:inline-block` to `wire:loading` elements. When the element is loading the display property should just be removed so that either the element will behave it's natural way or use any display css given to it via classes.
> 
> ref: #885

CC @calebporzio 

Hey there,

You requested a demo, here's a quick screen capture of the problem. I disabled the "display: none" on wire:loading for testing purposes. As you can see, Livewire adds a style property with `display: inline-block` which in turns breaks the Tailwind "flex icon" positioning on the input, since it needs to be flex (as in my classes).

IMHO: Livewire should not add `display: inline-block` but rather just add `display: hidden` when it should be hidden, the display property's responsibility should be to the styling of the item being hidden/shown, rather than to Livewire itself.

https://streamable.com/tpf4pz

**Comment by calebporzio** [comment]
Closing this.

I've implemented a feature that solves this problem here: https://github.com/livewire/livewire/pull/1935

**Pull request closed without merging**
