### PR TITLE
Add protected storage in browser as discussed in #321

### PR DESCRIPTION
**Pull request by slava-vishnyakov**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?
Yes, #321 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)
Yes, but maybe needs more

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.
See #321

5️⃣ Thanks for contributing! 🙌
👍

### CODE REVIEW

**Comment by slava-vishnyakov** [comment]
@calebporzio 

I've added the config option and two methods to Component `getProtectedStorage()` which user can override on per-component basis, like this:
https://github.com/livewire/livewire/pull/323/files#diff-8a7a34e0fd91135184ee976810b4bfcbR34-R37  and `getProtectedStorageEngine()` which returns a specific implementation of storage.

I've extracted the protected storage behavior into two classes `ProtectedStorageInCache` (current behavior) and `ProtectedStorageInBrowser`. 

The only thing that I'm having problems with is how to test it end-to-end that it actually works. Like, for example this change: https://github.com/livewire/livewire/pull/323/files#diff-f22e3dd7206922d2012072b60be30644R21-R46 - it's not covered by any test. But I have no idea how to test it. Any help would be appreciated.

**Comment by slava-vishnyakov** [comment]
Ok, I'm a bit stuck with this. I've run `npm install` and then `npm run unminified`, now I get this:

```
 ERROR  Failed to compile with 4 errors                                                                                                                                                                                                                        1:22:40 PM

These dependencies were not found:

* @/component/DirtyStates in ./src/js/index.js
* @/component/LoadingStates in ./src/js/index.js
* @/component/OfflineStates in ./src/js/index.js
* @/component/Polling in ./src/js/index.js

To install them, you can run: npm install --save @/component/DirtyStates @/component/LoadingStates @/component/OfflineStates @/component/Polling
       Asset     Size     Chunks             Chunk Names
/livewire.js  184 KiB  /livewire  [emitted]  /livewire

ERROR in ./src/js/index.js
Module not found: Error: Can't resolve '@/component/DirtyStates' in '.../livewire/src/js'
 @ ./src/js/index.js 19:0-50 151:0-11
 @ multi ./src/js/index.js

ERROR in ./src/js/index.js
Module not found: Error: Can't resolve '@/component/LoadingStates' in '.../livewire/src/js'
 @ ./src/js/index.js 18:0-54 150:0-13
 @ multi ./src/js/index.js

ERROR in ./src/js/index.js
Module not found: Error: Can't resolve '@/component/OfflineStates' in '.../livewire/src/js'
 @ ./src/js/index.js 20:0-54 152:0-13
 @ multi ./src/js/index.js

ERROR in ./src/js/index.js
Module not found: Error: Can't resolve '@/component/Polling' in '.../livewire/src/js'
 @ ./src/js/index.js 21:0-42 153:0-7
 @ multi ./src/js/index.js
```

**Comment by slava-vishnyakov** [comment]
Ok, now (after https://github.com/livewire/livewire/pull/323/commits/ec5488d5d385624420e55e165e26173d3c21e5b7) it definitely works. Just need to figure out a few things:

1) Is there a way to add end-to-end tests? 
2) How to test JS part of all of this
3) Do I need to be concerned about `.children` (in JS/PHP) and their `.protected` fields somehow?

**Comment by slava-vishnyakov** [comment]
@calebporzio Can you help a little with these questions?

**Comment by calebporzio** [comment]
Ok, sorry I haven't gotten to this, I've been traveling.

Thanks a bunch for this PR, it's really well done.

I read through it and pulled it down locally, and I just wasn't happy with how complicated this feature needed to be because of the current architecture.

I refactored the Livewire codebase to support something like this better.

Now all your changes (except for your tests) can be isolated to one file: `src/HydrationMiddleware/HydrateProtectedProperties.php`

You should be able to add the switching from the config in there.

I know I just made more work for you, so let me know if you want me to work on this PR myself and I'm happy to, or you can continue finishing it.

Let me know.

About your questions:
1. Not at the moment (will definitely have a Dusk suite before 1.0)
2. Hmm, I'm not sure JS tests are necessary here. JavaScript is just passing through the extra encrypted property... yeah, E2E tests would be best for this. If there's a simple test to make sure that if "protected_properties" is present in the request, that it makes it's way back, maybe that'd be good, but not necessary
3. I don't think you have to be concerned with children.
4. Yes please
5. Hmm, I think you're right, it's already encrypted, let's leave it out of the checksum

Let me know, thanks again @slava-vishnyakov

**Comment by slava-vishnyakov** [comment]
@calebporzio Cool! Thanks for the answers! 

I'll check out the new branch and see if I can do a PR.

**Comment by slava-vishnyakov** [comment]
Closing this for now, will open a new PR.

**Comment by slava-vishnyakov** [comment]
@calebporzio 
Just to be clear - did you mean something like this?

image

**Comment by calebporzio** [comment]
Yeah, something along those lines, yes.

**Comment by slava-vishnyakov** [comment]
Should we keep the ability to override the storage per component? I.e. I want for ex. some components to be stored in cache, but others in browser, like this?

image

**Comment by calebporzio** [comment]
Yeah, I do think that'd be helpful

**Comment by slava-vishnyakov** [comment]
Trying to wrap my head around the idea of "Now all your changes (except for your tests) can be isolated to one file"

1) When the component is first rendered into HTML - neither `hydrate`, nor `dehydrate` method is called, which seems like a bug, actually.

I've tried this and the component happily rendered.

image

Which leads me to this discovery. Here's a simple counter that doesn't start with 0, but rather takes its value from some secret secure storage:

image

Let's see what happens:

ScreenFlow

The initial value is always discarded and the counter doesn't work as expected. Seems like a bug to me, or is it intended?

2) Again, returning to the idea that "all your changes (except for your tests) can be isolated to one file". Here's the `InitialResponsePayload` being created:

image

I'm not sure where the `protected` properties would end up here if I can't touch this file. The only place is `data`, but it is initialized by the function `$properties = $instance->getPublicPropertiesDefinedBySubClass();` 

Here we have 2 problems: it returns only `public` properties and it doesn't call hydrator.. So I have no influence on this function (or any other in `new InitialResponsePayload` call).

So, now, do we hide the protected properties in the `data` somehow?

I'm kind of stuck here. Any ideas?

**Comment by calebporzio** [comment]
Sorry, @slava-vishnyakov - you're right.

I refactored further. Check out the new tagged release for the code updates.

Basically, you would manipulate the `$response` object to add a "protected_properties" property. This property will now be automatically added the component's initial data payload AND  subsequent ones.

Hope this makes sense, if it doesn't I'm happy to hop  on a Zoom call or something.

**Comment by slava-vishnyakov** [comment]
After updating and trying this:

```
@livewire('counter', 42)
```

I'm getting this:

```
Object of class Illuminate\Support\Fluent could not be converted to string (View: ../livewire/src/Macros/livewire-view.blade.php)
```

image

image

image

Either I did something obviously stupid or maybe we should add CircleCI + Dusk?..

**Comment by slava-vishnyakov** [comment]
Ok, scratch that. It was a cached view.

**Comment by slava-vishnyakov** [comment]
Ok, so I think the idea is like this:

```
    public static function hydrate($unHydratedInstance, $request)
    {
        // I should have $request->protected_properties here
    }

    public static function dehydrate($instance, $response)
    {
        $response->protected_properties = ['a' => 1];
    }

```

However it does not work:

```
    public static function hydrate($unHydratedInstance, $request)
    {
        # $request->protected_properties;
        # Trying to get property 'protected_properties' of non-object

        # $request['protected_properties'];
        # ErrorException: Undefined index: protected_properties
    }

    public static function dehydrate($instance, $response)
    {
        $response->protected_properties = ['a' => 1];
    }
```

I see this:

```
wire:initial-data="...],&quot;protected_properties&quot;:{&quot;a&quot;:1},&quot;children
```

Which is a good sign.

However the JS part still seems to have only a few hardcoded properties:

image

So my property never arrives back to the backend.

**Comment by slava-vishnyakov** [comment]
The screenshot is `src/js/Message.js`

**Comment by calebporzio** [comment]
@slava-vishnyakov, you're correct. We have to either update the JS to allow for "passing-through" data that isn't explicitly declared.

What do you think the best thing to do is here?

I'm tempted to just add the "protected_properties" as an optional param that will be added to the request if it exists from the previous response (same with the initial extraction of the data in component/index.js) - thoughts? Thanks for pushing on this!

**Comment by slava-vishnyakov** [comment]
Well, off the top of my head I can't think of anything else that we might
need to pass and even if that happens - it's probably easier to just
hardcode one more property.

Another solution cold be to have a 'custom' prop and just json encode it
for props like '$response->custom->protected'.

Maybe the 'custom' way is more flexible, though maybe it opens some new
attack vectors... Can't think of any though

**Comment by slava-vishnyakov** [comment]
Two things that bug me about `custom` approach. 

1. If we were decoding to a simple stdClass or array - we'd probably be much safer than if we use something like Fluent, which has a few methods of its own, maybe it's somehow possible to craft something like `{"custom": {"../data": "..."}}` to override the `.data`.. I'm not sure, doesn't seem likely, but still it's a class with a bunch of methods.

2. Having a `custom` I'd probably feel safer if it were checksummed too. But then again, what prevents somebody in future from setting `$response->custom->my_nice->nested_thing = [true, 0, (stdClass)['a' => null]]`, so now the checksumming becomes a small nightmare. :)

**Comment by calebporzio** [comment]
True, I say we just hardcode an extra param on the front-end for now.

Yeah, I was thinking the same thing with attack vectors, but too couldn't think of any.

Thanks.

**Pull request closed without merging**
