### PR TITLE
Add support for named error bags

### PR DESCRIPTION
**Pull request by mabdullahsari**
For every bit of relevant context and why this is needed, please see https://github.com/livewire/livewire/discussions/2585#discussioncomment-2282452 first.

---

This PR allows the use of the `Validator`'s error isolation feature using `validateWithBag`.

Remarks:

- I am not sure about the new property's name suffixed with "Key" because `errorBag` is already in use. Perhaps the current property should be renamed to `errors` / `messages`.
- I have deliberately omitted `PerformDataBindingUpdates` because that should always be the `default` error bag (I think?).
- Not sure if tests are sufficient, or in the right place. Corrections definitely welcome.

Thanks 🙏

### CODE REVIEW

**Comment by mabdullahsari** [comment]
The failing tests are probably unrelated to my changes.

**Comment by joshhanley** [comment]
@mabdullahsari thanks for the PR! I've re-run the tests

**Comment by mabdullahsari** [comment]
> @mabdullahsari thanks for the PR! I've re-run the tests

Failing test is unrelated, still. This probably fixes it? https://github.com/livewire/livewire/pull/4796

**Comment by joshhanley** [comment]
@mabdullahsari yeah there was an issue with that test. It has been fixed on the master branch. Can you merge master in to your branch?

Thanks!

**Comment by mabdullahsari** [comment]
> 

Done, but looks like something's still failing. I ran the test locally, and everything ran fine. ¯\_(ツ)_/¯

**Comment by joshhanley** [comment]
@mabdullahsari yeah, it's all good though, all test suites except one have passed, so its probably just an issue with dusk (happens occasionally) 🙂

**Comment by calebporzio** [comment]
Thanks for submitting, going to hold off on this for now though.

**Comment by mabdullahsari** [comment]
> Thanks for submitting, going to hold off on this for now though.

Okay, but what do you recommend as an alternative then? I have provided details in the discussion as to why I would **not** like to create separate components for these. Thanks.

**Pull request closed without merging**
