### PR TITLE
Adds error when multiple root tags are present

### PR DESCRIPTION
**Pull request by Roboroads**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?
#1493  

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
Nop.

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)
Yep!

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.
Someone who did not thoroughly read the documentation (like me - sorry) an error like this can save hours of debugging time. Since it just silently fails right now although it's intended behaviour. 

5️⃣ Thanks for contributing! 🙌
You're welcome :smile:

### CODE REVIEW

**Comment by Roboroads** [comment]
Busy fixing the tests ;)

**Comment by Roboroads** [comment]
NOTE: This test fails on 2.0.4/master as well - this will be fixed with #1495

**Comment by Roboroads** [comment]
Since #1495 got merged - tests are now resolved :smile:

**Comment by calebporzio** [comment]
Thanks for this PR.

I totally understand the need for this, but I really don't want to add extra processing to every single Livewire request for this case.

Going to hold off for now and just try to make the docs better (would love a PR for that)

Thanks!

**Comment by damms005** [comment]
@calebporzio Since such extra processing is a concern, something like `dev mode` can be made available (like Vue JS does)

**Comment by calebporzio** [comment]
Ah, interesting. Like only check when app debug is true or something. I could get with that

**Comment by Roboroads** [comment]
I can change the PR to include this!

**Pull request closed without merging**
