### PR TITLE
Sort HTML DIRECTIVES

### PR DESCRIPTION
**Pull request by altwaireb**
Sort HTML DIRECTIVES in navigation

### CODE REVIEW

**Comment by calebporzio** [comment]
why?

**Comment by altwaireb** [comment]
To make it easy to find, most sites do this, and if you look closely at the Laravel documentation, you will find that.
laravel_dec

**Comment by lrljoe** [comment]
Yet at the same time, the Laravel site also doesn't.  It's just the Packages that are alphabetically sorted.

image

It seems more logical to me in terms of what you're most likely trying to do when getting started.
wire:click, wire:submit and wire:model are the first things that people will try to use when getting started.  Burying wire:model halfway down the list isn't going to help a newcomer, and that's who the docs are for in reality.

Also - please read the notes when creating a PR, main branch PRs are not accepted, ever.

**Comment by calebporzio** [comment]
yeah, torn on this one too - thanks for the PR, but closing it for now

**Pull request closed without merging**
