### PR TITLE
[JS] Fix broken IE11 support by transpiling spread syntax using babel

### PR DESCRIPTION
**Pull request by ruudsnl**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?
Yes! It fixes the issue of Livewire not initializing in both IE11 and Edge. The issue can be found here: #585 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
Nope

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)
Nope

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.

- Added the following Babel plugin to transpile spread syntax in object literals: 
https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread which is not supported in IE11 and early versions of Edge
- Furthermore, to prevent similar issues in the future I added IE11 as a target in the Babel config.
- Rebuilt the assets, the compatible version can be found in the dist directory

I have tested this in Edge using Browserstack and it seems to work.

More info on spread syntax compatibility: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals

5️⃣ Thanks for contributing! 🙌
More than welcome, thanks for Livewire.

### CODE REVIEW

**Comment by calebporzio** [comment]
Hey @ruudschuurmans, I pulled down the PR (thank you BTW), but all the tests are failing with:

image

Are you seeing the same thing?

**Comment by ruudschuurmans** [comment]
Hey @calebporzio I will check this out tomorrow and follow up. Thanks for letting me know!

**Comment by ruudschuurmans** [comment]
Apparently, the new build target (ie11) needed another babel plugin to make the Jest test framework work. So `@babel/plugin-transform-runtime` has been added and that fixed the tests. (more at: https://github.com/facebook/jest/issues/3126)

**Comment by ruudschuurmans** [comment]
Fixed by adding `node: current` as babel target for the test environment. (more at: https://github.com/facebook/jest/issues/3126)

**Comment by calebporzio** [comment]
I can't seem to pull your branch down, did you do any rebasing that might have messed up the tree?

image

**Comment by ruudschuurmans** [comment]
oof, you're right my rebase was not the best way to go. I'll clean up the branch later and ping you!

**Comment by calebporzio** [comment]
Any progress on this?

**Comment by ruudschuurmans** [comment]
@calebporzio  Fixed the rebase, now JS tests are working too for me!
Weird thing is, even though no PHP files have been changed in this PR, the PHP tests are failing in the Github CI?

**Comment by calebporzio** [comment]
Thanks!

**Comment by lancepioch** [comment]
@all-contributors please add @ruudschuurmans for maintenance

**Pull request merged**
