### PR TITLE
Set array properties

### PR DESCRIPTION
**Pull request by SamDeimos**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by ju5t** [comment]
Can you explain what this does?

**Comment by SamDeimos** [comment]
> Can you explain what this does?

allows changing values ​​in an array

**Comment by SamDeimos** [comment]
This is an example of use

image

**Comment by calebporzio** [comment]
Thanks for being willing to contribute, however in the interest of keeping the Livewire surface area slim, I'm going to close this.

**Pull request closed without merging**
