### PR TITLE
make componet view name dynamically

### PR DESCRIPTION
**Pull request by almas-x**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
@almas1992 - thank you. Mind adding a test for this?

**Comment by almas1992** [comment]
> @almas1992 - thank you. Mind adding a test for this?

Actually, I really don't know how to write unit tests yet，I'm so sorry about that.

**Comment by calebporzio** [comment]
@almas1992 No Problem! Then, would you mind pasting in a code sample of something that doesn't work before merging this PR? that would help demonstrate it's purpose and help me write a unit test. Thanks!

**Comment by almas1992** [comment]
1. Change view_path in config file `livewire.php`

```php 
 'view_path' => resource_path('views/other/path'),
```

2. Run the make command `php artisan make:livewire counter` , it will be make blade file  `counter.blade.php` in the path `resources/views/other/path/counter.blade.php`

3.The counter component 

Before

```php
namespace App\Http\Livewire;

use Livewire\Component;

class Counter extends Component
{
    public function render()
    {
        return view('livewire.counter');
    }
}
```
> The view name was wrong

After

```php 
namespace App\Http\Livewire;

use Livewire\Component;

class Counter extends Component
{
    public function render()
    {
        return view('other.path.counter');
    }
}
```

**Comment by calebporzio** [comment]
Thanks for the explanation!

**Comment by lancepioch** [comment]
@all-contributors please add @almas1992 for code

**Pull request merged**
