### PR TITLE
Improve Navigate Behavior

### PR DESCRIPTION
**Pull request by danie-ramdhani**
This PR is fixing:

- Do nothing when href doesn't exist (before is navigate to `null` path)

- Open in new tab and don't fetch new page when `target="_blank"` attribute exist

- Don't fetch new page when user long click the link (before is prefetching the link before click is released)

How it's works before (it's prefetching before the click is released)

[How it's works before (it's prefetching before the click is released)](https://github.com/livewire/livewire/assets/58886605/3f2af2d2-5e77-4134-85ca-73ab75a07152)

How it's works if this PR merged

[How it's works if this PR merged](https://github.com/livewire/livewire/assets/58886605/0e61f5c5-75ae-4b7c-9230-347fd87efd11)

### CODE REVIEW

**Comment by SRWieZ** [comment]
Hey! I'm pretty sure the last point is a feature, not a bug 😉

**Comment by danie-ramdhani** [comment]
> Hey! I'm pretty sure the last point is a feature, not a bug 😉

idk... what if user is long click the link then click another link or in the mobile version, the user is long click to open the modal browser (idk how people call it).

**Comment by joshhanley** [comment]
@danie-ramdhani Thanks for the PR! Can you please split these changes into separate PRs so they can be reviewed individually and also add tests? Thanks!

**Comment by danie-ramdhani** [comment]
> @danie-ramdhani Thanks for the PR! Can you please split these changes into separate PRs so they can be reviewed individually and also add tests? Thanks!

Got it, but i don't know how to test the last point (Don't fetch new page when user long click the link, before is prefetching the link before click is released) sorry for late reply!

**Pull request closed without merging**
