### PR TITLE
PHP 8.2 support

### PR DESCRIPTION
**Pull request by ariaieboy**
add #[AllowDynamicProperties] on classes that use dynamic property

### CODE REVIEW

**Comment by joshhanley** [comment]
@ariaieboy thanks for starting this! I've renamed this, php 8.2 support.

You will need to add exclusions in for php 8.2 and Laravel 7, and possibly 8. But just do 7 for now so we can see if the tests run.

See here how it was done for php 8.1

image

**Comment by ariaieboy** [comment]
> @ariaieboy thanks for starting this! I've renamed this, php 8.2 support.
> 
> You will need to add exclusions in for php 8.2 and Laravel 7, and possibly 8. But just do 7 for now so we can see if the tests run.
> 
> See here how it was done for php 8.1
> 
> image

it seems that laravel 8 is compatible with php8.2 at least for livewire tests

**Comment by joshhanley** [comment]
@ariaieboy ok great, thanks! All looks good to me

**Comment by joshhanley** [comment]
@ariaieboy hey I was just testing Livewire on PHP 8.2 (running phpunit locally), and couldn't get it to display the deprecation notices. Did you do anything special to get them to show up/ how did you work out which files should be tagged with the allow deprecated properties attribute?

**Comment by ariaieboy** [comment]
> @ariaieboy hey I was just testing Livewire on PHP 8.2 (running phpunit locally), and couldn't get it to display the deprecation notices. Did you do anything special to get them to show up/ how did you work out which files should be tagged with the allow deprecated properties attribute?

actually I've just used the phpstorm latest version inspect code.

**Comment by joshhanley** [comment]
Thanks @ariaieboy for the PR! I had to ensure the `AllowDynamicProperties` was imported/ fully namespaced to get it to work properly.

**Comment by ariaieboy** [comment]
@joshhanley thanks for your updates on this PR.
can you tag the changes so we can have these changes in our projects without using the dev-master?

**Comment by joshhanley** [comment]
@ariaieboy we're just finalising another PR first before looking at tagging a release 🙂

**Pull request merged**
