### PR TITLE
Skip rendering on redirects

### LINKED ISSUE #940: skip render when redirect is set
**Is your feature request related to a problem? Please describe.**
I have a component that renders a model.  In this component is a delete button. When the delete is hit, the function removes the model and sets the redirect.  Control then passes to the render() function which tries to render the now deleted model, resulting in an error.

**Describe the solution you'd like**
Issue a redirect without needing to render the full component.

**Describe alternatives you've considered**
I have a workaround that checks `$this->redirectTo` in the render method, ane immediately returns.  Unfortunately it also needs to return a view, and this must be populated with valid data even though it will not be seen.
```
    public function render()
    {
        if($this->redirectTo){
            return view('livewire.foodbanks.foodbank-card')->withFoodbank(new Foodbank());
        }

        // etc with the required render functionality
```

### PR DESCRIPTION
**Pull request by nuernbergerA**
Fixes #940

### CODE REVIEW

**Comment by zepfietje** [comment]
This probably also fixes https://github.com/livewire/livewire/issues/1110.

**Comment by calebporzio** [comment]
Thanks @nuernbergerA !!!

**Comment by AdvancedStyle** [comment]
How does this actually work?

I've added a redirect to mount and it just shows my empty layout and doesn't redirect?

```
public function mount(){
return redirect()->to(route('home'));
}
```

**Comment by nuernbergerA** [comment]
@AdvancedStyleits `$this->redirect()`

**Comment by AdvancedStyle** [comment]
I tried this too, same thing happens, just shows empty layout, no redirect:

```
public function mount(){
$this->redirect(route('home'));
}
```

```
public function mount(){
return $this->redirect(route('home'));
}
```
etc... (I tried many different ways to use redirect())

**Comment by zepfietje** [comment]
@AdvancedStyle @nuernbergerA, this hasn't been released yet. So if your project is still in development, you can use `dev-master` for the Livewire dependency. Else, you'll have to wait until a new version gets tagged (no idea when).

**Comment by nuernbergerA** [comment]
@AdvancedStyle can you please open an issue with exact steps to reproduce. i assume it's related to turbolinks.

cheers
adrian

**Comment by AdvancedStyle** [comment]
I don't think it is turbolink related seeing as I've tried removing turbolinks from the project and the problem is still the same.

Unfortunately I can't make a laravel playground example seeing as this version is not yet tagged :( I'll make an example and open issue once this is possible.

Just to be sure that I'm not doing something dumb; it should work like this right?

If you add a web route directly to a Livewire Component (such as):

```
Route::get('mypage', \App\Http\Livewire\MyPage\Index::class)->name('mypage');
```

Then put a redirect in the mount, such as below, then it should never render a 'mypage' and just redirect straight to the homepage?

```
public function mount(){
$this->redirect(route('home'));
}
```

**Comment by nuernbergerA** [comment]
@AdvancedStyle can you test again with the latest dev-master?

**Comment by AdvancedStyle** [comment]
@nuernbergerA Yes seems to work just like a normal Laravel redirect now 👍

**Pull request merged**
