### PR TITLE
Support customized AlpineJS prefix

### PR DESCRIPTION
**Pull request by edvordo**
- [x] Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
- [x] I'm actively customizing the AlpineJS prefix in my projects and with V3 various things do not work / half work (explained below).

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
- [x] Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
- [x] No, everything is related to support the customized AlpineJS prefix.

4️⃣ Does it include tests? (Required)
- [x] Yes.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
Created a demo in [this repository](https://github.com/edvordo/livewire-v3-apline-customized-prefix) to show things not / half working:
 - `wire:navigate` does a full page load instead of the SPA-like load
 - button with `data-x-data data-x-on:click` works and shows an alert
 - `wire:click` does not work - no request is performed
 - plugins included with the customized prefix, such as `data-x-collapse` work as expected
 - `data-x-cloak` is removed after page load

I wasn't sure how to include the built javascript file with fixed livewire.esm.js and changed AlpineJS prefix for tests purposes, so I build it in a project, where I copied over the built livewire assets (with this PR changes) and included it as a standalone file (`src/Features/SupportNavigate/test-views/compiled-custom-livewire-init.js`). The source of this file is also included (`src/Features/SupportNavigate/test-views/source-custom-livewire-init.js`).

I'm happy to add more tests if needed.

### CODE REVIEW

**Comment by edvordo** [comment]
I see that my changes to the JS portions made quite a bit of changes to the built livewire.* files, while changes in other PRs did very minimal changes. So, a few questions: 

What do I need to do to fix this behavior? 
Do I need to npm link all the modules / packages from alpinejs repository? How to handle directives?
What node/npm versions should I use for build?

I'll resolve the conflicts from other PRs merged in the mean time, of course.

**Comment by joshhanley** [comment]
@edvordo thanks for the PR!

Due to the nature of your PR, I'd expect it to change a lot in the compiled assets, so don't be concerned about that. 
Regarding the npm link, no you no longer need to do that, so just a straight `npm install` and `npm run build` should work happily.

**Comment by edvordo** [comment]
@joshhanley While I agree I changed fair few files, [this change](https://github.com/livewire/livewire/pull/6751/files#diff-082bdedd3673dc44256e2be1be654a4ec9ee479e286fb8149186c278eb11b1eaR2818) (and fair few others where just a number increases) in compiled esm.js file seems a bit too random.
But alright, if you say I don't need to worry about it, I won't and just merge in changes from other PRs. Thank you for the feed back!

**Comment by edvordo** [comment]
Updated to upstream changes, but I had to pull aplinejs main repo and copy a build into node_modules, otherwise the "teleport within persist" tests would fail, as that version of AlpineJS is not released yet, but it is already included in built livewire.* files. Might be a good idea to wait for the alpinejs release so it does not have to be hacked in 🙃

**Comment by edvordo** [comment]
Not trying to rush anything, I'm sure not many people need it too much (me included), just trying to get feedback on whether you'd want me to do anything else for this PR, like add tests, add the support elsewhere (might have missed a place not on purpose) or anything else really or are we just waiting for alpinejs tag/release? :)

**Comment by joshhanley** [comment]
@edvordo Caleb is currently away on holidays, so it will need to wait until gets back 🙂

In regards to building Alpine, instead of manually editing node modules folder, you can use `npm link` to link to a cloned version of the Alpine repo. I know I previously said not to use `npm link`, but since I said you didn't need to do that, we've had to do it again as there a few things on the Alpine main branch that Livewire needed for tests to pass.

I wouldn't worry about merging main and building assets just yet, let's wait to see what Caleb thinks of the PR first. Generally he will merge main and build the assets.

**Comment by joshhanley** [comment]
@edvordo thanks for the PR! At this stage, Caleb doesn't want to support this, so we're going to close this for now. Thanks for being willing to contribute!

**Comment by edvordo** [comment]
But it's already half supported, why leave it in an incomplete state?

No support also puts additional workload on me when I upgrading to V3 as everything in my codebase depends on the customised prefix.

Can I at least try to reintroduce this PR in like a month or something?

**Comment by joshhanley** [comment]
@edvordo I think he doesn't like supporting it in Alpine either. See here for details https://github.com/alpinejs/alpine/pull/3334#issuecomment-1406674120

But you're welcome to try and submit it again later to see if he has changed his mind 🙂

**Comment by edvordo** [comment]
Which a tad bit unlikely, knowing his stance on it (from not long after alpine was released https://github.com/alpinejs/alpine/pull/506#issuecomment-632347442) and seeing his sentiment from January 3 years later.

I'll have to find a way to live with it (well, my friend will, I have zero issues with using alpine "as-is" / "as-intended").

**Pull request closed without merging**
