### PR TITLE
Loading target with parameters

### PR DESCRIPTION
**Pull request by dsazup**
Hello, this PR is related to issue #402 and also a point in the roadmap:

`Scope loading targets to actions WITH parameters: <div wire:loading wire:target="updateTodo({{ $todo->id }})">`

I have run into this issue today. Imagine I have a list of payment plans. Each row has 'upgrade' button that you can click. Once you click it, I need to show a spinner on the button. This is currently not really possible, as the spinner would be displayed on all buttons. I read through the issues and also noticed the roadmap and decided to give it a go.

I was wondering if you would consider a slightly different, though easy to achieve syntax. 

Instead of parsing the` updateTodo('title', 1)`, I propose to have syntax such as `updateTodo:title:1`. This way we do not need to worry about combining the parameters and having exact same signature, as there could be a lot of issues, for example double or single quotes, spacing etc. 

In my PR you will notice if there are params it returns 2 actions, for example with the todo case it would return `updateTodo` and `updateTodo:title:1` so that both

`<div wire:target="updateTodo">` and `<div wire:target="updateTodo:title:1">` could work.

Do you see any issues with it?

### CODE REVIEW

**Comment by basepack** [comment]
This is a great idea imo. Your PR has my +1 👍

**Comment by jjjrmy** [comment]
need this! thanks 🙏

**Comment by calebporzio** [comment]
Thanks for submitting this PR.

I agree, it would be great if we could add support for targeting specific method/param combinations.

I think in my ideal world, the syntax would be as follows:
```
<button wire:click="foo('bar', 'baz')">
<span wire:loading wire:target="foo('bar', 'baz')">
```

Rather than the proposed `foo:bar:baz`

To me, this would be a more intuitive syntax. I imagine this is the syntax a developer would "guess" would work. I'd rather not introduce a new syntax here if we can help it.

As far as retrieving the method and parameters form something like `wire:target="foo('bar', 'baz')"`, that part should actually be easy. There is a "directive.method" and "directive.params" accessors on the element's directive object to use the same regex we use for firing methods and params.

That being said, currently `wire:target` supports targeting multiple actions separated by a comma: `wire:target="foo, bar"`.

I imagine this would trip up the existing method/params regex.

So, my assessment of this feature is this:
* I agree Livewire should offer this capability
* I'd much rather implement the more intuitive `foo('bar', 'baz')` syntax over `foo:bar:baz`
* I think it's possible, it will just be even more difficult because the existing regexes will have to be updated, or new ones will need to be created.

I'm interested in others thoughts on my notes.

Thanks!

**Comment by dsazup** [comment]
Thanks for the feedback. I tried to achieve that syntax at first, but just did not find an easy way to do it. Will need to familiarise with the codebase more. I might look into this again later, but if anyone wants to do it in the meantime, feel free.

**Comment by jjjrmy** [comment]
could this also work with dirty state?

**Comment by mokhosh** [comment]
@calebporzio I think supporting multiple actions with `wire:target="foo|bar"` is even better. Fixes the conflict too.

**Comment by kentin84000** [comment]
This feature still works with the latest version of Livewire?

**Pull request closed without merging**
