### PR TITLE
Fix for TypeError in invokable components

### PR DESCRIPTION
**Pull request by alexandre67fr**
When testing invokable components with PHPUnit (for example, `$this->createApplication(); $this->actingAs($user)->get(route('component'))`), a `TypeError` occurs.
This is because `request()->route()` is `null`.

To fix this, we override `$route` only if `request()->route()` is not null

### CODE REVIEW

**Comment by joshhanley** [comment]
@alexandre67fr any chance you could add a test that would fail without this change?

**Comment by alexandre67fr** [comment]
@joshhanley you're welcome :)  
sure, I've added a test

On Livewire v2.8.0, it fails with

```
TypeError : Argument 1 passed to Livewire\ImplicitRouteBinding::resolveAllParameters() must be an instance of Illuminate\Routing\Route, null given, called in src/Component.php on line 59
 src/ImplicitRouteBinding.php:24
 src/Component.php:59
 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48
 vendor/laravel/framework/src/Illuminate/Routing/Route.php:262
 vendor/laravel/framework/src/Illuminate/Routing/Route.php:205
 vendor/laravel/framework/src/Illuminate/Routing/Router.php:695
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
 vendor/laravel/framework/src/Illuminate/Routing/Router.php:697
 vendor/laravel/framework/src/Illuminate/Routing/Router.php:672
 vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
 vendor/laravel/framework/src/Illuminate/Routing/Router.php:625
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
 src/DisableBrowserCache.php:19
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:142
 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111
 vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:510
 vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:294
 tests/Unit/RouteRegistrationTest.php:30
```

With the small change proposed in MR, this new test won't fail.

**Comment by joshhanley** [comment]
@alexandre67fr thanks! 🙂

**Comment by calebporzio** [comment]
Great stuff thanks @alexandre67fr and @joshhanley  for the help!

**Pull request merged**
