### PR TITLE
fixed encoding when building method + param signature - closes #2390

### LINKED ISSUE #2390: Problem with encoding $set() function
### Description
When i try to send in javascript with $set() function some special char like "řěšč" i will get error 
`Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.` And livewire start sending every second new request to `http://webdo.test/livewire/message/...`, but what is interesting is that if i look into variable value i get a right value with special chars. So i think it will be only something with the nonending requests. 

### Stripped-down, copy-pastable code snippets
There is no needed so long code to show. Just try in blade component add this into <script></script>
`@this.set('variable', 'žžž');`

**Context**
- Livewire version: [2.3.6]
- Laravel version: [8.3.1]
- Alpine version: [2.3.0]
- Browser: [Chrome, Firefox]

### PR DESCRIPTION
**Pull request by austenc**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?

Reported in #2390

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No sir!

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)

Yes, I added an additional chunk to the Alpine dusk test.

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

When an action happens we serialize the method and params with `btoa` in javascript. This results in an error when trying to set a variable to something that contains strange characters like `žžž`.

Other uses of `btoa` within Livewire use `encodeURIComponent`, so I added that to the params in this case. 

5️⃣ Thanks for contributing! 🙌
🍻

### CODE REVIEW

**Comment by htulibacki** [comment]
People who use these strange characters on a daily basis as an integral part of their language will be very grateful for merging this pull request! 😄

**Comment by mokhosh** [comment]
@htulibacki Yes, everyone who is using non Latin characters (Persian, Arabic, Hebrew, Hindi, Urdu, Japanese, etc.) will be very grateful, including myself.

@calebporzio Appreciate the frequent releases lately. Can you please merge this in one of these releases?

**Comment by mityukov** [comment]
need this fix badly… :/

**Comment by JunaidQadirB** [comment]
When is this PR going to be merged?

**Comment by baceto90** [comment]
I have a problem with Cyrillic characters too. Hopefully this pull request will be merged as soon as possible.

**Comment by mokhosh** [comment]
@austenc seems like you have spatie/ray in your composer.json and it's causing the tests to fail. It might help with this getting merged if the tests are passing when @calebporzio gets here :D

**Comment by austenc** [comment]
@mokhosh thanks for the reminder -- updated with latest master and tests are now passing!

**Comment by fawzanm** [comment]
Thanks for this PR. I badly need this PR to get merged. 😔

**Comment by calebporzio** [comment]
Merged and tagged, thanks!

**Pull request merged**
