### PR TITLE
Fix - Use alias for page, if defined

### PR DESCRIPTION
**Pull request by dsturm**
Since we are allowed to [define an alias](https://laravel-livewire.com/docs/2.x/query-string#query-string-aliases) for the page query string parameter, the `resolvePage` method should consider this for resolving the current page from request.

Before this fix, deeplinking / reloading would not recognize the alias and would show the first page instead.

Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

4️⃣ Does it include tests? (Required)

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@dsturm thanks for the PR! Can you please add tests for this change? Thanks!

**Comment by dsturm** [comment]
Hej @joshhanley, after some kind of struggling I've now added a test for this PR.

**Comment by joshhanley** [comment]
@dsturm great thanks! Test looks good, I've trigged the tests to run 🙂

**Comment by dsturm** [comment]
Hej @joshhanley,

this PR fails currently on a separate test (`Tests\Browser\Loading\Test::test_different_delay_durations`). How should I proceed here?

**Comment by joshhanley** [comment]
@dsturm yeah there was an issue with that test. It has been fixed on the master branch. Can you merge master in to your branch? Then we will re-run the tests.

Thanks!

**Comment by dsturm** [comment]
Hej @joshhanley, I merged the master into the PR. Can you please re-run the tests?

**Comment by joshhanley** [comment]
I've triggered them to run 🙂

**Comment by dsturm** [comment]
Hej @joshhanley,

I'm sorry, but I quiet don't understand why the tests are failing again. If there is anything I could do, please let me know.

**Comment by joshhanley** [comment]
@dsturm I'll re-run them again so we can have a look and see what the error is 🙂

**Comment by nuernbergerA** [comment]
@dsturm merge Master again, should be fixed now

**Comment by dsturm** [comment]
I’ve merged the master branch, since there was again a failed test, which wasn’t touched by this PR 🤔

**Comment by joshhanley** [comment]
@dsturm I've re-run tests, and it all looks good now 🙂

**Comment by calebporzio** [comment]
Makes good sense. Thanks!

**Pull request merged**
