### PR TITLE
Migrate contribution guide to v3

### PR DESCRIPTION
**Pull request by inxilpro**
I noticed that the existing PR template still references the v2 contribution guide. This is a quick stab at migrating the guide over for v3. I started with the existing v2 guide and then updated it to match both the contents of the github `CONTRIBUTING.md` file and the style changes in the new docs (dropped `@component` calls in favor of markdown, etc).

### CODE REVIEW

**Comment by sajjadhossainshohagbd** [comment]
Hi @inxilpro ,
I trying to set up locally following your contribution guide. But I am getting an error when running tests.

Can you solve this?

**Note: I am using Windows 11.**

`Fatal error: Cannot declare class Livewire\Features\SupportModels\Post, because the name is already in use in C:\Users\sajja\Desktop\testing-lab\packages\livewire\src\Features\SupportModels\BrowserTest.php on line 130`

**Comment by joshhanley** [comment]
@inxilpro and @sajjadhossainshohagbd yeah we need to fix the namespace collision. Chris, I would revert the run individually docs changes and instead we can just fix the problem. I typically run them all together (and it's what I would recommend).

I wrote the original contribution guide, so I will try and have a good look at your PR this week 🙂

**Comment by PhiloNL** [comment]
@sajjadhossainshohagbd have you tried running the test individually? 

```shell
./vendor/bin/phpunit --testsuite Unit
./vendor/bin/phpunit --testsuite Browser
./vendor/bin/phpunit --testsuite LegacyBrowser
```

We will fix the namespace collision in a different PR, as it might be related to Windows in this case as it seems to work fine on my Mac.

**Comment by joshhanley** [comment]
@PhiloNL ok sweet, thanks! 😁

**Comment by joshhanley** [comment]
FYI have fixed the namespace collision in PR #7499 and merged it. @sajjadhossainshohagbd can you pull the latest changes from the main branch, and try and run tests again and let us know how you go? Thanks!

**Comment by sajjadhossainshohagbd** [comment]
@joshhanley Now, I am trying to run tests. The previous error is gone but a new error is found. Some unit tests fail and then show this error on browser tests.

**Terminal Screenshot:**

Screenshot 2023-12-10 114250

**Browser Screenshot:**
Screenshot 2023-12-10 114438

**Comment by joshhanley** [comment]
@sajjadhossainshohagbd thanks for testing! Hmm yeah I have no idea what is causing that new error 🤔

**Pull request merged**
