### PR TITLE
Add Polyfill for Array.find and this.el.closest for ie11 support

### PR DESCRIPTION
**Pull request by rverrips**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?
Yes, #119 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No, all changes are polyfills needed for IE 11 support

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)
No

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.
Although currently polyfills support the onclick actions, more are needed when working with input fields in IE11

5️⃣ Thanks for contributing! 🙌
You're welcome - Happy to help where I can.

### CODE REVIEW

**Comment by rverrips** [comment]
I found I needed to add a "hydrate" method to all my Livewire components since v0.2 - Seems to be breaking phpunit tests for CI on this PR, but passes fine with v0.1.6 on my local environment.

**Comment by calebporzio** [comment]
Ah yes, sorry about that. The issue is fixed in v0.2.1

**Comment by rverrips** [comment]
Cool, could you return the Travis Build as it should work now ;)

**Comment by rverrips** [comment]
Thanks, tests all green after the fix in v0.2.1 - this PR is ready to rock ;)

**Comment by calebporzio** [comment]
Thanks Roy!

**Comment by lancepioch** [comment]
@all-contributors please add @rverrips for maintenance

**Pull request merged**
