### PR TITLE
Add loading state helpers to component class

### PR DESCRIPTION
**Pull request by jameslkingsley**
This is a small addition to the client-side component class, that'll let you control the loading state for a component. Particularly useful in custom directives or very specific use-cases where you just wanna say "hey this component is processing this thing".

Note: there's no special handling for resuming a loading state when Livewire re-renders the page. This is something the developer would need to cater for in their own implementation.

### CODE REVIEW

**Comment by joshhanley** [comment]
@jameslkingsley I think could come in handy! 

Can you give an example of how that would look in code to use?

Would this only work for Livewire actions/models or could you trigger Livewire's loading state say from Alpine while it was making an external API call or something?

**Comment by jameslkingsley** [comment]
It's available anywhere within a Livewire component.
All you need is the client-side component instance, which you can get a couple of ways:

**Using `$wire`**
```html
<div x-data>
  <button x-on:click="$wire.__instance.setLoading('foo')">Load</button>
  <span wire:loading wire:target="foo">Loading...</span>
</div>
```

**Using `el.__livewire`**
```html
<div wire:id="..." id="componentRootNode">
  <!-- document.getElementById('componentRootNode').__livewire.setLoading('foo') -->
  <span wire:loading wire:target="foo">Loading...</span>
</div>
```

**Comment by joshhanley** [comment]
@jameslkingsley thanks for that! It helps to be able to see possible implementations of it.

**Comment by calebporzio** [comment]
This is interesting. Because it adds extra maintenance and API surface area, I'm going to hold off until there's more demand for it. Thanks!

**Comment by stancl** [comment]
@calebporzio Maybe this could help with https://github.com/livewire/livewire/issues/2425?

Right now Livewire doesn't expose *any API at all* that would let the developer affect the loading states. If it did, I think devs could do:

```js
Livewire.hook('message.sent', (component, message) => {
    if (message.something) {
        component.setLoading('foo');
   }
})
```

**Pull request closed without merging**
