### PR TITLE
Update signature for UploadedFile::storeAs to match new Laravel signature

### PR DESCRIPTION
**Pull request by 27pchrisl**
This is a fix for the upcoming Laravel 10.x.

Laravel made the path argument optional in UploadedFile::storeAs in https://github.com/laravel/framework/commit/8d4741665f564cc8a3e15d823c0bb025a85324b4 causing errors in the subclass as this method needs the same update.

### CODE REVIEW

**Comment by joshhanley** [comment]
@27pchrisl thanks! Failing tests are unrelated. There was a breaking change in Laravel 9.46 which they are keeping, so we need to update our tests to match. Once I've done that, I will merge master into here are re-run the tests.

**Comment by driesvints** [comment]
@joshhanley what was the breaking change in 9.46?

**Comment by joshhanley** [comment]
@driesvints was a change to eloquent model decimal casts in this PR https://github.com/laravel/framework/pull/45492.

Now it won't round up on an overflow number. That PR doesn't feel right to me. But for our fix I've just added a version check to our tests and asserted the rounded down number, see our PR #5508 for details.

**Comment by driesvints** [comment]
Without reading everything, does Tim's new PR maybe bring back that functionality? https://github.com/laravel/framework/pull/45602

**Comment by joshhanley** [comment]
Closing this PR as these changes have been merged into PR #5507 so it retains @27pchrisl's contributions. Thanks @27pchrisl for this PR! 🙂

**Pull request closed without merging**
