### PR TITLE
[Fix] Two sets of links for one paginator morphdom issue

### PR DESCRIPTION
**Pull request by joshhanley**
This PR adds a fix for if you display two sets of pagination links for the one paginator on a page, for example if you have links above and below your table, raised in #1536 and #1582.

What is currently happening is morphdom is tripping up when there are two of them on the page due to them having the same `wire:key`, so each set of links needs its own identifier to pass into `wire:key`.

Laravel's paginator supports passing extra data to the view through the links method.

So I have added support for a property called `paginationKey` which can be passed in through the links method, like the below, and it will add it to the existing wire key in the pagination view.

```php
$posts->links(null, ['paginationKey' => 1]);
```

This ensures then if `$posts->links` is called twice, you can pass a different `paginationKey` into each one, which will keep morphdom happy.

Hope this helps!

Below is a screencast of the current issue with morphdom glitching.

recording (33)

### CODE REVIEW

**Comment by calebporzio** [comment]
Good stuff @joshhanley - I like this. However, is there a way to do this automatically? So that a dev doesn't have to experience a bug, dig around and eventually find this "paginationKey" solution.

Like can we assign a unique key or something?

This may lead to a bigger question: We should have a way to generate a random key for this blade stuff in Livewire that is only random for the first request, then subsequent requests it is the same.

I think I may hack on this.

**Comment by calebporzio** [comment]
After thinking about this a bit - providing a "Livewire aware random string generator" system would be pretty complex. I'd still like to explore it, but we should move on with this as if it doesn't exist.

Any ideas?

**Comment by joshhanley** [comment]
@calebporzio yep, I'm not a fan if it either.

I couldn't think of an elegant way to populate an automatic key that was different for each instance of links, but that didn't trigger morphdom replacing of each instance every time a request is made.

Simple solution is to just put `uniqid()` into the `wire:key` but that'd cause it to be wiped out each time due to the change of key.

A random string generator that runs on first request also wouldn't work if the paginated data/links aren't displayed on first render either.

So one possible thing is, for the multiple paginators on a page PR, you can manually pass the different pagination names into the paginator and get it back out using `getPageName`, so I was going to use that to ensure keys are unique for different paginator links.

Maybe there might be a way to override the links method so it internally tracks how many times links has been called or something as uses that as part of the key? Not ideal either though.

**Comment by calebporzio** [comment]
Mmmm yeah this is really tough. Decent ideas you've suggested The `->links()` is the most ideal from an API perspective, but not ideal from a maintenance one.

**Comment by joshhanley** [comment]
@calebporzio yeah exactly. So the paginator classes are not macroable, so it I think it would be too much maintenance nightmare to try and support overloading the links method.

That's why my thought was just to pass a key through links provided they need it. It would be no different that needing to put `wire:key` on things, which if you don't, can cause odd things to happen.

I also didn't want to call it `wire:key` as that is predetermined inside the paginator view as it sets different keys for different buttons, hence this was more just an identifier to distinguish different sets of pagination links.

**Comment by calebporzio** [comment]
@joshhanley 

I changed the implementation for this PR. If you hate it, just revert my commits.

I've switched to a strategy that doesn't require passing additional params to `->links(...)`

Instead, because every single render will render every single pagination link set, we can reliably store a property on the Livewire component instance that we can reference in `wire:key` AND increment before we use it each time.

I think this accomplishes our goal without developers having to do extra work.

I'll merge it for now, but again, feel free to back this out if you disagree.

**Pull request merged**
