### PR TITLE
Update Bootstrap pagination views

### PR DESCRIPTION
**Pull request by juliangarcess**
Review the contribution guide first at: https://livewire.laravel.com/docs/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Is needed to be the same that defaults at Laravel framework.

2️⃣ Did you create a branch for your fix/feature? (Main branch PR's will be closed)
`feature/update-bootstrap-pagination-views`

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
Only one change

4️⃣ Does it include tests? (Required)
Just visual changes, all test passing

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
I copied the laravel Bootstrap pagination view and adapted to livewire, because with the actual of livewire the total count was not showing.

> image
> before

>image
> after

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks for this, can you give me some more context around this? When did Laravel update these views? Will this be a breaking change for anyone? Does it use a newer version of bootstrap?

**Comment by joshhanley** [comment]
@juliangarcess If you merge main in, it should be fixed 🙂

**Comment by PerryvanderMeer** [comment]
@juliangarcess Browser tests are flacky and not related to your changes.

**Comment by calebporzio** [comment]
Great, thank you!

**Comment by dragonfly4** [comment]
@juliangarcess 

This merge was breaking custom changes I had implemented to add this missing feature. Thanks for the PR as it's now built-in.

Is there a reason why you have used different translation strings? My app is multilanguage and now it's always in English.

Laravel uses the pagination. prefix which is located under "lang\en\pagination.php"
Example
[                    <span class="page-link">{!! __('pagination.previous') !!}</span>](https://github.com/laravel/framework/blob/6c27ca43dbcfd232813ca5aba8ad3c80405ba9b1/src/Illuminate/Pagination/resources/views/simple-bootstrap-5.blade.php#L7)

Adding pagination. to the strings would allow people to translate this using the default Laravel file.
https://github.com/livewire/livewire/blob/0335b8f022ac535fc3cf29fd8a8fcb275353a470/src/Features/SupportPagination/views/bootstrap.blade.php#L45-L51

Happy to create a PR for this but since it's your work I prefer to give you first chance 😁

**Comment by dragonfly4** [comment]
My bad then. I'll wait for Laravel 11 and submit a PR.

**Comment by joshhanley** [comment]
@dragonfly4 It's generally safe to publish these as they rarely get changed. So I would just publish it and customise it to what you need.

**Pull request merged**
