### PR TITLE
Routeing.

### PR DESCRIPTION
**Pull request by jesseleite**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?

I can create an issue first if you wish.  Let me know bud.

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

I can separate the two file changes out into multiple PRs if you wish.  Let me know bud.

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)

I can write tests for these changes if you wish.  Let me know bud.

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.

Because I'm hoping you'll give me the opportunity to become one of the biggest livewire contributors ❤️

5️⃣ Thanks for contributing! 🙌

You are so welcome.

### CODE REVIEW

**Comment by jesseleite** [comment]
Tests even pass 🏄‍♂️

**Comment by calebporzio** [comment]
Haha, of course @jesseleite.... thanks!

**Comment by lancepioch** [comment]
@all-contributors please add @jesseleite for doc

**Comment by lancepioch** [comment]
@all-contributors please add @jesseleite for doc

**Comment by lancepioch** [comment]
@all-contributors please add @jesseleite for doc

**Pull request merged**
