### PR TITLE
[V3] Improved error message for setting a nested property to an unsupported value

### PR DESCRIPTION
**Pull request by julesgraus**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Yes. See https://github.com/livewire/livewire/discussions/6047

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes.

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
Yes. I've modified an existing test.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

Please see the detailed information over here: https://github.com/livewire/livewire/discussions/6047

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by julesgraus** [comment]
Notice: I've intentionally made the tests fail

**Comment by joshhanley** [comment]
@julesgraus thanks for the PR! Not sure why you've set the tests to fail, can you explain that? We prefer PRs tests to pass before we merge 😅

**Comment by julesgraus** [comment]
In version 2 you could do this:

```Livewire::test(YourComponent::class)->set('emails.0', 'test@example.org')```

This exact same code, fails in version 3. But the tests of version 3 that should cover this succeeds / passed, while it should not. So, I've modified the test, to match the situation I've encountered in my app. The situation that made me create this issue and pr.

I suspect we need to create 2 PR's. One that simply improves the error message like I did in this pull request. And one that resolves the actual issue. But I don't know IF it is an actual issue, or that I need to upgrade my code. In the latter part, we may need to address this issue when running ```livewire:upgrade``` I guess.

**Comment by joshhanley** [comment]
@julesgraus ah yep, understood. Can you change the existing test to back the way it was, and create a new test that fails covering the break, so we can investigate it? We prefer not to change existing tests where possible. Thanks!

**Comment by julesgraus** [comment]
Yes. Will do. Got to get some sleep right now since it is midnight already. Will do it when I get back from work tomorrow

**Comment by joshhanley** [comment]
@julesgraus no worries! Thanks, much appreciated 🙂 have marked this as draft for now

**Comment by calebporzio** [comment]
Thank you for this, however, I'm going to close it in the interest of keeping this part of the codebase a little cleaner (rather than passing that extra parameter all around) - again, thank you

**Pull request closed without merging**
