### PR TITLE
Move supported preview types to config

### PR DESCRIPTION
**Pull request by jimmypuckett**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?

Yes, it is here...

#1591 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

Nope

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)

Updated existing

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

Allow people to controll what they want to allow

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Hey @jimmypuckett, couple notes:

This makes sense, however:
* If we push this, it will fail because people already have published config files and updating this repo's config file won't automatically update theirs - you will need to provide a fallback as a "default" parameter in `config()->get()`
* I think this belongs in the upload subsection of the config as the last parameter as it strictly deals with that system and doesn't make sense to stand on it's own
* In your test, I would hardcode the expectation rather than loading it directly from the config file - less dynamicism in tests the better

Just some notes for you, thanks!

**Comment by jimmypuckett** [comment]
@calebporzio A few clarifications...

1) Good catch, I will address that.  (Have a question about the how, so please see below)
2) I toyed with that location, so I will move it
3) I almost put the array in here to not duplicate the array, but I wanted a single source of truth on the expected array.  I was concerend that someone would remember to change the config but not the test.

I can dupilcate the array in 1 & 3 or I can make 1 use the require from the configs like I do in the test.

Whcih do you prefer & I will make it so?

**Comment by calebporzio** [comment]
Yeah, so actually you can just remove the code you added to the tests, and ideally add a new test that tests that you can't preview a certain extension until you add it to the config.

**Comment by jimmypuckett** [comment]
OK, @calebporzio, I finally had some time to make those changes that you suggested.  Please let me know if there is anything else that you would like to see changed.  If/when this gets merged, then I will port it to the 2.x branch.

Thanks!

**Comment by calebporzio** [comment]
Thanks for this! This is perfect!

**Comment by calebporzio** [comment]
Also, no need to re-PR to master - already merged up.

**Pull request merged**
