### PR TITLE
Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty. due to two spaces in a class list

### PR DESCRIPTION
**Pull request by macbookandrew**
Review the contribution guide first at: https://livewire.laravel.com/docs/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

- wanted/needed? It’s a bugfix for existing behavior
- create a discussion? no, sorry…

2️⃣ Did you create a branch for your fix/feature? (Main branch PR's will be closed)

- yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

- no

4️⃣ Does it include tests? (Required)

- no…I don’t see any existing tests for this function or really any JS tests, so not quite sure where to put them

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

This fixes the following error I ran into when upgrading from v2 to v3:

Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

Given the following markup:

```html
<button
    class="block w-full rounded-md border border-transparent bg-brand-red-600 py-3 px-4 text-center text-base font-medium text-white shadow-sm hover:bg-brand-red-700 focus:outline-none focus:ring-2 focus:ring-brand-red-500 focus:ring-offset-2 focus:ring-offset-gray-50"
    type="submit"
    wire:loading.attr="disabled"
    wire:loading.class="bg-gray-400  hover:bg-gray-300 focus:ring-offset-gray-50 focus:ring-gray-600 cursor-not-allowed"
>
    Checkout
</button>
```

The `wire:loading.class` had two spaces between a couple of the class names. This results in the `classes` array looking like this:

```js
[ 'bg-gray-400', '', 'hover:bg-gray-300', 'focus:ring-offset-gray-50', 'focus:ring-gray-600', 'cursor-not-allowed' ]
```

and that throws the error.

Two spaces is unnecessary and a mistake in this case, but it’s also valid HTML so should be accepted IMHO 🤷🏻‍♂️ 

This change fixes the issue by simply filtering out empty strings

### CODE REVIEW

**Comment by joshhanley** [comment]
@macbookandrew thanks for the PR! Can you please add a test that covers this? Thanks!

**Comment by macbookandrew** [comment]
@joshhanley happy to, but…

> I don’t see any existing tests for this function or really any JS tests, so not quite sure where to put them

See bdc8d9508e7b09e47fffc8a64b63768fef0a814c for a stab at this. Let me know if you want changes to that.

I compiled the JS in 321e3d7634c8484845d0dee83aa0736cfe8683db, but there are over a dozen unrelated changes  🤷🏻‍♂️

**Comment by joshhanley** [comment]
@macbookandrew ah no worries. Legacy tests are the old tests so we don't update them. As the fix seems to be for `wire:loading` (even though the file is in a shared js folder), can you put it into `src/Features/SupportWireLoading/BrowserTest.php`? Also can you make sure to make a new test rather than modify existing tests?

Re the built assets, Livewire's assets were being build from Alpine's main branch rather than a tagged Alpine release due to new changes. Caleb has just tagged a new release of both, so if you merge in Livewire's main branch you should be able to rebuild the assets without as many changes.

Thanks!

**Comment by macbookandrew** [comment]
@joshhanley thanks! Wow…I totally skipped over much of [this section](https://livewire.laravel.com/docs/contribution-guide#add-failing-tests) 🤦🏻‍♂️

**Comment by joshhanley** [comment]
@macbookandrew no worries! 🙂 Ah, all good

**Pull request merged**
