### PR TITLE
Remove `rel` attribute from button

### PR DESCRIPTION
**Pull request by utsavsomaiya**
This is reopened as I have seen that @calebporzio missed something.

Sorry for interrupting.

Here is the reference : https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

### CODE REVIEW

**Comment by joshhanley** [comment]
@utsavsomaiya please edit this PR description to include your findings, so Caleb doesn't need to go digging 🙂

**Comment by joshhanley** [comment]
This PR is reopened PR #7536.

**Comment by lrljoe** [comment]
Just a note that rel attribute is only used when href is present, and using on "button" elements isn't supported, so makes sense to remove it.

**Comment by utsavsomaiya** [comment]
> Just a note that rel attribute is only used when href is present, and using on "button" elements isn't supported, so makes sense to remove it.

Yupp!! Thanks

**Comment by calebporzio** [comment]
Sounds good, thanks for pushing this back up!

**Pull request merged**
