### PR TITLE
Fix `wire:navigate` for manually triggered click events

### PR DESCRIPTION
**Pull request by gehrisandro**
This PR fixes the problem that manually triggered click events on links with `wire:navigate` are currently ignored.

A more detailed description of the problem can be found here: https://github.com/livewire/livewire/discussions/6341

### CODE REVIEW

**Comment by calebporzio** [comment]
Would this trigger "two" firings of the wire:navigate? one for the click you added and one for the mousedown listener?

**Comment by gehrisandro** [comment]
@calebporzio I'm don't hope so. But I have to check this.

**Comment by gehrisandro** [comment]
@calebporzio As far as I was able to test everything looks fine to me. No duplicated events.

**Comment by calebporzio** [comment]
Ok sounds good. Thanks!

**Comment by gehrisandro** [comment]
@calebporzio Thanks for merging and your awesome and inspiring work 🎉

**Comment by calebporzio** [comment]
Sorry @gehrisandro - I reverted this because it was causing most tests to fail in the main branch. I'm happy to merge another PR if some of those issues are addressed. Thanks!

**Pull request merged**
