### PR TITLE
[v3] Add failing test for input reset

### PR DESCRIPTION
**Pull request by krekas**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

4️⃣ Does it include tests? (Required)

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by devajmeireles** [comment]
As per my review, the test `src/Features/SupportFormObjects/BrowserTest.php` doesn't make sense.

- You are trying to reset a property that initially contains the value as `This is a title`
- After resetting, you expect the value to be empty, but the correct thing is that the value is `This is a title`, [since the property reset consist on reset the property value to the initial state.](https://livewire.laravel.com/docs/forms#resetting-form-fields)

**Comment by krekas** [comment]
@devajmeireles yes good point. Updated test

**Comment by devajmeireles** [comment]
I found the problem. This PR https://github.com/livewire/livewire/pull/6118 will solve this. As per my review I think you need to abstract your PR for a new one only related with lifecycle hooks to the properties.

**Comment by joshhanley** [comment]
@krekas thanks for the PR!

I'm not sure I follow exactly, one test uses `->reset()` and the other test doesn't, but this is meant to be testing `->reset()` right? Also he first test, in `SupportFormObjects\BrowserTest`, doesn't actually have a FormObject in it so either you need to add one or that's the wrong place for the test.

The first test is failing because you're using `->input()` which Livewire doesn't support. Try changing that to `->type('@title', 'This is a title')` and it will probably pass.

Can you update and let me know when done?

Also can you provide me a component class and view with instructions that I can use locally to test your issue?

Thanks!

**Pull request closed without merging**
