### PR TITLE
Added assertions to TestView

### PR DESCRIPTION
**Pull request by nuernbergerA**
Currently `assertSeeLivewire()` only works for `TestResponse`

```php
$this->get('/some-url')->assertSeeLivewire('awesome-livewire-component');
```

But is also possible to [test blade components](https://github.com/laravel/framework/pull/32601/files)

So this PR adds the assertions to `TestView`
```php
$this->component('some-blade-component')->assertSeeLivewire('awesome-livewire-component');
```

The Assertion will be available on `blade()`, `component()` and `view()` in Laravel `TestCase` class

---
https://laravel.com/docs/8.x/http-tests#testing-views

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks @nuernbergerA . Can you undo you "Assertions" abstraction? Otherwise this is looking good.

**Comment by nuernbergerA** [comment]
@calebporzio do you really want to have the block duplicated so often?

**Comment by calebporzio** [comment]
Yes, for now

**Comment by nuernbergerA** [comment]
@calebporzio done

**Comment by calebporzio** [comment]
Thanks!

**Pull request merged**
