### PR TITLE
[V3] Return null on IntSynth when null is passed in

### PR DESCRIPTION
**Pull request by ejonasson**
The `IntSynth` in Livewire V3 adds the ability to convert an empty string that's passed into the synth to `null`. This is great on the frontend (since a form input will generally return `''` instead of `null`, but there are still scenarios where `null` might be returned. For example, in a unit test (as demonstrated in the test on this PR), or when updated though Javascipt.

This PR just makes sure we pass though that `null` value in those cases, as opposed to passing it to the `int` cast, which converts it to `0`. 

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Did not create a discussion, but an explanation is included above.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
The only changes are to the `IntSynth` class, and adding a test for that Synth.

4️⃣ Does it include tests? (Required)
Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
Included above :)

### CODE REVIEW

**Comment by joshhanley** [comment]
@ejonasson thanks for the PR! I just pulled it down, and commented out your fix and the test still passes. Can you confirm the same happens for you?

**Comment by joshhanley** [comment]
@ejonasson actually don't worry, I managed to fix it 🙂

**Comment by ejonasson** [comment]
@joshhanley Oops, sorry about that. Thank you for fixing!

**Comment by calebporzio** [comment]
Thank you!

**Pull request merged**
