### PR TITLE
Failing test for can't set model as property if it hasn't been persisted yet

### PR DESCRIPTION
**Pull request by riasvdv**
This adds a failing test for #6120 - "Can't set model as property if it hasn't been persisted yet" when component deletes model

I've used actual eloquent with sqlite here with inline table creation as you can't delete models with Sushi as far as I know.

### CODE REVIEW

**Comment by riasvdv** [comment]
This had some conflicts so I've re-applied the failing test to the latest main branch

**Comment by masterix21** [comment]
Works If you remove lines 20-22 from https://github.com/livewire/livewire/blob/266c356a11d584dc95961a7cf0737e33f7b80a06/src/Features/SupportModels/ModelSynth.php#L20-L22

Anyway, I don't know if it could be the solution.

**Comment by 3alampro** [comment]
i'm using the same controller to edit and create new model by using optional route model binding. but with this Exception i can't use it like v2

**Comment by joshhanley** [comment]
@riasvdv thanks for the PR! I'm going to close this in favour of PR #7003 which includes a fix. I have merged in PR #6858 which was similar to this one but uses Sushi.

**Pull request closed without merging**
