### PR TITLE
Laravel v10 Support

### PR DESCRIPTION
**Pull request by driesvints**
This PR adds Laravel v10 support. We'll need this to update Jetstream: https://github.com/laravel/jetstream/pull/1216

Depends on:

- [x] https://github.com/calebporzio/sushi/pull/109

### CODE REVIEW

**Comment by joshhanley** [comment]
@driesvints thanks! I'll get Caleb to have a look at the Sushi PR

**Comment by driesvints** [comment]
Cool, we already got most of it done, just one failure left.

**Comment by joshhanley** [comment]
Laravel 10 tests we're failing due to newer updates/fixes to the recent rounding changes in Laravel merged into L10. So I've updated version comparisons in our tests to not include any newer Laravel 9 versions or greater.

See https://github.com/laravel/framework/pull/45602

**Comment by driesvints** [comment]
Thanks @joshhanley!

**Pull request merged**
