### PR TITLE
Add assertions to check if properties and actions are bound / used in a components view

### PR DESCRIPTION
**Pull request by julesgraus**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Yes. See #5599 

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes.

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
Yes. For everything I've added.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
See #5599 for the description and reasons. Also see the tests to see how you could use [the new assertions](https://github.com/julesgraus/livewire/blob/feature/makes-assertions-on-view-trait/tests/Unit/TestableLivewireViewBindingsTest.php). 

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@julesgraus oh, I just saw this! I replied on your discussion a few minutes ago. Have a look at this package, I believe it adds what you're after https://github.com/christophrumpel/missing-livewire-assertions

**Comment by julesgraus** [comment]
Ok that's very nice. But why not have such feature merged into this Livewire package itself? Since I am at least the second one who has found out it may be handy, I think it should be part of Livewire itself.

**Comment by joshhanley** [comment]
@julesgraus I'm not saying it shouldn't. I was just providing another possible solution to use straight away (the comment was probably more relevant for the discussion when this PR didn't exist) 🙂 

Just an FYI, at the moment we're limiting features added to V2 while we work on V3, so it may not get added in now. But that's up to Caleb to decide.

**Comment by julesgraus** [comment]
@calebporzio Are you interested in this code for version 3? If so, I will make one. Just tell me if I need to change something. I use it all the time.

**Comment by joshhanley** [comment]
@julesgraus Caleb probably won't see this, but I noticed he forgot to add a comment when he closed this PR like he did the others. See his message below:

Thank you for your contributing to Livewire. Your efforts are much appreciated.

We are declaring "Livewire PR bankruptcy:" closing all outstanding pull requests to start fresh with a clean slate.

If you think this is too heavy-handed and your PR is important, please re-open it against the v2 branch.

Thanks!

**Pull request closed without merging**
