### PR TITLE
Fix Safari special character encoding issue

### PR DESCRIPTION
**Pull request by bobwurtz**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

Yes - there is an existing [pull request](https://github.com/livewire/livewire/pull/4613) that was closed because it did not include a test. I could not contribute to that branch so I copied the fix for the special character issue provided by [jonneroelofs](https://github.com/jonneroelofs) and added a test.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No

4️⃣ Does it include tests? (Required)

Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

This would fix a common issue with Safari handling special characters differently than Chrome.

```
            if (
                // The value is a supported type, set it in the data, if not, throw an exception for the user.
                is_bool($value) || is_null($value) || is_array($value) || is_numeric($value)
            ) {
                data_set($response, 'memo.data.'.$key, $value);
            } else if(is_string($value)) {
                data_set($response, 'memo.data.'.$key, \Normalizer::normalize($value));
            }
```

The `is_string` check is moved to a separate if statement and normalized.

This is my first time contributing to an open-source project so please let me know if I did anything wrong or if there is something I should do differently in the future. Thanks!

### CODE REVIEW

**Comment by joshhanley** [comment]
@bobwurtz thanks for the PR! Just to confirm, we will need to run this test in Safari is that correct?

**Comment by bobwurtz** [comment]
@joshhanley Yes, the test needs to run in Safari. There's no issue on Chrome.

**Comment by joshhanley** [comment]
@bobwurtz yep, thanks! We'll make sure we run it in Safari 🙂

**Comment by bobwurtz** [comment]
@joshhanley I see that these tests are failing and it looks like it has something to do with trying to test in Safari. Is there something I should change about the test that I wrote?

**Comment by joshhanley** [comment]
@bobwurtz hmm strange. Also for some reason I can't re-run the tests. Any change you could push an empty commit to re-trigger the tests incase it was just an issue with GH actions?

Thanks!

**Comment by bobwurtz** [comment]
@joshhanley I just pushed an empty commit. I see a message after pushing the commit that says `First-time contributors need a maintainer to approve running workflows.`

**Comment by joshhanley** [comment]
@bobwurtz thanks! I've triggered the tests to run 🙂

**Comment by bobwurtz** [comment]
@joshhanley the jobs still did not complete. The error reads:

```

There was 1 error:
1) Tests\Browser\StringNormalization\Test::test
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"safari"}]},"desiredCapabilities":{"browserName":"safari","platform":"ANY"}}
Failed to connect to localhost port 9515: Connection refused
```

Is there something I need to change about the job?

**Comment by joshhanley** [comment]
@bobwurtz ah, what that is, is the fact that you have `public static $useSafari = true;` in the test.

You need to remove that, as GitHub Actions doesn't have Safari to test in.

We use that flag manually, locally, to test with Safari when there is a Safari specific fix.

Hope this helps!

**Comment by bobwurtz** [comment]
@joshhanley Oh that makes sense now. I just removed it so everything should run smoothly now. Thanks for the help!

**Comment by joshhanley** [comment]
@bobwurtz ok thanks! Have triggered tests to run again 🙂

**Comment by danvanwijk** [comment]
Encountered this issue myself now. Thanks for pointing out a solution.

**Comment by stefanocurnis** [comment]
wow. thank you! lost 1 week on this one. hope it gets merged soon. I'm unable to use livewire with iOS / Safari and non-english languages.

**Comment by stephane-monnot** [comment]
Thank you ! 

@joshhanley Do you plan to create a new tag soon ? I really need this fix.
Thanks

**Comment by joshhanley** [comment]
@stephane-monnot we're just finalising another PR first before looking at tagging a release 🙂 you can install this already using `dev-master` if you need it now.

**Pull request merged**
