### PR TITLE
Fix not being able to set values on specific numerical indexes of array attributes of models

### PR DESCRIPTION
**Pull request by iksaku**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?
Previously created an issue: #1667 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
Straight to the neck... Ermm... Implementation...

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)
Yup, tests where added to ensure it is not broken in the future.

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.
Mostly, what #1667 says.

If your model contains an array of arrays on which you would like to `wire:model` a specific index, validation would fail, even if your rules are properly set as arrayable (`model.attribute.*.nested`).

This is an attempt to fix that.

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by erikgaal** [comment]
I think we need another test for the case where the key of property that's going to be set is _ending_ with an index, e.g. `foo.zap.0`. This would be so when the items of the array aren't `objects`, but `strings` or other primitives.

```php
Livewire::test(ComponentForEloquentModelHydrationMiddleware::class, [
    'foo' => $foo = Foo::first(),
])  ->set('foo.zap.0', 'glob')
    ->call('save')
    ->assertHasErrors('foo.zap.*')
    ->set('foo.zap.0', 'globbbbb')
    ->call('save')
    ->assertHasNoErrors();

    $this->assertEquals(['globbbbb'], $foo->fresh()->zap);
}

/* ... */

protected $rules = [
    ...,
    'foo.zap.*' => 'required|min:5',
]
```

**Comment by iksaku** [comment]
@erikgaal thanks for the heads up! Let me push another commit for this 😄

**Comment by calebporzio** [comment]
Thanks, I'll wait for that next commit before merging.

**Comment by iksaku** [comment]
All ready to go @calebporzio :wink:

**Comment by calebporzio** [comment]
Thanks @iksaku & @erikgaal !

**Pull request merged**
