### PR TITLE
Wireable Image Dehydration in SupportFileUpload

### PR DESCRIPTION
**Pull request by stevenmond**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?
This was mentioned as part of https://github.com/livewire/livewire/pull/4036

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No, although I incorporated the code change from https://github.com/livewire/livewire/pull/4239 into this and added a test for the fix it added.

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)
Yes

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.
```SupportFileUploads``` isn't checking for ```Wireable``` objects when ```dehydratePropertyFromWithFileUploads``` is called. As a result, any images that are on ```Wireable``` objects are not serialized at that time. Later on, images serialized as ```{"disk":"public"}``` rather than as ```livewire-file[s]:``` since the disk property is the only public property on ```TemporaryUploadedFile```. This is the same result as running a ```json_encode``` on ```TemporaryUploadedFile```.

 This fix iterates through all the keys on the ```Wireable``` object checking for ```TemporaryUploadedFiles``` and updating the value as appropriate.

Hydration seems to work out of the box from what I've seen and didn't require any changes.

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@stevenmond should we mark this as a draft for now, and if #4239 gets merged then we will rebase this onto master and then mark it as ready?

**Comment by joshhanley** [comment]
@stevenmond yeah that'd be preferred if you can keep it independent.

But if you could share your test code on that PR so they can add it, that would be much appreciated! 🙂

**Comment by stevenmond** [comment]
@joshhanley Updated as requested. Will share test code to #4239's PR.

**Comment by joshhanley** [comment]
@stevenmond thanks!

**Comment by calebporzio** [comment]
Ok, merged the other PR - will merge this once the conflicts are resolved and everyone's happy with it. Thanks!

**Comment by stevenmond** [comment]
@joshhanley I've resolved the conflicts with the test that were committed as part of #4239. Let me know if there is anything else you need me to do on my end.

**Comment by joshhanley** [comment]
@stevenmond thanks! All looks good to go.

**Comment by calebporzio** [comment]
Great, thanks!

**Pull request merged**
