### PR TITLE
Fix `livewire:navigated` not fired on first page load

### PR DESCRIPTION
**Pull request by iksaku**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
No

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
It is stated in the docs that relying on the `DOMContentLoaded` for your scripts is incompatible when using `wire:navigate` feature, instead, it is recommended to rely on `livewire:navigated` (alias for `alpine:navigated`) for scripts that require interacting with the page once the page is fully loaded.

This behavior was broken on commit 310c92c9e67134a06a86fc086838423ee290de47.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by levu42** [comment]
@iksaku are you potentially confusing `livewire:navigated` and `alpine:navigated` in the title of the PR? In #6490 I wrote that `alpine:navigated` is fired on first load, but `livewire:navigated` is not. Your tests are also testing `livewire:navigated`.

**Comment by iksaku** [comment]
@levu42 You're right, I confused the event names, let me fix that. Thanks!

**Comment by joshhanley** [comment]
@iksaku thanks for the PR! It was removed as it was causing navigate to be used for all page changes regardless of if they were using `wire:navigate` or not. Not sure if you have managed to fix that issue, but there is a related failing test, if you could have a look at that? Thanks

image

**Comment by levu42** [comment]
@joshhanley while `livewire:navigated` isn't fired on the first page load, the documentation should at least be updated, it currently says:

>When using wire:navigate, DOMContentLoaded is only fired on the first page visit, not subsequent visits.
> 
> To run code on every page visit, swap every instance of DOMContentLoaded with livewire:navigated:
> 
> [...]
> 
> Now, any code placed inside this listener will be run on the initial page visit, and also after Livewire has finished navigating to subsequent pages.

**Comment by joshhanley** [comment]
@levu42 actually, the docs are correct. As mentioned above, there was a big bug caused by the way it was implemented. It was temporarily removed to stop navigate running for every link in every app. But it would be better if a solution can be found to get it all to run happily as documented 🙂

**Comment by iksaku** [comment]
Closing in favor of #6699

**Pull request closed without merging**
