### PR TITLE
Add a way to bail out of property updates

### PR DESCRIPTION
**Pull request by jameslkingsley**
This is a backdoor for cancelling a property update by just returning `false` in the `updating()` hook.

Addresses https://github.com/livewire/livewire/discussions/2349

### CODE REVIEW

**Comment by joshhanley** [comment]
I think this could be useful as there are situations where validation can't even run due to type casting errors.

For example, in issue #1672 if you have an input that is bound to a model property that is cast to a carbon instance, and a user has entered a string into the input field, then you get a carbon parse error.

It would be nice to find a way to run validation against the value of a property to be updated before actually gets applied, and cancel the update if it fails, like in this PR.

I think this PR is only part of the story though, as the example in #2349 validation wouldn't actually work, as the validation runs against the value of the property, not the incoming change, hence why validation is typically run in an `updated` hook rather than `updating`.

I know a manual validator could be used in updating instead, but it would be handy if there was a way to use the components in rule/s but run against the update value.

There are also some other instances where this might be useful if there are multiple updates coming from the front end in the same request, whether it be due to defer or alpine triggering a couple of updates simultaneously, that you may want to cancel some of the changes. I can provide some examples of this if need be.

Hope this helps!

**Comment by jameslkingsley** [comment]
> It would be nice to find a way to run validation against the value of a property to be updated before actually gets applied

The way I've handled this so far:
```php
public function updating($attribute, &$value)
{
    // $value is passed by reference so we can modify it before it's used by Livewire
    $value = 'something else';
}
```

**Comment by stancl** [comment]
Does this work with `updatingFoo()`?

**Comment by jameslkingsley** [comment]
Now it does 😉

**Comment by calebporzio** [comment]
This makes a lot of sense to me, is this a breaking change though?

**Comment by stancl** [comment]
I think it should be fine with `=== false`. Sure, someone might return `null` from an updating hook to return early, but if you're specifically returning `false` from it, you're probably looking for this behavior.

**Comment by calebporzio** [comment]
Yeah, I think I agree @stancl, @jameslkingsley ?

**Comment by jameslkingsley** [comment]
Yeah I agree. I'm gonna push some tests btw.

**Comment by joshhanley** [comment]
@jameslkingsley yeah I'm not sure about the traits handling, but the rest looks good 🙂

I'd imagine if one of the traits returned false, that the rest of the update is cancelled (including other traits), instead of continuing to loop through the other traits before finally returning false. Same for the dispatch of the listeners.

Keep in mind, that if you "cancel" an update, it will only be for that particular property that is being updated. So if you had batched updates, and say returned false for the first property update (as such was cancelled), the second property update will start from the beginning, running through all update methods and traits.

Hence why I think if a trait returns false, then just to stop the update there instead of running through the rest of the traits.

What do you think?

**Comment by jameslkingsley** [comment]
Yeah that makes a lot of sense, also simplifies the implementation

**Comment by jameslkingsley** [comment]
Made it an opt-in thing internally. `dispatchStrict()` will return early if one of the listeners returns `false`. Open to better method name.

**Comment by joshhanley** [comment]
> Does it matter that the early exit will happen for other events though? `LivewireManager::dispatch` might not run all listeners if one of them returns `false`. Quite a hard to spot bug.

@jameslkingsley I had that first thought too, but actually when you follow it through, it will only run through listeners with that exact event name `'component.updating'` for example.

```php
foreach ($this->listeners[$event] ?? [] as $listener)
```
So it shouldn't block any other events 🙂  does that sound right to you?

Probably don't need the `dispatchStrict` in that instance if I'm following it correctly.

**Comment by jameslkingsley** [comment]
I mean for other events that are dispatched with the `dispatch` method.

**Comment by calebporzio** [comment]
Sorry for the lag on this. I like this addition. Not sure about adding "dispatchStrict" - is there an implementation that doesn't add any extra API, but adds this behavior? Closing this, but please resubmit with the changes and I'll pull in. Thanks!

**Pull request closed without merging**
