### PR TITLE
[V3] Failing test: wire:loading with JS object

### PR DESCRIPTION
**Pull request by danharrin**
Imagine you have a button:

```html
<button wire:click="foo(@js(['bar' => 'baz']))"></button>
```

Both of these indicators will show, even though only the first should:

```html
<span wire:target="foo(@js(['bar' => 'baz']))" wire:loading>Loading</span>
<span wire:target="foo(@js(['baz' => 'bar']))" wire:loading>Loading</span>
```

I think that the JS inside the `wire:target` needs to be evaluated in a similar way to `wire:loading` to ensure that the params are matched exactly.

### CODE REVIEW

**Comment by calebporzio** [comment]
@danharrin - have you looked into the cause of this problem at all?

**Comment by zepfietje** [comment]
@danharrin, just reminding you to reply to Caleb so we can maybe have a fix in place before releasing Filament v3 Tuesday. 🙂

**Comment by calebporzio** [comment]
Lol, fixed it

**Comment by zepfietje** [comment]
Thanks a lot, @calebporzio!

**Comment by danharrin** [comment]
Thanks so much Caleb! Super busy with everything else, sorry for not getting back in time

**Pull request merged**
