### PR TITLE
Removed a reference to a parameter that is not used in the example.

### PR DESCRIPTION
**Pull request by julesgraus**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Yes. Because the documentation isn't correct. I did not create a discussion because I think it is such small change that it would be overkill

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
No. Not applicable.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

The documentation tells you that the example contains a message and style parameter. But it only contains a message parameter. I just fixed the text to match the example.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@julesgraus thanks for the PR! I think it would be better to add the style parameter, which demonstrates the testing of multiple parameters, instead of removing it from the text. Maybe set it to `style: 'success'`? Thoughts?

**Comment by julesgraus** [comment]
@joshhanley Agree. I first created a pull request that did exactly that that was merged in yesterday. 

See [commit](https://github.com/livewire/livewire/pull/5909/commits/43607d9f01f2325a7d3856d1ad7ca60d1137600b) of my previous [PR](https://github.com/livewire/livewire/pull/5909). 

But Caleb removed that in commit https://github.com/livewire/livewire/commit/f0272e2e65d9a6946b258ac0f006764fdc49b57b

**Comment by joshhanley** [comment]
@julesgraus I suspect it's because you changed the example to be too specific and potentially too complicated (using an enum). But maybe just leave it the way it is then, I will get Caleb to have a look and he can decide which he'd prefer 🙂

**Comment by julesgraus** [comment]
Yeah I can see that perspective too. And I can agree with that perspective too. Non the less, we need to fix it one direction or the other.

**Comment by calebporzio** [comment]
Ooops thanks! Exactly what @joshhanley said

**Pull request merged**
