### PR TITLE
setup github actions workflow for tests

### PR DESCRIPTION
**Pull request by faustbrian**
1️⃣ Is this something that is wanted/needed? Did you create a feature-request issue first?
Probably. No.

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No.

3️⃣ Does it include tests if possible? (Not a deal-breaker, just a nice-to-have)
No.

4️⃣ Please include a thorough description of the feature/fix and reasons why it's useful.
Run tests every time something is pushed. See https://github.com/faustbrian/livewire/commit/88afcf2f2408a6080bdaa4638d342e7882c1d30b/checks?check_suite_id=347145091 for what jobs it runs.

5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Awesome, was literally going to do this myself today.

**Comment by calebporzio** [comment]
@faustbrian  - mind looking into why the action isn't working? (if you need some permissions I can give them to you)

**Comment by faustbrian** [comment]
Hmm, should be working on any pushes and merges. They ran fine on my fork but I'll have a look later today.

**Comment by faustbrian** [comment]
@calebporzio https://github.com/livewire/livewire/pull/406 seems to be working, the jobs are running and all green again.

**Comment by calebporzio** [comment]
Nice, it looks like you're right. Everything's good. Thanks!

**Comment by lancepioch** [comment]
Already a contributor, 🌟

**Pull request merged**
