### PR TITLE
Add failure test when using wire:model together with x-mask

### PR DESCRIPTION
**Pull request by luanfreitasdev**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
https://github.com/livewire/livewire/discussions/7100

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

Livewire binds the value before the mask is applied when a mask is added to an input with a wire:model.
You can see the issue by accessing: https://wirebox.app/b/4j29y.
We can set a timeout for the dataset to make sure that the value is only returned after the mask has been applied.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
ok I see the problem here, I think the solution is to change x-mask to override input events so that they are only fired after x-mask has already changed the input. Right? or do you think that would cause unwanted side effects in some way - it seems the cleanest and most robust to me though

**Comment by clinvest** [comment]
Hi, same problem here, using the mask feature through filamentphp: https://github.com/filamentphp/filament/issues/10694

**Comment by kismonguz** [comment]
> Hi, same problem here, using the mask feature through filamentphp: [filamentphp/filament#10694](https://github.com/filamentphp/filament/issues/10694)

If you using money formatter, it will also mess up the thousand separator.

**Comment by calebporzio** [comment]
Thanks for the report and failing test - I was able to identify and fix it on the Alpine side.

Here's the alpine PR: https://github.com/alpinejs/alpine/pull/3988

This fix will be included in the next release.

**Pull request closed without merging**
