### PR TITLE
Deeply nested models with relationships cannot hydrate

### PR DESCRIPTION
**Pull request by ryatkins**
Binding directly to a nested model relationship does not render data in the browser or allow the model to be updated.

I've tried every example of wildcard dot notation, but haven't been able to figure out the code so I have provided a test and example data

Example: 
`'users.*.items.*.title' => 'required',`

`$this->users = User::with('items')->get()`

[Related issue #1886](https://github.com/livewire/livewire/issues/1886)

I believe this is happening in HydratePublicProperties@hydrateModels:

`$fullModelData` looks like this coming in
```
array:3 [▼
  "id" => 3
  "name" => "Mark"
  "items" => array:3 [▼
    0 => array:4 [▼
      "id" => 6
      "title" => "Lawn Mower"
      "price" => "226.99"
      "user_id" => "3"
    ]
    1 => array:4 [▶]
    2 => array:4 [▶]
  ]
]
```

`$filteredModelData looks like this going out`
```
array:3 [▼
  0 => array:1 [▼
    "items" => []
  ]
  1 => array:1 [▼
    "items" => []
  ]
  2 => array:1 [▼
    "items" => []
  ]
]
```

### CODE REVIEW

**Comment by joshhanley** [comment]
@ryatkins so I have had a dig into this, and there is two different factors stopping this from working at the moment.

One is eager loaded relations are not being restored for collections after re-hydration. I have a fix for this, that I was trying to get into Laravel https://github.com/laravel/framework/pull/35720 (I think it might need to wait until Laravel 9 though), but Caleb is happy to support it here short term, so I will PR a fix soon once I've written some tests to ensure it's all sound.

The other is the collections dehydration and rehydration doesn't support support deep nesting. I experimented with a recursive function this morning to dehydrate the collection correctly (and got it all working), but need to do the same for rehydration.

@calebporzio if you are happy to support deep nesting, I can keep going and get the rehydration running and submit a PR.

**Comment by ryatkins** [comment]
@joshhanley - Thanks for the update.  I've run into this issue as well on the Laravel side and getting this into Laravel core would be amazing.

**Comment by calebporzio** [comment]
@joshhanley - yeah, I think I'm down for deep collection nesting support, yeah - as long as it doesn't add too much meta data to the payload.

**Comment by calebporzio** [comment]
Also you're the man @joshhanley for tackling these beasts

**Comment by calebporzio** [comment]
Also, Also, thanks @ryatkins for the helpful failing test PR - makes things easier for people to contribute the fix!

**Comment by joshhanley** [comment]
@ryatkins ok I've finally submitted the PR for the first part of the issue regarding eager loaded relations, see PR #2386.

**Comment by calebporzio** [comment]
Ok, just merged @joshhanley's PR. What is part 2 of this issue? (refresher please?)

**Comment by joshhanley** [comment]
@calebporzio part two, is the actual deep nesting support (in `HandlesActions`). I have a draft working for collections, but it has some edges I need to work through first and to add some more tests. But Ryan tested it and he said it works well!

You can probably close this PR as I have pulled Ryans commit into my branch. 

As it is a deeper issue, would you prefer if I submit a draft PR so you can review the progress on it (to make sure it's how you'd like) or just wait until it's done and open a full PR?

**Comment by calebporzio** [comment]
Ok thanks for the info @joshhanley, I'll close this then.

Up to you re: draft or not draft.

Thanks a ton for your attention on these deep issues! You're the man!

**Pull request closed without merging**
