### PR TITLE
Utilize Laravel's Container for Dependency Resolution in LivewireServiceProvider

### PR DESCRIPTION
**Pull request by Omranic**
This pull request updates the LivewireServiceProvider class to utilize Laravel's container for resolving dependencies and instantiating objects, improving modularity and flexibility for app developers. With this change, developers can easily override core Livewire functionalities in their service providers as needed, such as Mechanisms and Features.

These changes have been made with the aim of maintaining backward compatibility and ensuring that there are no side effects or incompatibilities.

-----

Code snippet of the improvement and reasons why it's useful:

```php
namespace App;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton(\Livewire\Mechanisms\HandleRequests\HandleRequests::class, \App\HandleRequests::class);
    }
}
```

Example of a `HandleRequests` Mechanism override, changing the mechanism boot logic. This is just an example, but there's many other use cases.
```php
namespace App;

use Livewire\Mechanisms\HandleRequests\HandleRequests as BaseHandleRequests;

class HandleRequests extends BaseHandleRequests
{
    function boot()
    {
        // ...
    }
}

```

Thanks for your consideration! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
This is fantastic - will be extremely powerful for people who are willing to roll up their sleeves, thanks!

**Comment by isaacdew2** [comment]
@calebporzio @Omranic I've updated my Laravel instance to the latest and it seems this change broke registering component aliases via the Livewire facade. For example, Jetstream components such as `navigation-menu` that are registered in the service provider are throwing a `ComponentNotFoundException`. I've reverted the changes in this commit and it's able to find the Jetstream `navigation-menu` component again.
Screenshot 2023-10-17 at 1 30 55 PM
Screenshot 2023-10-17 at 1 32 33 PM

**Comment by andrewdwallo** [comment]
This caused many issues in my application as well. All registered components could not be found.

**Comment by CyberPunkCodes** [comment]
I also am having issues with 3.0.9

I am not familiar with the new Github layout to follow the history well, but I also was leaning on the recent changes in the service provider being the issue.

I have also created a bug discussion: #7093

**Comment by Omranic** [comment]
Thanks @andrewdwallo & @CyberPunkCodes, I was able to reproduce this issue on a new Jetstream installation, however I'm still investigating why this is happening. Here's my initial findings:

Before this commit, IoC container resolved services shows the following order:

```php
Illuminate\Foundation\Application {[#2 ▼](http://project2.default.test/dashboard#sf-dump-1350046153-ref22) // vendor/livewire/livewire/src/LivewireServiceProvider.php:79
  #resolved: array:30 [▼
    "events" => true
    "router" => true
    "App\Http\Kernel" => true
    "Illuminate\Contracts\Http\Kernel" => true
    "Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables" => true
    "Illuminate\Foundation\Bootstrap\LoadConfiguration" => true
    "Illuminate\Foundation\Bootstrap\HandleExceptions" => true
    "env" => true
    "Illuminate\Foundation\Bootstrap\RegisterFacades" => true
    "Illuminate\Foundation\PackageManifest" => true
    "Illuminate\Foundation\Bootstrap\RegisterProviders" => true
    "Livewire\LivewireManager" => true
    "Livewire\EventBus" => true
    "Livewire\Mechanisms\PersistentMiddleware\PersistentMiddleware" => true
    "Livewire\Mechanisms\HandleComponents\HandleComponents" => true
    "Livewire\Mechanisms\HandleRequests\HandleRequests" => true
    "Livewire\Mechanisms\FrontendAssets\FrontendAssets" => true
    "Livewire\Mechanisms\ExtendBlade\ExtendBlade" => true
    "files" => true
    "Livewire\Mechanisms\ComponentRegistry" => true
    "blade.compiler" => true
    "Livewire\Mechanisms\CompileLivewireTags" => true
    "Livewire\Mechanisms\RenderComponent" => true
    "Livewire\Mechanisms\DataStore" => true
    "Spatie\Ignition\Contracts\ConfigManager" => true
    "log" => true
    "Illuminate\Foundation\Bootstrap\BootProviders" => true
    "db.factory" => true
    "db" => true
    "view.engine.resolver" => true
  ]
```

After this commit, IoC container resolved services shows a different order:

```php
Illuminate\Foundation\Application {[#2 ▼](http://project2.default.test/dashboard#sf-dump-1285719654-ref22) // vendor/livewire/livewire/src/LivewireServiceProvider.php:79
  #resolved: array:30 [▼
    "events" => true
    "router" => true
    "App\Http\Kernel" => true
    "Illuminate\Contracts\Http\Kernel" => true
    "Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables" => true
    "Illuminate\Foundation\Bootstrap\LoadConfiguration" => true
    "Illuminate\Foundation\Bootstrap\HandleExceptions" => true
    "env" => true
    "Illuminate\Foundation\Bootstrap\RegisterFacades" => true
    "Illuminate\Foundation\PackageManifest" => true
    "Illuminate\Foundation\Bootstrap\RegisterProviders" => true
    "Livewire\LivewireManager" => true
    "Livewire\EventBus" => true
    "Spatie\Ignition\Contracts\ConfigManager" => true
    "log" => true
    "Illuminate\Foundation\Bootstrap\BootProviders" => true
    "db.factory" => true
    "db" => true
    "files" => true
    "Livewire\Mechanisms\PersistentMiddleware\PersistentMiddleware" => true
    "Livewire\Mechanisms\HandleComponents\HandleComponents" => true
    "Livewire\Mechanisms\HandleRequests\HandleRequests" => true
    "Livewire\Mechanisms\FrontendAssets\FrontendAssets" => true
    "Livewire\Mechanisms\ComponentRegistry" => true
    "blade.compiler" => true
    "Livewire\Mechanisms\ExtendBlade\ExtendBlade" => true
    "view.engine.resolver" => true
    "Livewire\Mechanisms\CompileLivewireTags" => true
    "Livewire\Mechanisms\RenderComponent" => true
    "Livewire\Mechanisms\DataStore" => true
  ]
```


Also before this commit, Livewire Component aliases shows the following contents:

```php
array:11 [▼ // vendor/livewire/livewire/src/Mechanisms/ComponentRegistry.php:141
  "navigation-menu" => "Laravel\Jetstream\Http\Livewire\NavigationMenu"
  "profile.update-profile-information-form" => "Laravel\Jetstream\Http\Livewire\UpdateProfileInformationForm"
  "profile.update-password-form" => "Laravel\Jetstream\Http\Livewire\UpdatePasswordForm"
  "profile.two-factor-authentication-form" => "Laravel\Jetstream\Http\Livewire\TwoFactorAuthenticationForm"
  "profile.logout-other-browser-sessions-form" => "Laravel\Jetstream\Http\Livewire\LogoutOtherBrowserSessionsForm"
  "profile.delete-user-form" => "Laravel\Jetstream\Http\Livewire\DeleteUserForm"
  "api.api-token-manager" => "Laravel\Jetstream\Http\Livewire\ApiTokenManager"
  "teams.create-team-form" => "Laravel\Jetstream\Http\Livewire\CreateTeamForm"
  "teams.update-team-name-form" => "Laravel\Jetstream\Http\Livewire\UpdateTeamNameForm"
  "teams.team-member-manager" => "Laravel\Jetstream\Http\Livewire\TeamMemberManager"
  "teams.delete-team-form" => "Laravel\Jetstream\Http\Livewire\DeleteTeamForm"
]
[] // vendor/livewire/livewire/src/Mechanisms/ComponentRegistry.php:141
```

And after this commit, Livewire Component aliases shows empty:

```php
[] // vendor/livewire/livewire/src/Mechanisms/ComponentRegistry.php:148
[] // vendor/livewire/livewire/src/Mechanisms/ComponentRegistry.php:148
```

I'm still digging to understand why this behavior happens, and possibly fix the issue..

**Comment by andrewdwallo** [comment]
Maybe something to do with dynamic component registration, static methods, singleton's used in Jetstream? Components can be switched in the ServiceProvider.

**Comment by Omranic** [comment]
**The Issue:** identified pertains to the registration process of mechanisms in the `LivewireServiceProvider`. Here's a simplified explanation:

- Previously, mechanisms were created using standard PHP object creation `(new $mechanism)`, not involving Laravel's service container, hence no service container events were triggered.
- With the recent change, these mechanisms are now instantiated via Laravel's IoC service container `app($mechanism)`, causing service container events to be triggered.
- 💡 **The core of the problem** arises when the `Livewire\Mechanisms\CompileLivewireTags` mechanism is instantiated. It extends `Illuminate\View\Compilers\ComponentTagCompiler` which has a constructor dependency of `Illuminate\View\Compilers\BladeCompiler` , and its creation via the service container triggers events. On the other hand, the `JetstreamServiceProvider` prematurely listens to this event, leading to a situation where Livewire components are being registered before all necessary mechanisms are set up, particularly the `Livewire\Mechanisms\ComponentRegistry` which comes next in order after `Livewire\Mechanisms\CompileLivewireTags`.

**Suggested fix:**
- Move the registration of Livewire components in `JetstreamServiceProvider` to the `boot()` method, which is where it should be. This ensures all mechanisms are in place before any component registration begins. It also makes the additional event handling for BladeCompiler resolution unnecessary. `$this->callAfterResolving(BladeCompiler::class, fn () => '');`
- A pull request (PR) will be proposed to the Jetstream repository to address this issue.

LMK if you've different thoughts, thanks!

**Pull request merged**
