### PR TITLE
Add `StringNormalization` support to arrays and collections to fix Safari checksum issues

### PR DESCRIPTION
**Pull request by Balsakup**
Update `StringNormalization` test to prove that special chars are not normalized and break Safari checksum.  
https://github.com/livewire/livewire/pull/4942 don't fix all cases.

### CODE REVIEW

**Comment by Okipa** [comment]
@Balsakup Nice 👍🏻

Seems OK to me, what do you think about this @joshhanley?

**Comment by joshhanley** [comment]
@Balsakup thanks for the PR! All looks good for collections/ arrays/ strings.

What about the scenario where there is an eloquent model (or eloquent collection) which has special chars in attributes, does that break too?

**Comment by Balsakup** [comment]
@joshhanley, I added some tests for the Eloquent collections and models, and everything is working as expected

**Comment by joshhanley** [comment]
@Balsakup thanks! I've been running some performance checks on this to make sure we don't increase the processing time too much. Just waiting on Caleb to have a look too before actioning further 🙂

**Comment by joshhanley** [comment]
So we've run some benchmarks on this PR in comparison to the current master branch, and the results are as follows:

As this PR only affects collections and arrays, so that is what has been tested.

Benchmark 1 - array with 10,000 items and also a collection of that array - running 100 iterations of dehydrate method:

Master:
Total time: 3.125s
Average: 31.25ms

This PR:
Total time: 3.848s
Average: 38.48ms


Benchmark 2 - array with 10 nested arrays of 10,000 items (100,000 items total) and also a collection of that array - running 100 iterations of dehydrate method:

Master:
Total time: 2.692s
Average: 26.92s

This PR:
Total time: 12.956s
Average: 129.56ms

As you can see in the benchmark 1, running a combined total of 20,000 items between the array and the collection, the difference between master and this PR is nominal.

There is a noticeable difference in benchmark 2, between master and this PR, approx 5 times slower. But, that is essentially testing a combined total of 200,000 items between the array and the collection and it's still only ~130ms.



Our conclusion is, that those times are not ideal, but that is likely due to the recursion through the arrays/collections. It's also unlikely that someone will have that much data loaded into a single array.

As such, we are going to merge this, to ensure Safari is properly supported and doesn't throw the checksum issue.

There might be a better place to do this processing, like somewhere where we are already traversing the property data, which could make this more efficient. That's something we can look into in the future.

**Comment by joshhanley** [comment]
Thanks for the PR @Balsakup!

**Comment by Balsakup** [comment]
@joshhanley Thank you so much for accepting my contribution. I am grateful for the opportunity to work with you and contribute to the project.

**Pull request merged**
