### PR TITLE
Support for native enums

### PR DESCRIPTION
**Pull request by andreascreten**
Added support for native enums, as discussed in https://github.com/livewire/livewire/discussions/4411

### CODE REVIEW

**Comment by joshhanley** [comment]
@andreascreten have triggered tests to run again 🙂

**Comment by andreascreten** [comment]
@joshhanley could you trigger them again? When I run them on my fork they are [all green](https://github.com/andreascreten/livewire/actions/runs/1717760143).

**Comment by joshhanley** [comment]
@andreascreten yup just triggered them again 🙂

**Comment by calebporzio** [comment]
Thanks for this!

**Pull request merged**
