### PR TITLE
Failing Test: Morph Marker when If contains calculation

### PR DESCRIPTION
**Pull request by fotrino**
This bug is related to [Discussion 7819](https://github.com/livewire/livewire/discussions/7819) &  [Discussion 6663](https://github.com/livewire/livewire/discussions/6663).

Recently I run into a bug caused by Injecting Morph Markers, which causes the following error in the console.

Screenshot 2024-02-14 at 6 16 45 PM

This is the basic setup to replicate the issue:

```php
class Todo extends Component
{
    public $someProperty = 1.5;
    
    public function render() 
    {
        return '<div> @if ($someProperty > 0) <span> {{ $someProperty }} </span> @endif </div>';
    }
}
```

Instead of wrapping the `span`element with `<!--[if BLOCK]><![endif]-->` & `<!--[if ENDBLOCK]><![endif]-->`, it only renders the ENDBLOCK.
```html
<div>
    <span> 1.5 </span>
    <!--[if ENDBLOCK]><![endif]-->
</div>
```

### CODE REVIEW

**Comment by calebporzio** [comment]
Mmmm yeah, this is a tricky one, what's happening is: the parser sees `@if` before `>` and assumes it's inside an HTML tag so it skips adding it.

**Comment by fotrino** [comment]
Yes, I've been trying a few different combinations but it blows up elsewhere when i run the test suite. Maybe there is a regex super genius out there that can help 😄

**Comment by joshhanley** [comment]
Yep couldn't get it working just by modifying the regex. Got a different strategy working and pushed up a new PR #7967.

**Comment by calebporzio** [comment]
Closing as @joshhanley fixed it in #7967

**Pull request closed without merging**
