### PR TITLE
Fix pagination query string not set when using lazy components

### PR DESCRIPTION
**Pull request by PhiloNL**
Failing test for https://github.com/livewire/livewire/discussions/6527.
If you enable lazy loading on a component the `page` query parameter will no longer be set.

### CODE REVIEW

**Comment by joshhanley** [comment]
@PhiloNL thanks for the failing test!

I've been working on a fix for this issue. There are some failing tests, one which is related and two that are not (teleport back button stuff - these are also failing on PR #6759 after I merged in master).

Normally (without lazy), a component's root element will have an attribute `wire:effects` which contains the logic for setting up pagination using the query string on the front end.

But the issue with the lazy component is the component gets initialised on the frontend, and the (empty) `wire:effects` get processed. Then the component actually mounts and initialises the pagination on the back end. But as the query string feature hasn't been told to track the paginators property, the query string then never gets updated.

So this fix has required a few changes:

One is `SupportPagination` should add an effect to the first json payload (aka the first time the lazy component is actually mounted).

I then had to update the queryString implementation on the front end to listen to effects changes on subsequent requests and not just `component.init` which it was before. That way the effect that comes through from mounting the lazy component actually can be processed.

So the above is all working happily.

The last piece, which I haven't managed to get running yet (which you can see in the pagination failing test) is loading the initial pagination pages from the queryString. Currently, when the lazy component mounts and pagination is initialised, the request URL and queryString is actually that of Livewire's update route, as such it doesn't have any pagination page details in the queryString at all.

So not sure how to solve that just yet, but open to ideas.

**Comment by calebporzio** [comment]
Good points @joshhanley - this is a deep one.

I think I need to explore a different, more stable implementation for lazy components, before we add lots of little conditionals for lazy components.

#6992

**Comment by mozex** [comment]
Any update on this?

**Comment by calebporzio** [comment]
fixed in #2686

**Comment by HuseyinYeldan** [comment]
Still pagination with lazy loading doesn't work. Any fix?

**Pull request closed without merging**
