### PR TITLE
Fix dusk test headless mode in CI

### PR DESCRIPTION
**Pull request by nuernbergerA**
Download test broken since Chrome/Chromium version 110.x

for more details see
https://github.com/SeleniumHQ/selenium/issues/11637
https://www.selenium.dev/blog/2023/headless-is-going-away/

### CODE REVIEW

**Comment by joshhanley** [comment]
@nuernbergerA thanks! Some other tests were failing so I’ve re-run the tests again.

**Comment by joshhanley** [comment]
@nuernbergerA went down a rabbit hole trying to work out why these tests are failing. Couldn't work out what was going on.

Was going to merge this along with the middleware fix PR, but couldn't get the tests going.

Ended up locking ChromeDriver to version 109 on the middleware PR just so I could get all tests to pass to tag a release.

Not sure what has changed in 110 or the new headless mode that is causing these test's issues.

**Comment by nuernbergerA** [comment]
@joshhanley no worries it's fine for me if we stick to 109 for now.

My problem is that I can run the test on my local env only in headless mode, with ui I have several errors that are not livewire related.

If I have time this week I will look into it

**Comment by joshhanley** [comment]
@nuernbergerA yeah I was just finding that too. I wonder when that started 😕 I normally only run in headless mode locally so don't know when the UI errors started happening.

**Comment by nuernbergerA** [comment]
I'm using Ubuntu what OS are you using @joshhanley ?

**Comment by joshhanley** [comment]
I'm running MacOS Monterey

**Comment by nuernbergerA** [comment]
Have you tried running it with Safari?

**Comment by joshhanley** [comment]
@nuernbergerA ha you're funny! 😂 nah I never run with Safari. Will run it now and see what it does

**Comment by joshhanley** [comment]
🤦‍♂️

image

**Pull request closed without merging**
