### PR TITLE
Add EchoManager

### PR DESCRIPTION
**Pull request by davidpiesse**
Adds EchoManager class for JS Component to abstract & encapsulate Echo logic.

### CODE REVIEW

**Comment by faustbrian** [comment]
@davidpiesse is this still being worked on?

**Comment by davidpiesse** [comment]
Not currently.

The shift in the code base means it need rewriting (again) and I don't have the time right now alas.

**Comment by calebporzio** [comment]
Closing for now.

**Comment by davidpiesse** [comment]
PR'd with #570 anew :)

**Pull request closed without merging**
