### PR TITLE
Add route model binding to actions

### PR DESCRIPTION
**Pull request by lancepioch**
Allows you to pass the model's route key (value) into a component's public function and have it be auto resolved to your type hinted model's instance.

This is based on #910

I'm working on tests still.

Todo:

* [ ] Implement Tests
* [ ] Whether to base off current code or pull request above
* [ ] Consider security implications

Example Component Function:
```php
public function setUsername(User $user, $username)
{
    $user->username = $username;
    $user->save();
}
```

Example View Call:
```html
<a wire:click.prevent="setUsername(1, 'test')"></a>
```

### CODE REVIEW

**Comment by DanHarrin** [comment]
Closes #701.

**Comment by AbdelElrafa** [comment]
Is there any update on this?

**Comment by mattharcourt** [comment]
@lancepioch - this PR could be expanded a bit to also solve #1067. 

If `ComponentConcerns\HandlesActions@resolveActionParameters()` is generalized to accept a `ReflectionMethod` instead of the method (to remove the dependency on `this`), it could be utilized in `Macros\RouterMacros@livewire()` in place of the call to `Macros\PretendClassMethodIsControllerMethod@retrieveBindings()`. Would have to make it a static method, or perhaps move it to a `ComponentMethodBinder` class so it could be used in both places.

I should've looked closer before submitting #1068 as this would be a better solution. I'm willing to close that PR and add to this if interested.

**Comment by mattharcourt** [comment]
Regarding my previous comment: after digging deeper, route binding is fundamentally different from action binding. PR #1068 has been updated to pursue route binding. 

This PR should continue on it's own for action binding. 

There may be additional logic to pull from Laravel's [`ImplicitRouteBinding`](https://github.com/laravel/framework/blob/192356b8d519dc307bd453786551fc5c765c7cab/src/Illuminate/Routing/ImplicitRouteBinding.php#L21) if there's interest in implementing scoped binding of related models for actions.

**Pull request closed without merging**
