### PR TITLE
[v3] Add 'upload' as reserved keywords to the documentation

### PR DESCRIPTION
**Pull request by PhiloNL**
Follow up on: https://github.com/livewire/livewire/pull/5852#issuecomment-1650212964

### CODE REVIEW

**Comment by devajmeireles** [comment]
Perhaps this should be updated?

CleanShot 2023-07-25 at 5 43 55

**Comment by joshhanley** [comment]
@devajmeireles those reserved words are more for component names, which the make command already uses anyway, so I don't think a warning is necessary for them (plus they are standard PHP reserved words).

Where as this PR is for a word that Livewire itself is reserving, so a method name shouldn't match it. If there were other words that Livewire specifically reserves, then yeah I agree they should be added 🙂

**Comment by calebporzio** [comment]
Thanks @PhiloNL and @joshhanley for the extra context!

**Comment by akunbeben** [comment]
I also have a component property named `$attributes`, which is reserved by the `Livewire\Features\SupportAttributes\HandlesAttributes` trait. Is it necessary to add a warning for this? Or it's just my specific case? What do you guys think?

image

**Comment by joshhanley** [comment]
@akunbeben yeah it should probably be listed on the validation page.

**Pull request merged**
