### PR TITLE
Added config file - fixes #192

### LINKED ISSUE #192: Not Working if namespace is not App
**Describe the bug**
Unable to find component

**To Reproduce**
My laravel App is named "Portal" instead of "App" - the component discovering won't work

**Expected behavior**
Show Livewire Component

**Additional context**
namespace App is hardcoded in LivewireMakeCommandParser.php@classNamespace and Component.php@getName

Solution: change it to config('app.name') instead of 'App'

### PR DESCRIPTION
**Pull request by jetwes**
Adds a dedicated config file with the option to use a custom namespace and a custom view folder
references #192

### CODE REVIEW

**Comment by tillkruss** [comment]
Comments would be nice that explain the options in detail. Laravel-style.

**Comment by tillkruss** [comment]
What about defaults of the config file doesn’t exist?

**Comment by tillkruss** [comment]
@calebporzio: This can be closed in favor of #235, eh?

**Comment by jetwes** [comment]
no worries

**Comment by calebporzio** [comment]
Thanks @jetwes!

**Pull request closed without merging**
