### PR TITLE
Handle custom routing requests when present

### PR DESCRIPTION
**Pull request by eric-hansen**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
Created a discussion: https://github.com/livewire/livewire/discussions/4698

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required, where possible)
No, if issue let me know as not sure exactly where/how this should be tested nor does a simple `composer install` make the whole test-suite pass.  Using Docker so unsure of what packages are missing if any.

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
I'd like to say everything that needs to be said is in the discussion, but if not then let me know and I can edit this to elaborate more.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by calebporzio** [comment]
Closing this because no test has been provided. By providing a test, we can ensure this fix is fixed forever and this bug isn't re-introduced. Please re-submit after adding a test. Thanks!

**Comment by eric-hansen** [comment]
> Closing this because no test has been provided. By providing a test, we can ensure this fix is fixed forever and this bug isn't re-introduced. Please re-submit after adding a test. Thanks!

2 questions:

1) Since this seems to only be affected when using `app()`/`request()`, is this testable?
2) If tests are a pre-req, then why was #4619 merged without one?

**Comment by joshhanley** [comment]
@eric-hansen yeah you should be able to test it, you said you had a test that fails without this change, so maybe try and replicate that test and component.

Somethings can be too difficult to test with Livewire due to the nature of the front end interaction, so occasionally (rarely), will a PR be approved without tests. But as it was, that was an oversight, I have just added tests for it 🙂

> nor does a simple composer install make the whole test-suite pass.
In regards to this comment above, a composer install isn't enough to get Livewire's tests running due to using Laravel Dusk. Please have a look at our contribution guide as to the extra steps required https://laravel-livewire.com/docs/2.x/contribution-guide

I don't know if you can run dusk in docker or not, as I don't use docker (I use valet), so that is something you will need to work out.

Hope this helps!

**Comment by eric-hansen** [comment]
@joshhanley I'll see if I can actually write a test for it.  The test I wrote was specific to the application I use Livewire for, not a test for Livewire itself.  So if the helpers mentioned a few times now are exposed as well then it may be doable.  If not then I hope we can assess whether a test is necessary to move forward.

As for Dusk, et. al. I'll read deeper and see what happens.

Thanks for the feedback.

**Comment by joshhanley** [comment]
@eric-hansen yeah generally that is how I come across bugs too.

So what I like to do is copy the code from my main app, into a small test app with Livewire, then I try to delete as much code as I can until I can replicate the issue with as little code as possible.

That then become the code for the test which I submit to Livewire. Most of Livewire's tests are components that look and act exactly the same way they would in an app (which Dusk is really great for simulating).

No worries!

**Comment by eric-hansen** [comment]
Should we continue any discussion regarding testing and such here or in the discussion thread?

Not usually contributing to projects that enforce the Discussion feature of GitHub so not sure what is preferred here.

**Pull request closed without merging**
