### PR TITLE
Add dark tailwind classes to pagination views

### PR DESCRIPTION
**Pull request by Alexxlml**
Please review the contribution guide first at: https://livewire.laravel.com/docs/contribution-guide

1️⃣ Is this something you want/need? Did you create a discussion about it first?
Yes, it is necessary to update the styles with `dark:` classes since the `laravel new` command now allows you to use the dark theme with Jetstream.
I didn't create a discussion about it.

2️⃣ Did you create a branch for your solution/feature? (Main branch public relations will be closed)
Yes.

3️⃣ Does it contain multiple unrelated changes? Separate the PRs.
No, just the tailwind classes on the necessary elements.

4️⃣ Does it include tests? (Required)
No, they are just visual changes.

5️⃣ Include a detailed description (including small code snippets if possible) of the improvement and the reasons why it is useful.
I based it on the following Laravel Framework PR:

**Add dark mode classes**
[[10.x] Update tailwind.blade.php for dark mode](https://github.com/laravel/framework/pull/49515)

tailwind.blade.php from livewire package:

```
<div>
    <p class="text-sm text-gray-700 leading-5">
        <span>{!! __('Showing') !!}</span>
        <span class="font-medium">{{ $paginator->firstItem() }}</span>
        <span>{!! __('to') !!}</span>
        <span class="font-medium">{{ $paginator->lastItem() }}</span>
        <span>{!! __('of') !!}</span>
        <span class="font-medium">{{ $paginator->total() }}</span>
        <span>{!! __('results') !!}</span>
    </p>
</div>
```

tailwind.blade.php from Laravel package:
```
<div>
    <p class="text-sm text-gray-700 leading-5 dark:text-gray-400">
        {!! __('Showing') !!}
        @if ($paginator->firstItem())
        <span class="font-medium">{{ $paginator->firstItem() }}</span>
        {!! __('to') !!}
        <span class="font-medium">{{ $paginator->lastItem() }}</span>
        @else
        {{ $paginator->count() }}
        @endif
        {!! __('of') !!}
        <span class="font-medium">{{ $paginator->total() }}</span>
        {!! __('results') !!}
    </p>
</div>
```

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@Alexxlml thanks for the PR! I noticed you changed some other classes and removed some of them.

Can I suggest only adding dark mode classes in this PR and separating the others into a new PR so they can be reviewed properly?

Thanks!

**Comment by Alexxlml** [comment]
@joshhanley thanks for the feedback.
Of course, sorry, I didn't realize that some classes were removed and others changed, such as `shadow-outline-blue` for `ring-gray-300`, apparently this is because the first one is a Tailwind class V1, this was replaced by the `ring` class in Tailwind V2.

I'll separate the changes as you suggest.

**Comment by Alexxlml** [comment]
Hello, I have created a new PR with commits made for each change in the tailwind and simple-tailwind pagination views.

I have attached the pull requests made in the [Laravel Framework](https://github.com/laravel/framework) repository.

**Comment by joshhanley** [comment]
@Alexxlml thanks! Can you remove dark mode classes from that PR and only include dark mode classes in this PR (and update the title/description), so they can be reviewed separately? Thanks!

**Comment by Alexxlml** [comment]
@joshhanley Sure.

**Comment by Alexxlml** [comment]
Hello @joshhanley , I have reverted the commit with all the changes to include only the dark classes in a new one, without changing any other class in this PR, I have also updated the title and description so that it is descriptive of the addition of dark classes.

In the other PR I have removed only the dark classes in a new commit.
I'm new to contributing and I don't know if these two PRs will give you a lot of trouble merging the changes.

I thank you for your patience with me.
I am open to feedback to improve my skills.

**Comment by joshhanley** [comment]
@Alexxlml great thanks! 😁

**Comment by Alexxlml** [comment]
@joshhanley  It's true, now I understand it.
Thanks for all the support on this PR.

**Comment by calebporzio** [comment]
Thank you! And thanks for your watchful eye @joshhanley

**Pull request merged**
