### PR TITLE
Allow dispatching CustomEvent with falsy value

### PR DESCRIPTION
**Pull request by adriaanzon**
1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
It relates to #4617. It's not a fix for using `$dispatch('input', null)`, but at least it allows you to dispatch other falsy values such as `''`, `0` or `false`. I don't know a fix for `$dispatch('input', null)`, because you would have to distinguish the CustomEvent from the one Safari sends, where the value of `e.detail` is also `null`.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
No

4️⃣ Does it include tests? (Required)
Yes

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
See my demo of the problem in the original post of #4617.

### CODE REVIEW

**Comment by joshhanley** [comment]
@adriaanzon thanks for the PR! I've triggered the tests to run

**Comment by adriaanzon** [comment]
The tests were failing. I saw some fixes for the test suite on the master branch so I have rebased my changes.

**Comment by joshhanley** [comment]
@adriaanzon thanks! I have triggered them again

**Comment by calebporzio** [comment]
Thanks! Makes sense!

**Pull request merged**
