### PR TITLE
Add `.live` support to modelable

### PR DESCRIPTION
**Pull request by calebporzio**
This is an alternative fix to #7166

### CODE REVIEW

**Comment by DanielCoulbourne** [comment]
LGTM

**Comment by joshhanley** [comment]
This PR also fixes the issue raised in PR #7165. So I have added the test from there into this PR.

**Comment by woodspire** [comment]
Please add some doc for this new feature.

**Comment by joshhanley** [comment]
@woodspire it's not a new feature really, just something people would expect to work, which is `<livewire:my-component wire:model.live="someProp" />`.

PRs to the docs are welcome if you feel it should be added 🙂

**Pull request merged**
