### PR TITLE
disable user-select on disabled pagination links

### PR DESCRIPTION
**Pull request by dianfishekqi**
Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?
https://github.com/livewire/livewire/discussions/4672

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)
yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
no
4️⃣ Does it include tests? (Required, where possible)
no
5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.
Details are in the discussion.

Thanks for contributing! 🙌

### CODE REVIEW

**Comment by joshhanley** [comment]
@dianfishekqi thanks for the PR! Can you undo the auto formatting so the only changes are the addition to the spans? 

Thanks!

**Comment by dianfishekqi** [comment]
> @dianfishekqi thanks for the PR! Can you undo the auto formatting so the only changes are the addition to the spans?
> 
> Thanks!

Remove headwind formatting, thanks!

**Comment by joshhanley** [comment]
@dianfishekqi great, thanks for that!

**Comment by calebporzio** [comment]
Great, thank you!

**Pull request merged**
