### PR TITLE
Fixed wrong manifest path in Vapor

### PR DESCRIPTION
**Pull request by lkmadushan**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.

5️⃣ Thanks for contributing! 🙌

See the attachment.
Screenshot 2021-04-09 at 2 13 16 AM

### CODE REVIEW

**Comment by calebporzio** [comment]
Hi @lkmadushan - I believe you that this is the right adjustment. But can you provide some further proof and context as to when/why this changed? Thanks!

**Comment by jelleroorda** [comment]
Maybe it would be an idea to handle it the same way as the vapor core package is doing in it's [AppHandler.php#L30](https://github.com/laravel/vapor-core/blob/2.0/src/Runtime/Handlers/AppHandler.php#L30)?

**Comment by calebporzio** [comment]
@jelleroorda, are you suggesting we make this dynamic and use `$_ENV['LAMBDA_TASK_ROOT']` to prefix `/bootstrap...` instead of hardcoding `/tmp...`?

That makes sense.

I wonder how to make this change without it being a breaking change and still supporting the config.

Would love someone to propose a solution. Thanks!

**Comment by calebporzio** [comment]
Closing due to lack of response - please re-submit this PR if/when you have an update. Thanks for contributing!

> For context, as a maintainer, leaving PR's open for an indefinite amount of time adds overhead to my work. Therefore, if I can't perform an immediate action on a PR, I may close it rather than wait for a response (that sometimes never comes). I Hope you can empathize with that! Thanks again!

**Pull request closed without merging**
