### PR TITLE
[JS] wire:click paramters

### LINKED ISSUE #517: Strange behavior with comma separated parameter
**Describe the bug**
Strange behavior with comma separated parameter

**To Reproduce**
1) Install latest Laravel and latest livewire (0.5.3)
2) Create livewire component:
`$ php artisan make:livewire test`
3) Update view and component class:
resources/views/livewire/test.blade.php:
```
<div>
    @php
    $text = 'test, test';
    @endphp
    <button wire:click="test('{{ $text }}')">Test</button>
</div>
```

app/Http/Livewire/Test.php
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    private $text;

    public function render()
    {
        return view('livewire.test');
    }

    public function test($text)
    {
        $this->text = $text;
    }
}
```
**Expected behavior**
In browser console:
```
SyntaxError: '' literal not terminated before end of script
```

But if you change the view to (delete one space in `$text`):
```
<div>
    @php
    $text = 'test,test';
    @endphp
    <button wire:click="test('{{ $text }}')">Test</button>
</div>
```
Everything works fine. 

**Desktop (please complete the following information):**
 - Browser is any: FF, Chrome, Safari and etc.

### PR DESCRIPTION
**Pull request by nuernbergerA**
fixes #517 

The current implementation will split the parameter string by comma without checking if the comma is part of a string inside a parameter

```js
let paramString = "'foo, bar', true , 'baz',null,'x,y'"
let params = paramString.split(/\s?,\s?/)

//result
["'foo", "bar'", "true", "'baz'", "null", "'x", "y'"]
```

With this PR my focus is not a delimiter, its the paramerter itself.
A paramter must follow some rules:
* be a constance sequence of word-charaters (true, null, someVar)
* start/end with ' ('some string')

so the above example code will look like this:
```js
let paramString = "'foo, bar', true , 'baz',null,'x,y'"
let params = paramString.match(/((?:'[^']*')|\w*)/g).filter(Boolean)
```

the only 'downside' now is that delimiters are optional so this would also be valid
```js
let paramString = "'foo, bar' true 'baz'null'x,y'"
let params = paramString.match(/((?:'[^']*')|\w*)/g).filter(Boolean)
```
or
```js
let paramString = "'foo, bar'|true|'baz'|null|'x,y'"
let params = paramString.match(/((?:'[^']*')|\w*)/g).filter(Boolean)
```

will all result in
```js
["'foo, bar'", "true", "'baz'", "null", "'x,y'"]
```

If you want to ensure a comma is used a a sperator we need a more complex regex

### CODE REVIEW

**Comment by nuernbergerA** [comment]
Ok after some research i found a solution that might fit better.

- use `.split` again (detects only comma outside apostrophe, with optional space around)
- keep `.filter(Boolean)` to handle empty brackets `callSomething()`

**Comment by nuernbergerA** [comment]
if array support is needed as mentioned in #560 we have to tweak the regex again
```regex
/ ?, ?(?=(?:[^'\[\]]|[\[\]'][^'\[\]]*['\[\]])*$)/
```

**Comment by calebporzio** [comment]
Ugh, maintaining a regex for this kind of thing is really dark. Are there other pure-js solutions to this? like doing an actual function call on a made-up function to get the parameters passed in? I don't know, just seems like going further down the regex path is a bad idea. Thoughts?

**Comment by nuernbergerA** [comment]
I would stick to the current state of this PR to fix the initial issue and open up a new issue to discuss futher steps.

**Comment by calebporzio** [comment]
Ok, I can abide.

Can we expand the regex to include other forms of quotes? backticks and double quotes?

Sometimes people do things like this: `<input wire:click='doSomething("with-this")'`

I'd like to at least support double-quotes.

Thanks for this PR!

**Comment by nuernbergerA** [comment]
[Visual Regex](https://embed.ihateregex.io/make/JUMyJUEwJTNGJTJDJTIwJTNGKCUzRiUzRCglM0YlM0ElNUIlNUUlMjInJTYwJTVDJTVDJTVCJTVDJTVDJTVEJTVEJTdDJyU1QiU1RSclNUQqJyU3QyUyMiU1QiU1RSUyMiU1RColMjIlN0MlNjAlNUIlNUUlNjAlNUQqJTYwJTdDJTVDJTVDJTVCJTVCJTVFJTVDJTVDJTVEJTVEKiU1QyU1QyU1RCkqJTI0KQ)
```regex
 ?, ?(?=(?:[^"'`\[\]]|'[^']*'|"[^"]*"|`[^`]*`|\[[^\]]*\])*$)
```

Ok with this boy we can support
- single-quotes
- double-quotes
- backticks
- arrays
- js-variables (incl. boolean/null)
- even all mixed together in a single line

**Comment by nuernbergerA** [comment]
To ignore escaped single-quotes
```regex
'[^'\\]*(?:\\.[^'\\]*)*'
```

We end up with this monster
```regex
/ ?, ?                             #match comma optional surrounded by a space
(?=
    (?:
        [^"'`\[\]]|
        '[^'\\]*(?:\\.[^'\\]*)*'|  #single-quotes
        "[^"\\]*(?:\\.[^"\\]*)*"|  #double-quotes
        `[^`\\]*(?:\\.[^`\\]*)*`|  #backticks
        \[[^\]]*\]                 #array
    )*
$)/
```

**Comment by calebporzio** [comment]
Yeah gross, I'm cool with it though. Regex is hard for me to read when it's short anyway, so it doesn't seem like a big deal to me (especially with a well-named variable or comment).

I'd rather support ""

**Comment by calebporzio** [comment]
Love this. Thanks so much @nuernbergerA - great PR!

**Comment by nuernbergerA** [comment]
closes #587 and #517

**Pull request merged**
