### PR TITLE
Fix persistent middleware type error on Laravel 10

### PR DESCRIPTION
**Pull request by joshhanley**
This PR fixes an issue with persistent middleware and Laravel 10, see discussion #5560.

Due to the new return types in Laravel 10, Livewire is currently throwing an error when a middleware that has a `Response` return type is passed through the persistent middleware pipeline.

image

This is because our pipeline is currently returning nothing, hence returning `null` which isn't a valid return type for the middleware.

This PR changes it to return a response of `noop`.

Have submitted this with just a failing test first, to ensure all Laravel and PHP version tests will work property with the test changes I have made. And if they all work as expected (and the Laravel 10 one fails), then I will push the fix.

Hope this helps!

### CODE REVIEW

**Comment by joshhanley** [comment]
Well that didn't work as I expected. Have pushed the fixed and marked as draft for now until I can fix tests.

**Comment by nuernbergerA** [comment]
I can take a look into it

**Comment by nuernbergerA** [comment]
See https://github.com/joshhanley/livewire/pull/1

**Comment by jerothor** [comment]
+ 1 i'm getting this middleware error with every single app i upgrade to laravel 10

**Comment by jamesautodude** [comment]
> +1 i'm getting this middleware error with every single app i upgrade to laravel 10

Same! It's mainly when user is logged out though. If the user is logged in, the error doesn't happen - at least for me

**Comment by joshhanley** [comment]
@jamesautodude once I get approval from Caleb, then we’ll sort it out. Hopefully in the next couple of days 🙂

**Comment by jamesautodude** [comment]
> @jamesautodude once I get approval from Caleb, then we’ll sort it out. Hopefully in the next couple of days 🙂

Okay thanks! Not sure if it helps but sometimes Laravel Shift can fix some things, although this issue may be out of the scope of Shift

**Comment by jerothor** [comment]
Please merge and release this. I'm having to revert to L9 for everything which is a bummer.

**Comment by pascalbaljet** [comment]
Not sure if it matters, but `noContent` has a default status of `204`.

**Comment by joshhanley** [comment]
> > @jamesautodude once I get approval from Caleb, then we’ll sort it out. Hopefully in the next couple of days 🙂
> 
> Okay thanks! Not sure if it helps but sometimes Laravel Shift can fix some things, although this issue may be out of the scope of Shift

@jamesautodude oh, this PR is the fix for it, don’t need shift 🙂

@jerothor I understand is frustrating, but its the weekend. It will be sorted soon. 

@pascalbaljet thanks! Good to know. I don’t think it will matter as it’s a fake request anyway. So just ensuring that a response type is returned, to keep the Laravel 10 type system happy, should be enough.

**Comment by jerothor** [comment]
> @jamesautodude oh, this PR is the fix for it, don’t need shift 🙂
> 
> 
> 
> @jerothor I understand is frustrating, but its the weekend. It will be sorted soon. See my comment above re approval.
> 
> 
> 
> @pascalbaljet thanks! Good to know. I don’t think it will matter as it’s a fake request anyway. So just ensuring that a response type is returned, to keep the Laravel 10 type system happy, should be enough. 

Thanks Josh

**Comment by joshhanley** [comment]
This has been merged and tagged in v2.11.3. Thanks to @nuernbergerA for the help!

**Comment by mabdullahsari** [comment]
@joshhanley This PR broke something with redirects. 
I had to revert Livewire to the previous version and pin the version. FYI.

**Comment by jerothor** [comment]
> @joshhanley This PR broke something with redirects. 
> 
> I had to revert Livewire to the previous version and pin the version. FYI.

Redirects working fine for me. 

Post your error and redirect code.

**Comment by mabdullahsari** [comment]
> > @joshhanley This PR broke something with redirects.
> > I had to revert Livewire to the previous version and pin the version. FYI.
> 
> Redirects working fine for me.
> 
> Post your error and redirect code.

See #5568

**Comment by joshhanley** [comment]
Hmm interesting. Have replied to the discussion 🙂

**Pull request merged**
